### ISSUE TITLE
centos 7 openssl-1.1.1k openvpn-2.5.4 build fail

### ISSUE THREAD

**Issue by qq805005062** [OpenVPN/openvpn#185]
crypto_openssl.o: In function `ui_reader':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:1068: undefined reference to `SSL_CTX_get_default_passwd_cb'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:1069: undefined reference to `SSL_CTX_get_default_passwd_cb_userdata'
crypto_openssl.o: In function `cipher_ctx_init':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:772: undefined reference to `EVP_CIPHER_CTX_reset'
crypto_openssl.o: In function `md_ctx_new':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:942: undefined reference to `EVP_MD_CTX_new'
crypto_openssl.o: In function `md_ctx_init':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:958: undefined reference to `EVP_MD_CTX_reset'
crypto_openssl.o: In function `hmac_ctx_new':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:998: undefined reference to `HMAC_CTX_new'
crypto_openssl.o: In function `hmac_ctx_init':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:1015: undefined reference to `HMAC_CTX_reset'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:1019: undefined reference to `HMAC_size'
crypto_openssl.o: In function `hmac_ctx_size':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:1031: undefined reference to `HMAC_size'
crypto_openssl.o: In function `crypto_init_lib':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:155: undefined reference to `OPENSSL_init_crypto'
crypto_openssl.o: In function `md_ctx_free':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:950: undefined reference to `EVP_MD_CTX_free'
crypto_openssl.o: In function `md_ctx_cleanup':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:965: undefined reference to `EVP_MD_CTX_reset'
crypto_openssl.o: In function `hmac_ctx_free':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:1006: undefined reference to `HMAC_CTX_free'
crypto_openssl.o: In function `hmac_ctx_cleanup':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/crypto_openssl.c:1025: undefined reference to `HMAC_CTX_reset'
ssl_openssl.o: In function `openvpn_extkey_rsa_finish':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1194: undefined reference to `RSA_meth_free'
ssl_openssl.o: In function `openvpn_extkey_ec_finish':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1352: undefined reference to `EC_KEY_get_method'
ssl_openssl.o: In function `tls_ctx_server_new':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:112: undefined reference to `TLS_server_method'
ssl_openssl.o: In function `tls_ctx_client_new':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:130: undefined reference to `TLS_client_method'
ssl_openssl.o: In function `tls_ctx_set_options':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:345: undefined reference to `SSL_CTX_set_options'
ssl_openssl.o: In function `tls_ctx_restrict_ciphers_tls13':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:530: undefined reference to `SSL_CTX_set_ciphersuites'
ssl_openssl.o: In function `tls_ctx_set_cert_profile':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:556: undefined reference to `SSL_CTX_set_security_level'
ssl_openssl.o: In function `tls_ctx_check_cert_time':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:638: undefined reference to `X509_get0_notBefore'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:648: undefined reference to `X509_get0_notAfter'
ssl_openssl.o: In function `tls_ctx_load_ecdh_params':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:713: undefined reference to `SSL_CTX_set_options'
ssl_openssl.o: In function `sk_X509_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `sk_X509_value':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_value'
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_value'
ssl_openssl.o: In function `sk_X509_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_num'
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `sk_X509_value':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_value'
ssl_openssl.o: In function `sk_X509_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `tls_ctx_load_cert_file':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:967: undefined reference to `SSL_CTX_get_default_passwd_cb_userdata'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:967: undefined reference to `SSL_CTX_get_default_passwd_cb'
ssl_openssl.o: In function `tls_ctx_load_priv_file':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1036: undefined reference to `SSL_CTX_get_default_passwd_cb_userdata'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1036: undefined reference to `SSL_CTX_get_default_passwd_cb'
ssl_openssl.o: In function `backend_tls_ctx_reload_crl':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1091: undefined reference to `X509_STORE_get0_objects'
ssl_openssl.o: In function `sk_X509_OBJECT_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509_vfy.h:58: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `sk_X509_OBJECT_value':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509_vfy.h:58: undefined reference to `OPENSSL_sk_value'
ssl_openssl.o: In function `backend_tls_ctx_reload_crl':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1096: undefined reference to `X509_OBJECT_get_type'
ssl_openssl.o: In function `sk_X509_OBJECT_delete':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509_vfy.h:58: undefined reference to `OPENSSL_sk_delete'
ssl_openssl.o: In function `backend_tls_ctx_reload_crl':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1099: undefined reference to `X509_OBJECT_free'
ssl_openssl.o: In function `tls_ctx_use_management_external_key':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1486: undefined reference to `X509_get0_pubkey'
ssl_openssl.o: In function `tls_ctx_use_external_ec_key':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1421: undefined reference to `EC_KEY_OpenSSL'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1421: undefined reference to `EC_KEY_METHOD_new'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1428: undefined reference to `EC_KEY_METHOD_set_init'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1429: undefined reference to `EC_KEY_METHOD_set_sign'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1431: undefined reference to `EVP_PKEY_get0_EC_KEY'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1437: undefined reference to `EC_KEY_set_method'
ssl_openssl.o: In function `tls_ctx_use_external_rsa_key':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1283: undefined reference to `EVP_PKEY_get0_RSA'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1287: undefined reference to `RSA_meth_new'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1290: undefined reference to `RSA_meth_set_pub_enc'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1291: undefined reference to `RSA_meth_set_pub_dec'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1292: undefined reference to `RSA_meth_set_priv_enc'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1293: undefined reference to `RSA_meth_set_priv_dec'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1294: undefined reference to `RSA_meth_set_init'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1295: undefined reference to `RSA_meth_set_finish'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1296: undefined reference to `RSA_meth_set0_app_data'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1309: undefined reference to `RSA_get0_key'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1310: undefined reference to `RSA_set0_key'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1311: undefined reference to `RSA_set_flags'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1314: undefined reference to `RSA_meth_free'
ssl_openssl.o: In function `tls_ctx_use_external_ec_key':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1439: undefined reference to `EC_KEY_METHOD_free'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1434: undefined reference to `EC_KEY_METHOD_free'
ssl_openssl.o: In function `tls_ctx_use_external_rsa_key':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1337: undefined reference to `RSA_meth_free'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1290: undefined reference to `RSA_meth_set_pub_enc'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1291: undefined reference to `RSA_meth_set_pub_dec'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1292: undefined reference to `RSA_meth_set_priv_enc'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1293: undefined reference to `RSA_meth_set_priv_dec'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1294: undefined reference to `RSA_meth_set_init'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1295: undefined reference to `RSA_meth_set_finish'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1296: undefined reference to `RSA_meth_set0_app_data'
ssl_openssl.o: In function `sk_X509_INFO_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:254: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `sk_X509_INFO_value':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:254: undefined reference to `OPENSSL_sk_value'
ssl_openssl.o: In function `sk_X509_NAME_find':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:77: undefined reference to `OPENSSL_sk_find'
ssl_openssl.o: In function `sk_X509_NAME_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:77: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `sk_X509_INFO_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:254: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `sk_X509_INFO_pop_free':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:254: undefined reference to `OPENSSL_sk_pop_free'
ssl_openssl.o: In function `sk_X509_NAME_new':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:77: undefined reference to `OPENSSL_sk_new'
ssl_openssl.o: In function `sk_X509_NAME_push':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:77: undefined reference to `OPENSSL_sk_push'
ssl_openssl.o: In function `sk_X509_NAME_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509.h:77: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `print_cert_details':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:2071: undefined reference to `EVP_PKEY_get0_EC_KEY'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:2073: undefined reference to `EVP_PKEY_get0_EC_KEY'
ssl_openssl.o: In function `show_available_tls_ciphers_list':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:2161: undefined reference to `TLS_method'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:2193: undefined reference to `SSL_get1_supported_ciphers'
ssl_openssl.o: In function `sk_SSL_CIPHER_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/ssl.h:958: undefined reference to `OPENSSL_sk_num'
ssl_openssl.o: In function `sk_SSL_CIPHER_value':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/ssl.h:958: undefined reference to `OPENSSL_sk_value'
ssl_openssl.o: In function `sk_SSL_CIPHER_free':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/ssl.h:958: undefined reference to `OPENSSL_sk_free'
ssl_openssl.o: In function `get_highest_preference_tls_cipher':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:2275: undefined reference to `TLS_method'
ssl_openssl.o: In function `openvpn_extkey_ec_finish':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:1353: undefined reference to `EC_KEY_METHOD_free'
ssl_openssl.o: In function `tls_ctx_set_cert_profile':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:548: undefined reference to `SSL_CTX_set_security_level'
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:552: undefined reference to `SSL_CTX_set_security_level'
ssl_openssl.o: In function `get_ssl_library_version':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_openssl.c:2296: undefined reference to `OpenSSL_version'
ssl_verify_openssl.o: In function `sk_ASN1_OBJECT_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/asn1.h:536: undefined reference to `OPENSSL_sk_num'
ssl_verify_openssl.o: In function `sk_ASN1_OBJECT_value':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/asn1.h:536: undefined reference to `OPENSSL_sk_value'
ssl_verify_openssl.o: In function `sk_ASN1_OBJECT_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/asn1.h:536: undefined reference to `OPENSSL_sk_num'
ssl_verify_openssl.o: In function `sk_ASN1_OBJECT_pop_free':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/asn1.h:536: undefined reference to `OPENSSL_sk_pop_free'
ssl_verify_openssl.o: In function `tls_verify_crl_missing':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_verify_openssl.c:781: undefined reference to `X509_STORE_get0_objects'
ssl_verify_openssl.o: In function `sk_X509_OBJECT_value':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509_vfy.h:58: undefined reference to `OPENSSL_sk_value'
ssl_verify_openssl.o: In function `tls_verify_crl_missing':
/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn/ssl_verify_openssl.c:786: undefined reference to `X509_OBJECT_get_type'
ssl_verify_openssl.o: In function `sk_X509_OBJECT_num':
/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/openssl/x509_vfy.h:58: undefined reference to `OPENSSL_sk_num'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:638：openvpn] 错误 1
make[3]: 离开目录“/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src/openvpn”
make[2]: *** [Makefile:432：all-recursive] 错误 1
make[2]: 离开目录“/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4/src”
make[1]: *** [Makefile:613：all-recursive] 错误 1
make[1]: 离开目录“/home/jin/openvpn-build/generic/tmp/openvpn-2.5.4”
make: *** [Makefile:501：all] 错误 2

./configure OPENSSL_LIBS="-L/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k -lssl -lcrypto" OPENSSL_CFLAGS="-I/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/include/"

make -j 4

**Comment by cron2** [comment]
OPENSSL_LIBS does not look right - -L needs to include the directory that the libssl.so and libcrypto.so are in, so it would usually end in "/lib" - like `OPENSSL_LIBS="-L/home/jin/openvpn-build/generic/tmp/openssl-1.1.1k/lib -lssl -lcrypto"`

That said, why build 2.5.4?  current 2.5 release is 2.5.8

**Comment by sqbb1223** [comment]
unsubscribe




获麟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenVPN/openvpn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 晚上7:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [OpenVPN/openvpn] centos 7 openssl-1.1.1k openvpn-2.5.4 build fail (Issue #185)





 
Closed #185 as completed.
