### ISSUE TITLE
2.6_beta1 + p2p --secret + DCO does not work

### ISSUE THREAD

**Issue by cron2** [OpenVPN/openvpn#188]
**Describe the bug**
2.6_beta1 enables DCO mode for p2p --secret setups, and later crashes because all the TLS bits are not initialized

**To Reproduce**
Run 2.6_beta1 on a DCO-enabled linux system, with a p2p --secret config

**Expected behavior**
message in the log file "disabling data channel offload", and running without DCO

**Version information (please complete the following information):**
 - OS: Ubuntu 20.04
 - OpenVPN version: 2.6_beta1

**Comment by ordex** [comment]
patch is on the mailing list

**Comment by cron2** [comment]
Turns out the patch is not covering "no --secret no-cipher p2p tunnels"...

**Comment by cron2** [comment]
New patch has been merged

commit a666668f064c7ff57cdebb3afceb72e1263a3ba9
Author: Arne Schwabe <arne@rfc2549.org>
Date:   Sat Dec 10 14:44:27 2022 +0100

    Disable DCO when TLS mode is not used

forgot to link GH issue in commit request, though.
