### ISSUE TITLE
[2.6 beta1 w/ dco]Remove link-mtu warning.

### ISSUE THREAD

**Issue by Originalimoc** [OpenVPN/openvpn#191]
Identical `--cipher`/`--data-cipher AES-128-GCM`/`--auth SHA256`/`--data-cipher-fallback`/`compression no` setting among server and clients, no link-mtu config.

Client still log:
``WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1516', remote='link-mtu 1513'``

Lack of documentation on how it's computed, and no real effect, DEPRECATED anyway, just remove it.

**Comment by Originalimoc** [comment]
Looks like it's internally auto-generated [src/openvpn/options.c]. Remove this option as soon as possible as this still early beta is the solution?

**Comment by Originalimoc** [comment]
It's directly affecting 7 src files... Wonder what's the point of this at the beginning

**Comment by schwabe** [comment]
We need more information of your configuration. Normally if all is identical we should have not have these warnings.

**Comment by Originalimoc** [comment]
yes weird indeed, wait

**Comment by Originalimoc** [comment]
client:
```
daemon
dev tun11
persist-tun
proto udp
tun-mtu 1428
remote 127.0.0.1 1080
nobind
explicit-exit-notify 2
connect-retry 1 3
client
allow-compression no
data-ciphers AES-128-GCM
auth SHA512
auth-nocache
script-security 2
remote-cert-tls server
tls-crypt tlscrypt.key
ca ca.crt
cert MainHS.crt
key MainHS.key
reneg-sec 10000
hand-window 5
tran-window 86000
persist-key
ping 0
ping-restart 3600
replay-window 5000 3
mute 20
mlock
```

**Comment by Originalimoc** [comment]
server:
```
daemon
port 1080
proto udp
float
explicit-exit-notify 1
tun-mtu 1428
dev tun21
txqueuelen 1000
client-config-dir /etc/openvpn/ccd1
persist-tun
persist-key
data-ciphers AES-128-GCM
auth SHA512
auth-nocache
allow-compression no
tls-crypt tlscrypt.key
ca ca.crt
cert server.crt
key server.key
dh dh.pem
remote-cert-eku "TLS Web Client Authentication"
reneg-sec 10000
hand-window 5
tran-window 86000
server 10.12.11.0 255.255.255.0
block-ipv6
topology subnet
client-to-client
replay-window 5000 3
connect-retry 3 15
ping 0
ping-restart 3600
sndbuf 11796480
rcvbuf 11796480
mlock
push "sndbuf 11796480"
push "rcvbuf 11796480"
```

**Comment by Originalimoc** [comment]
where's that 3 bytes discrepancy coming from...

**Comment by schwabe** [comment]
Please don't use the bug tracker like a chat. There is no need to split your one message into four individual ones. Also please provide a `verb 4` log from both client and server as that will show the computation. This is probably triggered by persist-key or persist-tun but I would like to see complete logs from client and server to test my theory

**Comment by Originalimoc** [comment]
Probably, I'll test it later.

**Comment by schwabe** [comment]
This repository is only for reporting bug. If you want to discuss, there is http://forum.openvpn.net

**Comment by schwabe** [comment]
@Originalimoc I am still waiting for your log files.

**Comment by Originalimoc** [comment]
Next workday.

**Comment by cron2** [comment]
I'm reopening this, as we are still interested to find a good solution for the `link-mtu is used inconsistently` warnings.

With the new code, this is easily triggered by having identical `tun-mtu` on both sides, but different overhead calculation (due to config settings that get later replaced by pushed values from the server anyway, like `cipher`), and also due to 2.5 and earlier sending bogus values due to incorrect calculations.  We don't actually need the original poster's log file for this, I have tons of examples :-)

**Comment by cron2** [comment]
The warning was effectively removed from 2.6 by changing the log level so it only appears if you really want to see it (via commit bfd0ef36c46f8326e40).  2.5 to 2.6 will still log this on the 2.5 side.
