### ISSUE TITLE
[2.6 beta1] TLS client dco module crash(?) after 14-15 TLS renegotiation

### ISSUE THREAD

**Issue by Originalimoc** [OpenVPN/openvpn#193]
**Describe the bug**
```
2022-12-08 02:38:25 us=845277 VERIFY EKU OK
2022-12-08 02:38:25 us=845295 VERIFY OK: depth=0, CN=server
2022-12-08 02:38:25 us=921607 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bit RSA, signature: RSA-SHA256
2022-12-08 02:38:40 us=998290 TLS: soft reset sec=15/15 bytes=0/-1 pkts=0/0
2022-12-08 02:38:40 us=998991 Assertion failed at dco.c:175 (primary->dco_status != DCO_NOT_INSTALLED)
```

**To Reproduce**
A normal TLS setup was established, then after around 15+ **successful** TLS: soft reset this happens.

Config same as https://github.com/OpenVPN/openvpn/issues/192#issue-1484902981 except server dco disabled because TLS reneg doesn't work with it on

**Expected behavior**
Nothing happens

**Version information (please complete the following information):**
 - OS: Ubuntu 22.04
 - OpenVPN version: 2.6 beta1

**Comment by cron2** [comment]
For DCO-related issues, having a logfile with `verb 6` is needed, because that shows the communication with the kernel module.  It's likely that `reneg-sec 15` is just not going to work with DCO, but the log (include the two previous successful renegotiations and the failed one) should show why.

**Comment by Originalimoc** [comment]
Huh thanks too it's 1 AM and I have to deal with these weird implementations.

**Comment by Originalimoc** [comment]
such as hard coded `o->scheduled_exit_interval = 5;`
WHY???
recompile it with 1 next time.

**Comment by cron2** [comment]
Hi,

On Thu, Dec 08, 2022 at 09:03:31AM -0800, Originalimoc wrote:
> such as hard coded `o->scheduled_exit_interval = 5;`
> WHY???
> recompile it with 1 next time.

You're free to compile whatever you want, but don't yell at us if
it breaks a server with 1000s of clients from all over the world
(= high latencies, possible packet loss).

The default settings need to work for less-than-perfect scenarios.

gert


-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by Originalimoc** [comment]
> Hi,
> On Thu, Dec 08, 2022 at 09:03:31AM -0800, Originalimoc wrote: such as hard coded `o->scheduled_exit_interval = 5;` WHY??? recompile it with 1 next time.
> You're free to compile whatever you want, but don't yell at us if it breaks a server with 1000s of clients from all over the world (= high latencies, possible packet loss). The default settings need to work for less-than-perfect scenarios. gert
> […](#)

So you do care about stress testing? Then what's EXACTLY wrong with reneg ~10sec for testing when TLS handshake can complete RELIABILY in 1 sec.

**Comment by schwabe** [comment]
@Originalimoc if you want us to fix bug we expect you to invest some effort as well in giving us proper log files and so on. If you cannot do this or do not want to do this then you are just wasting your and our time.
