### ISSUE TITLE
I get two errors with any server configuration: "Linux ip addr del failed: external program exited with error status: 2" and "RTNETLINK answers: Operation not permitted"

### ISSUE THREAD

**Issue by mr-akkerman** [OpenVPN/openvpn#195]
**Hi! When installing any version of openvpn server in the log files, I get the following errors:** 

_«Linux ip addr del failed: external program exited with error status: 2»
«RTNETLINK answers: Operation not permitted»_

What does it mean?  How to fix it?

**To Reproduce**
Install a VPN on the server.
To run.
View logs

**OS: ubuntu 20.04 LTS
OpenVPN version: any**

I am grateful for any help

**Comment by mr-akkerman** [comment]
I have suspicions that the problems are related to the traffic routing issue. However, it occurs during a clean installation without my intervention

**Comment by schwabe** [comment]
This is an issue and not for seeking help on OpenVPN configuration issues. Please see http://forum.openvpn.net for that. You are probably not running the program with root rights.

**Comment by mr-akkerman** [comment]
OK, thanks for that
