### ISSUE TITLE
FreeBSD: OpenVPN PID logged in syslog is off-by-one from actual OpenVPN PID

### ISSUE THREAD

**Issue by cron2** [OpenVPN/openvpn#198]
**Describe the bug**
Running OpenVPN on FreeBSD with `--daemon` (which implies `--syslog`) shows off-by-one PID in syslog

**To Reproduce**
Run OpenVPN on FreeBSD with `--daemon`, compare PID in syslog and `ps`

```
Dec 14 11:58:20 fbsd14 tun-udp-p2p-tls-sha256[46924]: dco_update_keys: peer_id=-1

# ps axwwwwwu |grep tls-sha256
root    46925   0.0  0.2 18208  8148  -  Ss   11:39       0:00.26 ./bin/openvpn --daemon tun-udp-p2p-tls-sha256 --cd tun-udp-p2p-tls-sha256 --config server.conf --writepid ../openvpn-tun-udp-p2p-tls-sha256.pid
```

**Expected behavior**
actuall process PID visible in syslog

**Version information (please complete the following information):**
 - OS: FreeBSD 14
 - OpenVPN version: 2.6_beta1

**Additional context**
I assume this is caused by doing `openlog()` before `daemon()` or something like that... does not happen on Linux.

**Comment by kprovost** [comment]
I'm pretty sure this is a FreeBSD bug, not an OpenVPN bug.

I believe it was introduced here: https://lists.freebsd.org/archives/dev-commits-src-main/2022-August/008489.html 
I've pinged the author of that commit about it.

**Comment by gonzopancho** [comment]
Given that this isn't an OpenVPN bug, it likely should not hold up a 2.6 release.

**Comment by cron2** [comment]
> Given that this isn't an OpenVPN bug, it likely should not hold up a 2.6 release.

It won't.  It's something I found in the pre-2.6 tests, and it's here so it's not forgotten, but it's not a showstopper.

@kprovost interesting find, and I agree that this looks very likely

```
-	(void)fprintf(fp, "%d ", getpid());
+	if (LogPid == -1)
+		LogPid = getpid();
+	(void)fprintf(fp, "%d ", (int)LogPid);
```

before the patch, it would always log the "now-current" PID, so the sequence of ``syslog(), fork(), syslog()`` would see the child PID in the second syslog (if called in the child, of course).  With the change, after the first syslog(), it would always stick the original PID.  And there we are again, with OpenVPN calling ``daemon(3)``, which forks...

The trivial solution would be to change the libc code to

```
    (void)fprintf(fp, "%d ", LogPid != -1? (int)LogPid: getpid());
```

so if someone wants to set a ``[pid]`` in ``openlog()`` they can, and if not, it would always use the current pid...

**Comment by kprovost** [comment]
The original author just committed a fairly similar fix in https://lists.freebsd.org/archives/dev-commits-src-main/2023-January/011767.html

**Comment by cron2** [comment]
Confirmed fixed.  Did a new world build today, tested openvpn with ``--daemon``, and indeed

```
Jan  4 23:01:05 fbsd14 tun-udp-p2mp[1151]:   auth_token_secret_file = '[UNDEF]'
Jan  4 23:01:05 fbsd14 tun-udp-p2mp[1151]:   client = DISABLED
Jan  4 23:01:05 fbsd14 tun-udp-p2mp[1152]: Diffie-Hellman initialized with 2048 bit key
Jan  4 23:01:05 fbsd14 tun-udp-p2mp[1152]: TLS-Auth MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1250 tun_max_mtu:0 headroom:126 payload:1600 tailroom:126 ET:0 ]
```

... when daemonizing, the syslogged PID changes, and 1152 is correct

```
[root@fbsd14 ~/t_server]# ps axwu |grep 1152
root    1152   0.0  0.2 18352 7800  -  Ss   23:01     0:00.02 ./bin/openvpn --daemon tun-udp-p2mp --cd tun-udp-p2mp --config server
```

Thanks for relaying the issue :-)
