### ISSUE TITLE
Uninterruptible loops and lost signals 

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn#205]
_Based on Trac issues 311 and 639 recreated here for better visibility and ease of follow up_

**Describe the bug**
SIGTERM/SIGINT are lost in some cases leading to non-interruptible (or hard to interrupt) loops

**To Reproduce**
On Windows and Linux: use a bogus dns server and run the client preferably with with an unresolvable remote like
`openvpn --client --remote foo.bar <other options>`
When the process stalls in `getaddrinfo()` press `ctrl-C`. Instead of exiting, the connection will repeatedly restart after a couple of rounds of timeout in `getaddrinfo()`. In this case `ctrl-C` pressed during address resolution is lost on Linux. 

Pressing `ctrl-C` when the process is in sleep() (restart delay) does terminate the process on Linux. But, on Windows ctrl-C is always lost unless  `--management option` is also used.

Windows only: Just use an unresolvable remote with working dns server (but no `--management` option) and the process goes into a SIGUSR1 restart loop that is not interruptible even during the restart delay.

**Expected behaviour**

On pressing ctrl-C or sending SIGTERM or SIGINT, the process should terminate once address resolution times out. Although `getaddrinfo()` is not interruptible, the signal does get delivered during it and it should not be lost. On Windows, restart loops must be interruptible even if `---management` option is not used.

**Version information (please complete the following information):**
 - OpenVPN version: 2.6_beta2

**Additional context**
As discussed under https://community.openvpn.net/openvpn/ticket/639, this appears to be caused by lower priority signals (SIGUSR1, for example) overwriting pending SIGTERM before it gets processed.

Propose to fix by 

 (i) set all signals through functions (no direct re-write of volatile variables)
 (ii) prioritize signals in order of importance 
 (iii) On windows, signal is not picked up in openvpn_sleep() unless management is active. Fix this
 (iv) use sigaction instead of old signal API

https://github.com/selvanair/openvpn/tree/signals

(iv) is may be too intrusive for 2.6 at this stage, but (i) to (iii) are simple and will fix the above buggy behaviour in practice, even if not fool-proof.

**Comment by selvanair** [comment]
Needs 3/5 (prioritize signals) before this can be closed.  Without that ctrl-C during DNS resolution is still lost both on Windows and Linux. May be reproduced using a bogus DNS server to make getaddrinfo stall -- press ctrl-C during that period, wait for getaddrinfo to time out (twice) and see SIGUSR1 restart instead of SIGTERM exit.

Its possible to get out of this (repeatedly press ctrl-C) but very hard.

**Comment by cron2** [comment]
Have updated and closed the trac tickets.
