### ISSUE TITLE
client-connect script blocks openvpn server

### ISSUE THREAD

**Issue by SurajDadral** [OpenVPN/openvpn#209]
I had an issue with client-connect script execution. We do some operations in client-connect script which takes 20-30 seconds. During the execution of this script all traffic on the openvpn server is blocked, or not processed.
If I telnet into management port and run `status` command there, then output of that command is returned after client-connect script done processing. During execution of this script, no other user is able to connect to openvpn-server.

**To Reproduce**
- Create client-connect script (php) and put `sleep(30);` in it.
- connect one user.
- within 30 seconds (during execution of client-connect script), try to connect another user whose connection will not be processed until client-connect script for previous user is not done processing.

**Expected behavior**
I should be able to connect other users when client-connect for previous user is executing.

**Version information (please complete the following information):**
 - OS: Debian 9
 - OpenVPN version: 2.5.8-stretch0 (also tested with 2.5.0-stretch0, 2.5.7-stretch0, 2.4.7-stretch0 same behavior)

**Additional context**
As per this: https://community.openvpn.net/openvpn/ticket/1244
Same issue was fixed, but unable to get it working as expected.

Thanks,

**Comment by SurajDadral** [comment]
Apology to bother.
Got to know how to make it work:
https://forums.openvpn.net/viewtopic.php?t=33068
https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/script-options.rst#environmental-variables

Thanks,

**Comment by cron2** [comment]
Hi,

On Thu, Dec 29, 2022 at 08:49:31PM -0800, Suraj wrote:
> I had an issue with client-connect script execution. We do some operations in client-connect script which takes 20-30 seconds. During the execution of this script all traffic on the openvpn server is blocked, or not processed.
> If I telnet into management port and run `status` command there, then output of that command is returned after client-connect script done processing. During execution of this script, no other user is able to connect to openvpn-server.

Yes, this is well-known.  OpenVPN is single-threaded, so when a plugin
or script takes time to finish, everything else waits.

This said, if you use OpenVPN 2.5 or later (which you do, according
to "OpenVPN version") scripts ran run asynchronously - that is, the
client-connect script needs to fork, the foreground process needs
to write "2" to $client_connect_deferred_file and then exit(0) - 
and the background process can then do the actual work and write
the final response code to this file (1 = success, 0 = reject user).

> **Additional context**
> As per this: https://community.openvpn.net/openvpn/ticket/1244
> Same issue was fixed, but unable to get it working as expected.

Your script needs to do a bit more work.  Look for "deferred" in
"man openvpn", in the --client-connect section and especially in
the "Environmental Variables" section.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
