### ISSUE TITLE
OpenVPN: allow storing authentication user name in configuration

### ISSUE THREAD

**Issue by moritori** [OpenVPN/openvpn#210]
**Describe the bug**
It would be nice, if it was possible to require certificate authentication and use a static challenge without username and password to make it possible to implement e.g. TOTP with a auth-user-pass-verify script. Static challenges are only activated if auth-user-pass is configured as well, this strictly requires a username and a password. We can configure static credentials with e.g. "auth-user-pass credentials.txt" and just add some static values in two lines in that file but it is not possible to store them inside the ovpn file as inline configuration parameter. This was actually promised for openvpn 2.4.x in the old bug ticket https://community.openvpn.net/openvpn/ticket/628 but unfortunately never implemented.

**To Reproduce**
add the following to your configuration:

`<auth-user-pass>`
`username`
`password`
`</auth-user-pass>`

**Expected behavior**
(1) I was hoping that OpenVPN would takeover the username for the username field and the string password for the password, however it only returns an error saying that this is not an inline parameter. It would also absolutely fine, if the contents of the inline parameter had to be base64 encoded.

(2) Additionally it would be great, if static-challenge would use an empty username and an empty password if auth-user-pass is not configured while static-challenge is.

**Version information (please complete the following information):**
 - OS: Linux
 - OpenVPN version: 2.5.6 (community edition)

**Comment by cron2** [comment]
Hi,

On Fri, Dec 30, 2022 at 08:05:16AM -0800, moritori wrote:
> add the following to your configuration:
> `
> <auth-user-pass>
> username
> password
> </auth-user-pass>
> `

This is supported in the upcoming OpenVPN 2.6.0 (to be released in the
next 4 weeks), but will not be backported to 2.5.x

commit 7d48d31b8226d5e3a5638e2369876381038bf5e2
Author: Antonio Quartulli ***@***.***>
Date:   Sat Sep 17 15:48:32 2022 +0200

    auth-user-pass: add support for inline credentials


gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by moritori** [comment]
That is fantastic news. Thank you! What about (2)?

**Comment by cron2** [comment]
Hi,

On Fri, Dec 30, 2022 at 08:05:16AM -0800, moritori wrote:
> (2) Additionally it would be great, if static-challenge would use an empty username and an empty password if auth-user-pass is not configured while static-challenge is.

Sorry I overlooked this question.  Not sure about this one, I am not
using static-challenge myself (for the corp VPN where we use 2FA, we
put our 2FA numbers into the password).

@selvanair might have insights.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by moritori** [comment]
No worries and thanks for your effort.

That would also work for our case, however we don't want to have the need to enter the username but have it derived from the certificate as is the default behavior.

**Comment by selvanair** [comment]
Static challenge is intimately coupled with auth-user-pass and cannot be used without it. Also embedding username/password in file with static-challenge enabled will work only for users who run from command line (and possibly via systemd). When using a UI that talks to the management interface (like Windows OpenVPN-GUI), the challenge will not get queried if user/pass are embedded or read from a file.

For your use case, it may be better to send a CR_TEXT challenge form the server using `client-pending-auth` via management interface. For details see: https://github.com/OpenVPN/openvpn/blob/master/doc/management-notes.txt It will require some re-thinking of how server-side verification is implemented.

**Comment by schwabe** [comment]
Yes. As @selvanair explains it is very unlikely that we improve the old 2FA methods since we now have the much more flexible pending auth/crtext method.

**Comment by schwabe** [comment]
Closing the issue since the features are already implemented.

**Comment by moritori** [comment]
@selvanair: thanks your detailed explanation. I got it working now with "client-pending-auth" and a cr_text challenge and can confirm that it is working as expected without username and password.
