### ISSUE TITLE
Link IPv4 and IPv6 into a single instance on the server (connection server <-> client)

### ISSUE THREAD

**Issue by willyamcts** [OpenVPN/openvpn#222]
Doing some research I noticed that the documentation says that IPv4 and IPv6 are supported simultaneously but it doesn't make it clear where. According to the manual and some tests i noted regardless of the `proto` used in the tunnel it is possible to travel IPv4 and IPv6 normally, what changes is the connection protocol (transport) between server and client: udp/udp4/udp6.

My intention is to allow clients to connect (transport) over both IPv4 and IPv6 using a single server instance. So far it seems to me that IPv4 and IPv6 connection/transport is not possible with a single instance, 1 instance is needed for IPv4 and another for IPv6.

if anyone knows, thanks

**Comment by cron2** [comment]
Hi,

On Thu, Jan 19, 2023 at 08:18:35AM -0800, Willyam Castro wrote:
> Doing some research I noticed that the documentation says that IPv4 and IPv6 are supported simultaneously but it doesn't make it clear where. According to the manual and some tests i noted regardless of the `proto` used in the tunnel it is possible to travel IPv4 and IPv6 normally, what changes is the connection protocol (transport) between server and client: udp/udp4/udp6.
> 
> My intention is to allow clients to connect (transport) over both IPv4 and IPv6 using a single server instance. So far it seems to me that IPv4 and IPv6 connection/transport is not possible with a single instance, 1 instance is needed for IPv4 and another for IPv6.
> 
> if anyone knows, thanks

It depends a bit on the server operating system in use.  On OpenBSD and
DragonFly, only one address family can be used per instance.

On Linux, FreeBSD, ... a server listening to a "dual-stacked IPv6 socket"
will also accept incoming connections just fine.

Linux needs "proto udp6" to actually get there.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by willyamcts** [comment]
But `proto udp6` not limit connection in IPv6 ? 

With dual-socket can I have the same IPv4 and IPv6 instance? How do I create a dual-stack socket?

OS: Debian
OpenVPN version: 2.4

**Comment by cron2** [comment]
Hi,

On Thu, Jan 19, 2023 at 09:00:05AM -0800, Willyam Castro wrote:
> But `proto udp6` not limit connection in IPv6 ? 

No.

> With dual-socket can I have the same IPv4 and IPv6 instance?

Yes.

>  How do I create a dual-stack socket?

OpenVPN will do that for you when you use `proto udp6` on the server.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by cron2** [comment]
Hi,

On Thu, Jan 19, 2023 at 09:17:03AM -0800, Willyam Castro wrote:
> Right, using `proto udp6` by example without directive `local` the server listen up in " :: " only. 

This includes IPv6, but Linux netstat is refusing to tell

On FreeBSD, you can see "46" in the first column:

```
FreeBSD$ netstat -an |grep 51194
tcp46      0      0 *.51194                *.*                    LISTEN     
udp46      0      0 *.51194                *.*                    
```

but Linux is not showing it

```
Linux$  ss -an |grep 51194
udp     UNCONN   0        0                                                   *:51194                                                 *:*                       
tcp     LISTEN   0        32                                                  *:51194                                                 *:*                    
```

... and all these services handle connections both on v4 and v6.


> The use of `local` is valid only once and as defined by `udp6`
> an IPv4 in `local` is not accepted, so far so good, it's expected.
> IPv4 and IPv6 traffic between the ends works, but I want an instance
> on the server that allows the client to connect to my IPv4 or my
> IPv6 explicitly in directive `remote ...`

If you want the server side to explicitly bind to a *specific* IPv4 or
IPv6 address, then you need to run two instances today.

Normally this is only needed if you have multiple IPv4 addresses, and
want OpenVPN on only one of them - but this is a known shortcoming
(you can not have "I have 3 IPv4 addresses and want OpenVPN only to
listen on 2 of them" either) - as soon as you put ``local`` in the config,
it's "one address, one protocol" only.


Now I'm not sure what you really want - the instance without local
will listen to both IPv4 and IPv6, and on the client side, you can
put whatever you want in the "remote" line, v4 and v6?  What is in the
client config does not need to match the "local" part of the server
config (unless you use old-style ``--secret`` without ``--float``).

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by willyamcts** [comment]
> If you want the server side to explicitly bind to a *specific* IPv4 or
IPv6 address, then you need to run two instances today.

> Normally this is only needed if you have multiple IPv4 addresses, and
want OpenVPN on only one of them - but this is a known shortcoming
(you can not have "I have 3 IPv4 addresses and want OpenVPN only to
listen on 2 of them" either) - as soon as you put ``local`` in the config,
it's "one address, one protocol" only.

Understood


>  [ .... ] What is in the client config does not need to match the "local" part of the server
config (unless you use old-style ``--secret`` without ``--float``).

In client is using `float` conf


>
> On FreeBSD, you can see "46" in the first column:
> ```
> FreeBSD$ netstat -an |grep 51194
> tcp46      0      0 *.51194                *.*                    LISTEN
> udp46      0      0 *.51194                *.*
> ```
> but Linux is not showing it
>```
>Linux$  ss -an |grep 51194
>udp     UNCONN   0        0                                                   *:51194                                                 *:*
>tcp     LISTEN   0        32                                                  *:51194                                                 *:*
>```

In my case, using `proto udp6` in server without `local`, with IPv4 and IPv6 settings, i have output `ss -an | grep 1194`:
```
udp   UNCONN    0      0                                    *:1194                         *:*
```
In `netstat -anp | grep 1194`
```
udp6       0      0       :::1194                 :::*                                11210/openvpn
```

In client:
```
proto udp
remote IPv4
remote IPv6
```

Really in `netstat` and `ss` appears to listen only on IPv6.
Now, with the confs above my client connect in both the protocols, very good. It was what I needed.

How is this possible? is it the socket management that allows this?

Very thanks by explanation @cron2
