### ISSUE TITLE
Authentication plugins coexistance

### ISSUE THREAD

**Issue by mxmauro** [OpenVPN/openvpn#225]
Scenario:

A server with two authentication plugins is stated, one of them makes a check against with a file and the other against a database. 

The former can fulfill synchronously, the second, deferred. Assuming they are loaded in order based on the position within the configuration file.

The `plugin_call_ssl` function's main loop calls the first plugin, returns `OPENVPN_PLUGIN_FUNC_ERROR` because the given user/pass is not listed in the file. Then calls the second and returns `OPENVPN_PLUGIN_FUNC_DEFERRED` to do async check on the database.

Because `error` was set to `true`, the authentication fails always no matter if the user is valid on the database.

Also, if the user/pass exists in the file of the first plugin, the function will return `OPENVPN_PLUGIN_FUNC_DEFERRED` because `deferred_auth_done` was set to `true` in the loop.

Probably, in order to fix this, compatibility with previous version must be broken.

Kind regards,
Mauro.

**Comment by cron2** [comment]
Hi,

On Thu, Jan 26, 2023 at 09:43:46AM -0800, Mauro Leggieri wrote:
> A server with two authentication plugins is stated, one of them makes a check against with a file and the other against a database. 
> 
> The former can fulfill synchronously, the second, deferred. Assuming they are loaded in order based on the position within the configuration file.
> 
> The `plugin_call_ssl` function's main loop calls the first plugin, returns `OPENVPN_PLUGIN_FUNC_ERROR` because the given user/pass is not listed in the file. Then calls the second and returns `OPENVPN_PLUGIN_FUNC_DEFERRED` to do async check on the database.

If you have two (or more) plugins loaded, all need to return SUCCESS.

There is no concept of "it is sufficient if one of them succeeds" in OpenVPN
today.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by mxmauro** [comment]
Hi @cron2 thanks for the quick response.

> There is no concept of "it is sufficient if one of them succeeds" in OpenVPN today.

It is a pity and it is not a real scenario. Cannot return success if authentication fails.

Let's take an example with the provided `auth-pam` used synchronously, it returns error if the validation fails, which makes sense.

**Comment by selvanair** [comment]
You may be able to work around this using a single auth-pam plugin in deferred mode and have two PAM modules one for checking file and other database. The PAM modules can be stacked to return success for any combination of interest. Looks like it should work, though untested.

**Comment by mxmauro** [comment]
Hi @selvanair but the code's [loop and behavior](https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/plugin.c#L813) does not help.

Assume user A is on the file and user B is on database. You should return error if authentication fails so, if you authenticate user A, one of the plugins may succeed but the other will error, causing error to be returned despite A credentials are fine.

Check other combinations like changing the load order of plugins and you will have a problem at some point.

**Comment by mxmauro** [comment]
Yes. I was doing a custom plugin when found this issue. I'll investigate more about PAM. Thanks!!

**Comment by selvanair** [comment]
As an example of using multiple PAM modules, here is a simple setup where PAM first tries an LDAP database and then falls back to passwd file 

```
$ cat /etc/pam.d/openvpn
auth sufficient pam-ldap.so /etc/ldap/pam_ldap.conf
auth required pam_unix.so try_first_pass
```
One could reverse the order, or use more complex logic using options like `[success=n]`

In the server config there is only one plugin:
`plugin /path/to/openvpn-lugin-auth-pam.so openvpn`

**Comment by mxmauro** [comment]
Perfect, I'll do a research on that.

Thank you.
