### ISSUE TITLE
OpenVPN-2.6.0-I001-amd64(win10-22H2) Right click exception

### ISSUE THREAD

**Issue by kksay2010** [OpenVPN/openvpn#226]
OS: win10-22H2
OpenVPN version: OpenVPN-2.6.0-I001-amd64
Problem description：
      Small icon after startup, Right click exception,Please refer to the picture（although I use Chinese, it doesn't affect your test）
![image](https://user-images.githubusercontent.com/29589474/215032624-398c6599-f7a4-4545-9ab4-1b263e136bd0.png)

**Comment by lstipakov** [comment]
Not sure what issue you have, but please use the latest version (I003).

**Comment by kksay2010** [comment]
> Not sure what issue you have, but please use the latest version (I003).

1003 is OK ,thanks
