### ISSUE TITLE
OpenVPN 2.6.0 --inactive does not work with ovpn-dco-win

### ISSUE THREAD

**Issue by luyebo-cn** [OpenVPN/openvpn#228]
Installer：OpenVPN-2.6.0-I003-amd64.msi
OS: Windows 10 22H2 [10.0.19045.2546]

According to the reference manual: 
_--inactive args Causes OpenVPN to exit after n seconds of inactivity on the TUN/TAP device. 
Valid syntaxes:
inactive n
inactive n bytes_

The server push configuration is as follows: **inactive 600 10000**

The client will automatically disconnect when the time comes, no matter how much data is transferred.
The 2.4.x/2.5.x version is able to handle it correctly.

Key Log Information:

2023-01-29 20:57:38 OpenVPN 2.6.0 [git:v2.6.0/b999466418dddb89] Windows-MSVC [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] [DCO] built on Jan 25 2023
2023-01-29 20:57:38 Windows version 10.0 (Windows 10 or greater), amd64 executable
2023-01-29 20:57:38 library versions: OpenSSL 3.0.7 1 Nov 2022, LZO 2.10
2023-01-29 20:57:41 PUSH: Received control message: 'PUSH_REPLY,explicit-exit-notify,topology subnet,route-delay 5 30,dhcp-pre-release,dhcp-renew,dhcp-release,route-metric 101,ping 12,ping-restart 50,**inactive 600 10000**,redirect-private def1,...
2023-01-29 20:57:46 Initialization Sequence Completed
2023-01-29 20:57:46 MANAGEMENT: >STATE:1674997066,CONNECTED,SUCCESS
2023-01-29 21:07:41 **Inactivity timeout (--inactive)**, exiting
2023-01-29 21:07:41 SIGTERM received, sending exit notification to peer

Bytes in: 326926 (319.3 KiB) out: 160551(156.8 KiB) OpenVPN GUI 11.37.0.0/2.6.0

**Comment by schwabe** [comment]
Is the client using the DCO driver/

**Comment by luyebo-cn** [comment]
Yes，DCO driver 0.8.3.0. Default options are used in the configuration file：
_dev tun
dev-type tun_

I will add --disable-dco and try again.

**Comment by luyebo-cn** [comment]
OpenVPN 2.6.1 with ovpn-dco-win-0.9.2-amd64, the bug still exists.

**Comment by luyebo-cn** [comment]
OpenVPN 2.6.1 with ovpn-dco-win-0.9.2-amd64, the bug still exists.

**Comment by lstipakov** [comment]
Looks like I haven't sent the patch to the mailing list, will do next week.

**Comment by lstipakov** [comment]
Patch sent to mailing list: https://patchwork.openvpn.net/project/openvpn2/patch/20230313100601.2146-1-lstipakov@gmail.com/

**Comment by lstipakov** [comment]
@luyebo-cn can you confirm that 2.6.2 fixes the issue?

**Comment by luyebo-cn** [comment]
> @luyebo-cn can you confirm that 2.6.2 fixes the issue?

Sorry for the late reply.
I tested and this issue was fixed in 2.6.2, but there is a related new issue:
Follow the manual: https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/
_In any case, OpenVPN's internal ping packets (which are just keepalives) and TLS control packets are not considered "activity", nor are they counted as traffic, as they are used internally by OpenVPN and are not an indication of actual user activity._

But，Now，OpenVPN's internal ping packets and/or TLS control packets are considered "activity traffic".

**Comment by lstipakov** [comment]
Hi, 

> But，Now，OpenVPN's internal ping packets and/or TLS control packets are considered "activity traffic".

I can't reproduce this - for me `inactive` excludes internal ping packets - just tested with `keepalive 3 180` and `inactive 5`.

I see internal ping packets every 3 seconds, and soon got `Inactivity timeout (--inactive), exiting`. 

Can you double-check with, for example, Wireshark, that there is no user activity traffic?

**Comment by luyebo-cn** [comment]
Sorry, I know why, it's my misunderstanding. It's because my Edge browser keeps sending Simple Service Discovery Protocol  request packets, and traffic is sent to the OpenVPN network, resulting in increased traffic.

Thanks.
