### ISSUE TITLE
Access violation in interactive service

### ISSUE THREAD

**Issue by lstipakov** [OpenVPN/openvpn#232]
When iservice is unable to apply "block-outside-dns", access violation happens during undo phase.

![Sieppaa](https://user-images.githubusercontent.com/643110/215828264-0736d54f-2ef0-4dda-9f8f-f185a28b6d20.JPG)

Steps to reproduce:

 - Install [SonicWall Global VPN Client](https://www.sonicwall.com/products/remote-access/vpn-clients/)
 - Install OpenVPN 2.6.0
 - Try to connect with profile which uses DCO and has "block-outside-dns"

There is a [compatibility issue](https://github.com/OpenVPN/ovpn-dco-win/issues/31) with dco driver and Sonicwall driver, but interactive service should not crash regardless of it. The access violation seem to happen inside WFP, but that does not excuse us :)

**Comment by lstipakov** [comment]
ping @selvanair

**Comment by selvanair** [comment]
Does the value of engine handle at this point the same as the one we got from the open call? We do check for error while opening so it has to be a valid handle. If this shows up only when sonicwall/dco compat issue is present, it could be related, no? Like a broken interface that triggers a crash inside WFP when referred to by block-dns?

Will try installing SonicWall client later.
