### ISSUE TITLE
Are 'user nobody' and 'group nogroup' deprecated on Windows as of 2.6?

### ISSUE THREAD

**Issue by rpodric** [OpenVPN/openvpn#233]
**Describe the bug**
I notice these two lines when connecting with OpenVPN-2.6.0-I003-amd64:

> Tue Jan 31 21:34:19 2023 NOTE: --user option is not implemented on Windows
> Tue Jan 31 21:34:19 2023 NOTE: --group option is not implemented on Windows
> 

**To Reproduce**
1. In your normal ovpn, also have these two lines if you don't already:
     user nobody
     group nogroup
2. Connect
3. View log

**Expected behavior**
I expected to connect, and do, and still do without the above lines, but I'm just wondering if it's correct that these are no longer in the Windows client, and if so, what that means. Maybe it's unimportant, but I thought it was for a security reason.

**Version information (please complete the following information):**
 - OS: Windows 11
 - OpenVPN version: 2.6.0

**Additional context**
All but sure this is new as of 2.6.0, but even if it's not, the question stands.

**Comment by cron2** [comment]
Hi,

On Tue, Jan 31, 2023 at 09:47:21PM -0800, rpodric wrote:
> > Tue Jan 31 21:34:19 2023 NOTE: --user option is not implemented on Windows
> > Tue Jan 31 21:34:19 2023 NOTE: --group option is not implemented on Windows
[..]
> **Additional context**
> All but sure this is new as of 2.6.0, but even if it's not, the question stands.

--user/--group has never been supported on Windows.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by flichtenheld** [comment]
These log messages are at least as old as the git repository. Nothing has changed here.

**Comment by rpodric** [comment]
OK, I missed it in 2.5, sorry, but do you happen to know when they were deprecated then? Was it perhaps _never_ supported in Windows? Are the lines actually not important?

I looked in the latest documentation and didn't see any mention of the deprecation:
https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6

But it does say this:

> By setting user to an unprivileged user dedicated to run openvpn, the hostile party would be limited in what damage they could cause. Of course once you take away privileges, you cannot return them to an OpenVPN session. This means, for example, that if you want to reset an OpenVPN daemon with a SIGUSR1 signal (for example in response to a DHCP reset), you should make use of one or more of the --persist options to ensure that OpenVPN doesn't need to execute any privileged operations in order to restart (such as re-reading key files or running ifconfig on the TUN device).
> 
> NOTE: Previous versions of openvpn used nobody as the example unpriviledged user. It is not recommended to actually use that user since it is usually used by other system services already. Always create a dedicated user for openvpn.

**Comment by cron2** [comment]
Hi,

On Wed, Feb 01, 2023 at 07:54:19AM -0800, rpodric wrote:
> OK, I missed it in 2.5, sorry, but do you happen to know when they were deprecated then? Was it perhaps _never_ supported in Windows? Are the lines actually not important?

It was never supported in Windows, so, not deprecated, just "never there".

> But it does say this:
> 
> > By setting user to an unprivileged user dedicated to run openvpn, the hostile party would be limited in what damage they could cause. Of course once you take away privileges, you cannot return them to an OpenVPN session. This means, for example, that if you want to reset an OpenVPN daemon with a SIGUSR1 signal (for example in response to a DHCP reset), you should make use of one or more of the --persist options to ensure that OpenVPN doesn't need to execute any privileged operations in order to restart (such as re-reading key files or running ifconfig on the TUN device).

The documentation is not really good here, as this is assuming a Linux/Unix
background.

On Windows, OpenVPN runs with the privileges of the user, and uses a 
system service ("interactive service") for all privileged access, like
configuring interfaces and routes.  So the situation is different from
Linux/Unix, where it needs to start up as root, and then changes to
"--user nobody".

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
