### ISSUE TITLE
Access Server - Ubuntu 22.04 - Group owned subnet doesn't work

### ISSUE THREAD

**Issue by Bv-Lucas** [OpenVPN/openvpn#244]
**Describe the bug**
When configuring group owned subnets from the web admin interface, I am facing errors that state I have overlapping, which is not the case. The subnet declared as overlapping is the first /22 of the /20 subnet dedicated to groups (default one : 172.27.240.0/20), it is always declared in the error message as being associated with the last group from the group list, which is false as there is no subnet configured for this group, and deleting the group in question results in the same error with the new last group from the list 
The error is : 
ERROR: openvpn_iptables_configure: client-side subnet collision between 172.27.240.0/255.255.248.0 'Group-owned subnets for <group_name>' and [172.27.240.0/255.255.255.0 VALUE='Group-owned subnets for <group_name>'] (GREATER_THAN)

ERROR: service failed to validate

**To Reproduce**
Create an empty access server
Configure group subnets (my initial config was 172.27.240.0/24 for one group, then 172.27.241.0/24, 172.27.242.0/24 .. and so on) 
It does the same when configuring all groups then "Update running server" and when updating after each group configuration
The "group permission" page will not show the error message but will show a small red square above the green one saying "configuration applied and service restarted"
To get the error message above, simply change a user group membership, and you will get an error stating that you have a /22 associated with the last group from the list.

**Expected behavior**
Group subnets are correctly applied

**Version information (please complete the following information):**
 - OS: Ubuntu 22.04
 - OpenVPN version: 2.11.3-af31575c-Ubuntu22
 - Repeat for peer if relevant

**Additional context**
I managed to get around this by watching the iptable configuration and associating other subnets, it is not ideal but I can manage to make it work. I also suspect I may be able to get around this by configuring iptables myself, but I would like that openVPN does it correctly in the first place

**Comment by novaflash** [comment]
Hello Bv-Lucas,

While we appreciate you bringing problems to our attention, this one is unfortunately in the wrong place. Kindly please go to https://openvpn.net/support and submit your problem there.

To explain this a bit more - OpenVPN Inc. is a company that creates products based on the OpenVPN open source project, such as OpenVPN Access Server. Here on github you are in contact with the open source community. Here we cannot fix problems that exist on OpenVPN Access Server. But you can reach OpenVPN Inc. personnel and the OpenVPN Access Server support people if you submit a ticket at https://openvpn.net/support

Good luck.

**Comment by Bv-Lucas** [comment]
Hello 
Oh sorry my bad I didn't realize, thanks for your reply
Best
Lucas
