### ISSUE TITLE
OpenVPN 2.6.0.008 installed prevents Dell Latitude 5410 laptops from booting into Windows 10

### ISSUE THREAD

**Issue by srcentre** [OpenVPN/openvpn#248]
We recently deployed OpenVPN 2.6.0-I003 amd64 to our Patch Manager system, and after installation and restart, our Dell Latitude 5410 laptops could not boot into Windows - other models such as Latitude 5420 and 5430 were unaffected, as were Latitude 5410 with Windows 11 installed. Appears to affect Windows 10 x64 20H2 and 21H2 - can't confirm whether issue also present on 22H2 as of yet.

The fix was to boot into safe mode with network, enable Windows installer and uninstall OpenVPN 2.6.0 and restart - and the laptops would boot again.

We have now rolled back to 2.5.8

**Comment by srcentre** [comment]
Sorry forgot to check closed issues - same as https://github.com/OpenVPN/openvpn/issues/241

**Comment by selvanair** [comment]
Fixed in OpenVPN 2.6.0-I004. 
Also see #241

**Comment by lstipakov** [comment]
@srcentre can you confirm that I004 fixes the issue for you?

**Comment by kava1189** [comment]
I had the same problem with a Dell Latitude 9330, and the I004 Version fixed the issue.

**Comment by ordex** [comment]
Closing as this issue was fixed in OpenVPN 2.6.0-I004.
For more details please see openvpn#241 and [ovpn-dco-win#24](https://github.com/OpenVPN/ovpn-dco-win/issues/24)
