### ISSUE TITLE
Izzue

### ISSUE THREAD

**Issue by vicluk** [OpenVPN/openvpn#252]
#**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - OpenVPN version: [e.g. 2.5.8]
 - Repeat for peer if relevant

**Additional context**

**Comment by cron2** [comment]
Please do not randomly click around in GH issues.  You are taking away real time from real humans having to read this, ask themselves "so where's the bug?", and close it.
