### ISSUE TITLE
OpenVPN for Windows 2.6.0 cannot connect to Mikrotik server

### ISSUE THREAD

**Issue by ovedeneev** [OpenVPN/openvpn#253]
Windows client 2.6 version stopped connecting to Mikrotik devices exclusively. It works fine with servers installed on Linux.

Reverting back to 2.5.9 fixed the issue.

 - OS: Windows 10
 - OpenVPN version: 2.6.0
 - Mikrotik RouterOS 6.49.7

Turning off DCO in config file does not help. Connection log is attached. 
[openvpn_2_6_issue.txt](https://github.com/OpenVPN/openvpn/files/10762094/openvpn_2_6_issue.txt)

**Comment by selvanair** [comment]
If you have access to the server log on mikrotik take look -- I think the server rejected the connection and closed it.

**Comment by lstipakov** [comment]
Does Microtik server run Azure VPN Gateway? :)Quite similar symptoms - TCP handshake failed. We have started talks with MSFT but no results yet. Lähetetty iPhonestaSelva Nair ***@***.***> kirjoitti 17.2.2023 kello 3.36:﻿
If you have access to the server log on mikrotik take look -- I think the server rejected the connection and closed it.

**Comment by ovedeneev** [comment]
> If you have access to the server log on mikrotik take look -- I think the server rejected the connection and closed it.

There's only one message in the logs:
`duplicate packet, dropping`

I checked with Wireshark - Windows host sends TCP RST. It could be Mikrotik provoking on this action but I cannot fetch more detailed debug log from it.


> Does Microtik server run Azure VPN Gateway?

No, this is hardware appliance.

**Comment by cron2** [comment]
Hi,

On Thu, Feb 16, 2023 at 04:35:10PM -0800, Oleg Vedeneev wrote:
> Windows client 2.6 version stopped connecting to Mikrotik devices exclusively. It works fine with servers installed on Linux.

From the logs it looks as if ``opt-verify`` is active on the Mikrotik
side.  This is an old option and is very likely breaking compatibility
because 2.6 has corrected many old bugs in tun-mtu/link-mtu calculation,
and this confuses ``opt-verify`` in older servers.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by ovedeneev** [comment]
Yes, there's a typo in that log message in Mikrotik.

```
data-ciphers AES-256-GCM:AES-192-GCM:AES-128-GCM:AES-256-CBC:AES-192-CBC:AES-128-CBC
cipher AES-256-CBC
```
This works for me just fine.



```
cipher AES-256-CBC
compat-mode 2.5.0
```

This combination does not work.

**Comment by schwabe** [comment]
Oh, right you probably need 

```
cipher AES-256-CBC
compat-mode 2.4.0
```

As we do not add cipher to data-ciphers with ``compat-mode 2.5.0``. Sorry, my mistake. But using ``data-ciphers`` is also a solution.

But I think that is up to Mikrotik to fix their OpenVPN implementation. They do not support NCP and maybe not even AEAD ciphers. This means that their implementation is on a 2.3.x level of OpenVPN. A version that is over 6 years old by now. Our ``compat-mode 2.4.0`` is just conversative in adding cipher also on that level and not only in 2.3.x compat mode.

**Comment by ovedeneev** [comment]
> cipher AES-256-CBC
> compat-mode 2.4.0

Yes, this did it. I believe the issue is resolved. I agree on your comments about OpenVPN implementation in Mikrotik.

Thank you.

**Comment by reuben-thundergrid** [comment]
Thanks, adding ` compat-mode 2.4.0 ` to the routeros exported config file worked for me

**Comment by Kingstley** [comment]
> Oh, right you probably need
> 
> ```
> cipher AES-256-CBC
> compat-mode 2.4.0
> ```
> 
> As we do not add cipher to data-ciphers with `compat-mode 2.5.0`. Sorry, my mistake. But using `data-ciphers` is also a solution.
> 
> But I think that is up to Mikrotik to fix their OpenVPN implementation. They do not support NCP and maybe not even AEAD ciphers. This means that their implementation is on a 2.3.x level of OpenVPN. A version that is over 6 years old by now. Our `compat-mode 2.4.0` is just conversative in adding cipher also on that level and not only in 2.3.x compat mode.

KUDOS! 
This rly helped..at my Mikrosh1t... RB2011UiAS-2HnD and as connection client i used Tunnelblick :)
Working as charm! :)
