### ISSUE TITLE
does not work with the mlock parameter OpenVPN 2.6.0

### ISSUE THREAD

**Issue by Dunduk99** [OpenVPN/openvpn#254]
Debian 11
Openvpn 2.6 

does not work with the mlock parameter

OpenVPN 2.6.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD]
library versions: OpenSSL 1.1.1t  7 Feb 2023, LZO 2.10
mlock: MEMLOCK limit: soft=64 KB, hard=64 KB
mlock: RLIMIT_MEMLOCK < 100 MB, increase limit
ERROR: setrlimit() failed: Operation not permitted (errno=1)
Exiting due to fatal error

**Comment by schwabe** [comment]
How do you start openvpn?

**Comment by Dunduk99** [comment]
> How do you start openvpn?

If this is what you mean, then it goes like this:
systemctl start openvpn@server

If I put openvpn 2.5.9 everything works fine.

**Comment by cron2** [comment]
Hi,

On Sat, Feb 18, 2023 at 08:48:43PM -0800, Dunduk99 wrote:
> Debian 11
> Openvpn 2.6 
> 
> does not work with the mlock parameter
> 
> OpenVPN 2.6.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD]
> library versions: OpenSSL 1.1.1t  7 Feb 2023, LZO 2.10
> mlock: MEMLOCK limit: soft=64 KB, hard=64 KB
> mlock: RLIMIT_MEMLOCK < 100 MB, increase limit
> ERROR: setrlimit() failed: Operation not permitted (errno=1)
> Exiting due to fatal error

systemd is setting the limit for locked memory too low (64 kb) - OpenVPN
2.5 does not check this limit, but can crash in very bad ways when the
limit is too low, mlock is in effect, and memory runs out.

This is why OpenVPN 2.6 requires 100MB available lockable memory.

See here for details: https://community.openvpn.net/openvpn/ticket/1390

There is two ways to fix this - either increase the memory limit in
the systemd unit file (+ open a debian bug against it), or remove the
mlock parameter - which, technically, does not bring real benefits 
on a well-configured system where non-root users can not read swap space.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by cron2** [comment]
I am now closing this issue, as this is an intentional change, documented in the ChangeLog.

**Comment by Dunduk99** [comment]
Thanx
