### ISSUE TITLE
Clients does not receive AUTH_PENDING or INFO_PRE control messages from scripts

### ISSUE THREAD

**Issue by mhalden** [OpenVPN/openvpn#256]
**Describe the bug**
A regression seem to have been introduced in `7dcde87b7a4323ffb173576d4559e14fcfe4e627` breaking the auth pending functionality from scripts. The `AUTH_PENDING` and `INFO_PRE` control messages are never received by the client.

The server logs that the messages are being sent, but with `UNDEF` instead of the client common name in the log message.

**To Reproduce**
Setup a server with the sample `totpauth.py` script setup. Clients configured for totp will not receive the challenge from the server.

**Expected behavior**
Client should receive the AUTH_PENDING and INFO_PRE control messages generated from authentication scripts.

**Version information (please complete the following information):**
 - OS: FreeBSD current.
 - OpenVPN version: 2.6 and master

**Additional context**
The functionality works as expected when building from commits older than `7dcde87b7a4323ffb173576d4559e14fcfe4e627`, e.g. `20ce5e3173cf1b086e1241619e8d949f0a6d0687` where the totp auth sample scripts was introduced.

**Comment by schwabe** [comment]
I understand the issue and why it is not happening on the management interface. Here is a quick fix to work around the issue:

```
commit a0f6101d744470262f239e7f54768a23fb9308d1 (HEAD -> bloom)
Author: Arne Schwabe <arne@rfc2549.org>
Date:   Mon Feb 27 18:04:08 2023 +0100

    WIP: Fix auth control push

diff --git a/src/openvpn/ssl.c b/src/openvpn/ssl.c
index 3d0dce1a3..81b0425c5 100644
--- a/src/openvpn/ssl.c
+++ b/src/openvpn/ssl.c
@@ -4028,6 +4028,11 @@ tls_send_payload(struct tls_multi *multi,
 
     ks = get_key_scan(multi, 0);
 
+    if (ks->state <= S_INITIAL)
+    {
+        ks = &multi->session[TM_INITIAL].key[KS_PRIMARY];
+    }
+
     if (ks->state >= S_ACTIVE)
     {
         if (key_state_write_plaintext_const(&ks->ks_ssl, data, size) == 1)
diff --git a/src/openvpn/ssl_verify.c b/src/openvpn/ssl_verify.c
index 996aee01f..6db04bbce 100644
--- a/src/openvpn/ssl_verify.c
+++ b/src/openvpn/ssl_verify.c
@@ -117,6 +117,12 @@ tls_common_name(const struct tls_multi *multi, const bool null)
     if (multi)
     {
         ret = multi->session[TM_ACTIVE].common_name;
+        if (!ret)
+        {
+            /* Session might not yet be established but we already know the
+             * common name from the initial session */
+            ret = multi->session[TM_INITIAL].common_name;
+        }
     }
     if (ret && strlen(ret))
     {
```

**Comment by schwabe** [comment]
These two patches should properly fix the issue:

https://patchwork.openvpn.net/project/openvpn2/patch/20230301135353.2811069-1-arne@rfc2549.org/

https://patchwork.openvpn.net/project/openvpn2/patch/20230301135353.2811069-2-arne@rfc2549.org/

**Comment by mygithub-one** [comment]
As for this BUG, when will it be released in the official release, not as a plugin

**Comment by schwabe** [comment]
@mygithub-one what do you mean with released in the official release and not as plugin?

**Comment by cron2** [comment]
Hi,

On Wed, Mar 01, 2023 at 08:24:26AM -0800, Arne Schwabe wrote:
> These two patches should properly fix the issue:
> 
> ***@***.***/
> 
> ***@***.***/

These two patches have been merged to master and release/2.6 branches
in the repos.

It would be good to have actual confirmation that they fix the problem
for the original poster ***@***.***), to make sure that the pending release
of 2.6.2 (this week!) is actually working correctly now...

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by mhalden** [comment]
My earlier testcase works with the `release/2.6` branch now.

**Comment by cron2** [comment]
Hi,

On Mon, Mar 20, 2023 at 11:17:45AM -0700, Marius Halden wrote:
> My earlier testcase works with the `release/2.6` branch now.

Cool, thanks for testing & confirming that the fix indeed works for you.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
