### ISSUE TITLE
Admin WEB UI constantly logs out

### ISSUE THREAD

**Issue by DjoleBelgrade** [OpenVPN/openvpn#265]
**Describe the bug**
Can't pass Licence Agreement on admin web panel. it logs me out after second page reload.

Can't click "Agree" button on admin WEB UI becaouse it logs me out.. i type username and password, get logged in and i see licence and when i just a reload page it ask for login agan... so when i click to "agree" it was not accepted because im not logged in.

**To Reproduce**
Just installed a fresh VM with ubuntu 22.04.1 and updated to 22.04.2, after that i was added repository for openVPN and install openvpn access server with apt.. and then i realise i just can't use admin web ui..

**Expected behavior**
Just to login to /admin and click "Agree". 

**Version information (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - OpenVPN version: where to see?

**Comment by schwabe** [comment]
OpenVPN has no Web UI. You might be using OpenVPN Access Server and can use support.openvpn.net for getting support for that product.
