### ISSUE TITLE
configure: error

### ISSUE THREAD

**Issue by jing8607** [OpenVPN/openvpn#266]
**IMPORTANT NOTE**
configure: error: libnl-genl-3.0 package not found or too old. Is the development package and pkg-config installed? Must be version 3.4.0 or newer for DCO

**Describe the bug**
when I run ./configure , it tell me an error,  I tried to download libnl-3.7.0 and make install it , but  still can't deal the error,
what should I do ?

**To Reproduce**
run ./configure

**Expected behavior**
no error

**Version information (please complete the following information):**
 - OS: [CentOs 7CentOS Linux release 7.9.2009 (Core)]
 - OpenVPN version: [current code]
 - Repeat for peer if relevant

**Additional context**
no

**Comment by cron2** [comment]
You only need libnl-genl if you have a working DCO kernel module, which I think is not available for CentOS (because that's just too old).  So run `configure --disable-dco`.

I tried to find whether there is a libnl-genl package for CentOS 7 that you could just install (maybe libnl-genl-devel or so), but I was not successful with that.  But I'm not a CentOS 7 user, so maybe I searched incorrectly.

**Comment by jing8607** [comment]
> You only need libnl-genl if you have a working DCO kernel module, which I think is not available for CentOS (because that's just too old). So run `configure --disable-dco`.
> 
> I tried to find whether there is a libnl-genl package for CentOS 7 that you could just install (maybe libnl-genl-devel or so), but I was not successful with that. But I'm not a CentOS 7 user, so maybe I searched incorrectly.

thanks a lot ,I'll try it later. if it still not working ,I'll try to compile 2.5version.☺

**Comment by cron2** [comment]
Hi,

On Wed, Mar 22, 2023 at 02:31:24AM -0700, Mullroy wrote:
> The github version doesn't contain a ./configure script. I had to perform these steps to 
> create one. It's not documented in the INSTALL document:

INSTALL reads

```
BUILD COMMANDS FROM SOURCE REPOSITORY CHECKOUT:

        autoreconf -i -v -f
        ./configure
        make
        sudo make install
```

which works just fine to generate a configure and build from there.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by jing8607** [comment]
> Hi,
> On Wed, Mar 22, 2023 at 02:31:24AM -0700, Mullroy wrote: The github version doesn't contain a ./configure script. I had to perform these steps to create one. It's not documented in the INSTALL document:
> INSTALL reads ``` BUILD COMMANDS FROM SOURCE REPOSITORY CHECKOUT: autoreconf -i -v -f ./configure make sudo make install ``` which works just fine to generate a configure and build from there. gert -- "If was one thing all people took for granted, was conviction that if you feed honest figures into a computer, honest figures come out. Never doubted it myself till I met a computer with a sense of humor." Robert A. Heinlein, The Moon is a Harsh Mistress Gert Doering - Munich, Germany ***@***.***

ok，thank you

**Comment by jing8607** [comment]
> Good day,
> 
> On Ubuntu 22.04 the missing package is: libnl-genl-3-dev Other packages required for the build: liblzo2-dev libcap-ng-dev python3-docutils
> 
> The github version doesn't contain a ./configure script. I had to perform these steps to create one. It's not documented in the INSTALL document: $ libtoolize $ aclocal $ automake --add-missing --force-missing --copy --foreign $ autoupdate $ autoconf

ok，thank you

**Comment by liuyang77886** [comment]
我执行./configure也报错：
configure: error: libnl-genl-3.0 package not found or too old. Is the development package and pkg-config installed? Must be version 3.4.0 or newer for DCO
我也执行安装了
sudo apt-get install liblzo2-dev libcap-ng-dev python3-docutils  libnl-genl-3-200 libnl-genl-3-dev 



ubuntu@VM-0-5-ubuntu:/opt/soft/vpn/openvpn-2.6.4$ sudo apt-get install libnl-genl-3-200 libnl-genl-3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnl-genl-3-200 is already the newest version (3.2.29-0ubuntu3).
libnl-genl-3-dev is already the newest version (3.2.29-0ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 292 not upgraded.


最后再次执行./configure
还是报错：
configure: error: libnl-genl-3.0 package not found or too old. Is the development package and pkg-config installed? Must be version 3.4.0 or newer for DCO



ubuntu@VM-0-5-ubuntu:/opt/soft/vpn/openvpn-2.6.4$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by Jeekate** [comment]
> Ubuntu 18 is old (5 years!), so there is no DCO, and what I already wrote about CentOS is valid here, too - run `configure --disable-dco` and enjoy. Or upgrade your Ubuntu system to 22.04

Ubuntu 22.04.2 LTS jammy occurred the same issue:
I tried sudo apt install as [liuyang77886](https://github.com/liuyang77886)
but error still remains

By adding ' --disable-dco' postfix, error says:
libcap-ng package not found, Is the development package and pkg-config installed?

**Comment by flichtenheld** [comment]
> > Ubuntu 18 is old (5 years!), so there is no DCO, and what I already wrote about CentOS is valid here, too - run `configure --disable-dco` and enjoy. Or upgrade your Ubuntu system to 22.04
> 
> Ubuntu 22.04.2 LTS jammy occurred the same issue: I tried sudo apt install as [liuyang77886](https://github.com/liuyang77886) but error still remains
> 
> By adding ' --disable-dco' postfix, error says: libcap-ng package not found, Is the development package and pkg-config installed?

Which is correct, you need that package either way. Comment https://github.com/OpenVPN/openvpn/issues/266#issuecomment-1479203595 above had all the required packages. It definitely builds on Ubuntu 22.04.

**Comment by Azmatul** [comment]
> configure
configure: error: libnl-genl-3.0 package not found or too old. Is the development package and pkg-config installed? Must be version 3.4.0 or newer for DCO

**Comment by flichtenheld** [comment]
> I tried your step still get this error..... i don't know what to do? :) i am using ubuntu 22.04.3 LTS configure: error: libnl-genl-3.0 package not found or too old. Is the development package and pkg-config installed? Must be version 3.4.0 or newer for DCO

Have you ensured that `libnl-genl-3-dev` is installed?

**Comment by jylihh** [comment]
Use old vesion of OpenVPN to solve this problem , such as 2.5.3.

**Comment by schwabe** [comment]
@jylihh there is no reason to use an old version. You can just disable DOC instead.

**Comment by Britnell** [comment]
I second @Bus42 's errors
- trying to install v2.6.8 i get missing pkg `libnl-genl-3.0 `
- `./configure --disable-dco` instead of missing pkg `libcap-ng`
- neither was fixed by installing `sudo apt-get install libcap-ng-dev libnl-genl-3.0-dev`

as suggested above i just tried with an old version 2.5.8 from one year ago, and that worked fine, though i'd prefer to use more up-to-date version

**Comment by cron2** [comment]
As @schwabe already wrote: do remember to install pkg-config - without pkg-config, configure can not find libnl-genl or libcap-ng.

**Comment by schwabe** [comment]
Here is also an improvement to our autoconf script to quit on Linux when pkg-config is not found: https://gerrit.openvpn.net/c/openvpn/+/465

**Comment by Britnell** [comment]
ahh thank you! I missed that. ( i thought there was some config file missing ... )

for ref for anyone else
`sudo apt-get install pkg-config`

then i was missing lz4, so
`sudo apt install liblz4-dev`

**Comment by science-code** [comment]
In my case, the solution was to install the [packages mentioned by dsommers above](https://github.com/OpenVPN/openvpn/issues/266#issuecomment-1836022841), and some other ones required later on by the `./configure` command:

    sudo apt-get install libnl-3-dev
    sudo apt install liblz4-dev
    sudo apt-get install libcap-ng-dev
    sudo apt-get install libssl-dev liblzo2-dev libpam0g-dev

After this the `./configure` and `make` could proceed without errors.

**Comment by InGramViking** [comment]
> RHEL/CentOS/Fedora equivalent: `sudo yum install libnl3-devel liblz4-devel openssl-devel lzo-devel pam-devel libcap-ng-devel`. Works with both `./configure` and `./configure --disable-dco`.

Or

`dnf install libnl3-devel  openssl-devel lzo-devel pam-devel libcap-ng-devel lz4-devel  `

**Comment by Vystii** [comment]
for me the command bellow did the trick. (I had libnl-(...) but it was too old)
```shell
sudo apt-get install libnl-genl-3-dev
```
