### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by jing8607** [OpenVPN/openvpn#268]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**
when I compile openvpn code, it's ok with ./configure and make,but in the step of make install, it tells a problem 

Libraries have been installed in:
   /usr/local/openvpn/lib/openvpn/plugins

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for

I tried to add '/usr/local/openvpn/lib/openvpn/plugins' to '/etc/ld.so.conf' but still not working

**To Reproduce**
./configure
make
make install

**Expected behavior**
no error

**Version information (please complete the following information):**
 - OS: [CentOS Linux release 7.9.2009 (Core)]
 - OpenVPN version: [2.5-release]
 - Repeat for peer if relevant

**Additional context**
no

**Comment by schwabe** [comment]
What error or problem do have? I don't see it in your report.

**Comment by selvanair** [comment]
Sounds  like you have successfully built and installed openvpn.

> Libraries have been installed in:
> /usr/local/openvpn/lib/openvpn/plugins
> 
> If you ever happen to want to link against installed libraries
> in a given directory, LIBDIR, you must either use libtool, and
> specify the full pathname of the library, or use the `-LLIBDIR'
> flag during linking and do at least one of the following:

That's a generic comment (not an error) from libtool and you can safely ignore it.  The only installed shared objects are plugins and there is no need to edit ld.so.conf or anything like that.

If the built openvpn binary is not working, report the error you get while running it.

**Comment by jing8607** [comment]
> 
Missing python-docutils - skipping man page generation (openvpn.8)
Missing python-docutils - skipping man page generation (openvpn-examples.5)
 /usr/bin/mkdir -p '/usr/local/share/man/man5'
 /usr/bin/install -c -m 644 ./openvpn-examples.5 '/usr/local/share/man/man5'
/usr/bin/install:cannot stat"./openvpn-examples.5" : No such file or directory
make[4]: *** [install-man5] Error 1

it reports error here
 I thought it reported error due to Missing python-docutils, 
So I install python-docutils by "yum -y install python-docutils", and make install again, but still not working, I don't know the comments "Libraries have been installed in:
/usr/local/openvpn/lib/openvpn/plugins" is block or not (灬ꈍ ꈍ灬)

what should I do next?
I can't open the websit https://community.openvpn.net/openvpn/ticket/1382 maybe it tells a solution, but I can't visit it

**Comment by jing8607** [comment]
> Sounds like you have successfully built and installed openvpn.
> 
> > Libraries have been installed in:
> > /usr/local/openvpn/lib/openvpn/plugins
> > If you ever happen to want to link against installed libraries
> > in a given directory, LIBDIR, you must either use libtool, and
> > specify the full pathname of the library, or use the `-LLIBDIR'
> > flag during linking and do at least one of the following:
> 
> That's a generic comment (not an error) from libtool and you can safely ignore it. The only installed shared objects are plugins and there is no need to edit ld.so.conf or anything like that.
> 
> If the built openvpn binary is not working, report the error you get while running it.

it reports error here
I thought it reported error due to Missing python-docutils,
So I install python-docutils by "yum -y install python-docutils", and make install again, but still not working, I don't know the comments "Libraries have been installed in:
/usr/local/openvpn/lib/openvpn/plugins" is block or not (灬ꈍ ꈍ灬)

what should I do next?
I can't open the websit https://community.openvpn.net/openvpn/ticket/1382 maybe it tells a solution, but I can't visit it

**Comment by jing8607** [comment]
> Sounds like you have successfully built and installed openvpn.
> 
> > Libraries have been installed in:
> > /usr/local/openvpn/lib/openvpn/plugins
> > If you ever happen to want to link against installed libraries
> > in a given directory, LIBDIR, you must either use libtool, and
> > specify the full pathname of the library, or use the `-LLIBDIR'
> > flag during linking and do at least one of the following:
> 
> That's a generic comment (not an error) from libtool and you can safely ignore it. The only installed shared objects are plugins and there is no need to edit ld.so.conf or anything like that.
> 
> If the built openvpn binary is not working, report the error you get while running it.

It's ok after I ./configure again, thanks a lot for your answer ☺

**Comment by pzhlkj6612** [comment]
> **Version information (please complete the following information):**
> 
> * OpenVPN version: [2.5-release]

> Missing python-docutils - skipping man page generation (openvpn.8)
> Missing python-docutils - skipping man page generation (openvpn-examples.5)
> /usr/bin/mkdir -p '/usr/local/share/man/man5'
> /usr/bin/install -c -m 644 ./openvpn-examples.5 '/usr/local/share/man/man5'
> /usr/bin/install:cannot stat"./openvpn-examples.5" : No such file or directory
> make[4]: *** [install-man5] Error 1

> it reports error here
> I thought it reported error due to Missing python-docutils, ...

Yup.

To future users: IMO, building OpenVPN from tarballs is simpler than building it from a cloned git repository. Those tarballs should have been generated by `make distcheck`, which makes sure the DISTribution always work like what documentation says.

https://github.com/OpenVPN/openvpn/blob/f588592ee6c6323b9674f470054e1638182c5b71/INSTALL#L116-L120

https://github.com/OpenVPN/openvpn/blob/f588592ee6c6323b9674f470054e1638182c5b71/doc/README.man#L5-L8

https://github.com/OpenVPN/openvpn/blob/f588592ee6c6323b9674f470054e1638182c5b71/dev-tools/gen-release-tarballs.sh#L200-L206

.
