### ISSUE TITLE
Release 2.6.0.5 But had always same issue. Same local IP address allocated

### ISSUE THREAD

**Issue by GMLinky** [OpenVPN/openvpn#269]
*** Description ***
When using several session at same time with OpenVPN client OpenVPN.exe
Local IP is always in range 10.7.0.xxx 10.7.3.xxx Ok
But sometimes with different VPN same local IP is allocated, it could 3 or 4 session. It screws up all sessions of course.

*** Reproduction ***
Use same config file with different VPN. It happens randomly

*** Expected behavior ***
Allocation of different local IP. May be a parameter ?

*** Version information ***
 - OS: Windows10
 - OpenVPN version: 2.6.0.5

*** Additional context ***
No local server

**Comment by schwabe** [comment]
That sounds like more a problem with your VPN configuration of having conflicting IP ranges rather than an OpenVPN bug.

**Comment by ordex** [comment]
it's the server that handles IP addresses assignment, so you must check with the server administrator what is going on and how they can fix that (assuming they can/want)
