### ISSUE TITLE
Compite option --enable_async_push disables ability to reenter wrong credentials upon login

### ISSUE THREAD

**Issue by a1466d44-d3dc-4c0b-90c7-315b088731d7** [OpenVPN/openvpn#279]
**Describe the bug**
When OpenVPN is compiled with the `--enable_async_push` option the client does not prompt the user to reenter its credentials, but immediately tries again as if the connection was interrupted.

**To Reproduce**
Our setup includes a Freeradius plugin
Line from OpenVPN configuration:
`plugin /usr/lib64/openvpn/plugins/radiusplugin.so /etc/openvpn/server/INSTANCENAME.radius`

**Expected behavior**
We'd expect, like without the compile time option `--enable_async_push`, that the client receives the auth failed message, and interprets it properly.

**Version information (please complete the following information):**
Server: RHEL 8.6 - openvpn-2.4.12-1.el8
Client Windows: OpenVPN 2.5.6 Windows-MSVC [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Mar 16 2022
Client Linux: Ubuntu 20.04 - openvpn 2.5.x _(information not fully recieved...)_

**Additional context**
Log excerpt Client _(Windows)_:
```
2023-03-15 11:48:33 us=921000 peer info: IV_GUI_VER=OpenVPN_GUI_11
2023-03-15 11:48:33 us=921000 peer info: IV_PLAT_VER=10.0_64bit
2023-03-15 11:48:33 us=921000 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA256
2023-03-15 11:48:33 us=921000 [[servername.domain.tld](http://servername.domain.tld/)] Peer Connection Initiated with [AF_INET]10.0.0.10:443
2023-03-15 11:48:35 us=125000 MANAGEMENT: >STATE:1678877315,GET_CONFIG,,,,,,
2023-03-15 11:48:35 us=125000 SENT CONTROL [[servername.domain.tld](http://servername.domain.tld/)]: 'PUSH_REQUEST' (status=1)
2023-03-15 11:48:35 us=125000 Connection reset, restarting [0]
2023-03-15 11:48:35 us=125000 TCP/UDP: Closing socket
2023-03-15 11:48:35 us=125000 SIGUSR1[soft,connection-reset] received, process restarting
2023-03-15 11:48:35 us=125000 MANAGEMENT: >STATE:1678877315,RECONNECTING,connection-reset,,,,,
2023-03-15 11:48:35 us=125000 Restart pause, 5 second(s)
2023-03-15 11:48:38 us=156000 SIGTERM[hard,init_instance] received, process exiting
2023-03-15 11:48:38 us=156000 MANAGEMENT: >STATE:1678877318,EXITING,init_instance,,,,,
```
Log excerpt Server:
```
Wed Mar 15 10:48:34 2023 10.20.0.13:59781 peer info: IV_GUI_VER=OpenVPN_GUI_11
Wed Mar 15 10:48:34 2023 10.20.0.13:59781 peer info: IV_SSO=openurl,crtext
Wed Mar 15 10:48:34 2023 10.20.0.13:59781 PLUGIN_CALL: POST /usr/lib64/openvpn/plugins/radiusplugin.so/PLUGIN_AUTH_USER_PASS_VERIFY status=2
Wed Mar 15 10:48:34 2023 RADIUS-PLUGIN: FOREGROUND THREAD: client_connect thread started.
Wed Mar 15 10:48:34 2023 RADIUS-PLUGIN: FOREGROUND THREAD: Auth_user_pass_verify thread started.
Wed Mar 15 10:48:34 2023 RADIUS-PLUGIN: FOREGROUND THREAD: New user.
Wed Mar 15 10:48:34 2023 10.20.0.13:59781 TLS: Username/Password authentication deferred for username 'myusername' [CN SET]
Wed Mar 15 10:48:34 2023 10.20.0.13:59781 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA
Wed Mar 15 10:48:34 2023 10.20.0.13:59781 [myusername] Peer Connection Initiated with [AF_INET]10.20.0.13:59781
Wed Mar 15 10:48:35 2023 RADIUS-PLUGIN: No attributes Acct Interim Interval or bad length.
Wed Mar 15 10:48:35 2023 RADIUS-PLUGIN: BACKGROUND AUTH: Reply-Message:Login FAILED please check username and password: myusername
Wed Mar 15 10:48:35 2023 Error: RADIUS-PLUGIN: BACKGROUND  AUTH: Auth failed!.

Wed Mar 15 10:48:35 2023 RADIUS-PLUGIN: FOREGROUND THREAD: Error receiving auth confirmation from background process.
Wed Mar 15 10:48:35 2023 TLS Error: key_state not authenticated
Wed Mar 15 10:48:35 2023 TLS Error: initializing data channel failed
Wed Mar 15 10:48:35 2023 10.20.0.13:59781 SIGUSR1[soft,init-data-channel-failed] received, client-instance restarting
```

Recompiling the RHEL Package and replacing the compile flag with `--disable_async_push` showed that this flag seems to be the root of the unexpected behavior. 

My question is: What behavior on the client side is to be expected if the auth result if not immediately present? Are we missing a client configuration flag?
Ubuntu packaged OpenVPN versions are compiled without this flag and work as expected. _(We have currently such servers in place, but want to switch to RedHat. But We'd like to stick with maintained packages)_

**Comment by cron2** [comment]
Hi,

On Wed, Mar 15, 2023 at 04:15:38AM -0700, 97b69f63-601b-4697-90db-7cdf2e2a0ea5 wrote:
> **Describe the bug**
> When OpenVPN is compiled with the `--enable_async_push` option the client does not prompt the user to reenter its credentials, but immediately tries again as if the connection was interrupted.
> 
> **Expected behavior**
> We'd expect, like without the compile time option `--enable_async_push`, that the client receives the auth failed message, and interprets it properly.
> 
> **Version information (please complete the following information):**
> Server: RHEL 8.6 - openvpn-2.4.12-1.el8
> Client Windows: OpenVPN 2.5.6 Windows-MSVC [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Mar 16 2022
> Client Linux: Ubuntu 20.04 - openvpn 2.5.x _(information not fully recieved...)_

So when you say "compiled with `--enable-async-push`", which of these
are you compiling with/without, and where do you see the problem?

This option should only make a difference on the server side - but 2.4.x
is so ancient that we're not going to spend much time to chase bugs in
there which might have been already fixed in the 2.5.x series (which saw
a complete overhaul of the "async anything" handling).

[..]
> Ubuntu packaged OpenVPN versions are compiled without this flag and work as expected. _(We have currently such servers in place, but want to switch to RedHat. But We'd like to stick with maintained packages)_

I'd assume that this works fine in 2.5.x (as my testbed is excercising
this option and async plugins, but that testbed was built for 2.5 and
I never tested all the option combinations in 2.4).  So it might not
be related to the option at all, just to "fixed source".

RHEL has the EPEL repos which have newer OpenVPN RPMs - maybe this
helps your use case?

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by a1466d44-d3dc-4c0b-90c7-315b088731d7** [comment]
> So when you say "compiled with `--enable-async-push`", which of these
> are you compiling with/without, and where do you see the problem?

We see that on the server side. Sorry for not being clear about that.

> I'd assume that this works fine in 2.5.x (as my testbed is excercising
> this option and async plugins, but that testbed was built for 2.5 and
> I never tested all the option combinations in 2.4).  So it might not
> be related to the option at all, just to "fixed source".
> 
> RHEL has the EPEL repos which have newer OpenVPN RPMs - maybe this
> helps your use case?

Openvpn is only part of the EPEL repository, ans is not available without.
Unfortunately RHEL9 is not an option for us at the time of writing.
Also RHEL8 is still supported, but that of course does not include specific packages, and their _(may be older)_ versions.


So you basically say that It might be an unsupported setup we have right now, and we can only migrate to an OS with an OpenVPN 2.5+ package, or have to compile it for ourselves? _(we currently use the later option, but could like to use maintained packages as it makes handling of issues and security risks much easier)_

**Comment by schwabe** [comment]
What we are saying is that OpenVPN project itself no longer actively develops the 2.4.x ranch as we shifted development to newer versions (2.5.x 3 years ago and 2.6.0 just now, see also https://community.openvpn.net/openvpn/wiki/SupportedVersions). 2.4.x will only get critical fixes at this time. 

So it is better to raise this issue with the EPEL maintainers to change the compliation flags. Also @dsommers maintains more up to date repositories for RHEL based distros (see https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos)

**Comment by a1466d44-d3dc-4c0b-90c7-315b088731d7** [comment]
Thank your for your clarification and help in this case. I'll continue to fix our issue internally by searching a more long lasting solution than using an outdated OpenVPN Version.
Lets try and make use of our support contract with RedHat ;) _(or directly update to RHEL 9. But that's something I cannot decide)_

Best regards and keep up the good work! :)
