### ISSUE TITLE
get this error: recv_socks_reply: TCP port read failed on recv(): Operation now in progress (errno=115) 

### ISSUE THREAD

**Issue by tohidmonjazeb** [OpenVPN/openvpn#280]
**Describe the bug**

I wanted to use a socks proxy with openvpn but I got this error :  recv_socks_reply: TCP port read failed on recv(): Operation now in progress (errno=115) .

I also searched about this on google and your issues too but couldn't find any solution.
please help me to solve this .

**Version information (please complete the following information):**
 - OS: kali 2022.4
 - OpenVPN version: 2.6.0

**Comment by cron2** [comment]
Hi,

On Wed, Mar 15, 2023 at 07:10:53AM -0700, tohid monjazeb wrote:
> **Describe the bug**
> 
> I wanted to use a socks proxy with openvpn but I got this error :  recv_socks_reply: TCP port read failed on recv(): Operation now in progress (errno=115) .

More logfile, please, with timestamps.

Most likely your SOCKS proxy is just slow, and after 5 seconds, the
SOCKS timeout strikes.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by selvanair** [comment]
I think we need to increase that 5s timeout or make it configurable -- vaguely recall similar reports in trac.

**Comment by cron2** [comment]
hi,

On Wed, Mar 15, 2023 at 10:16:36AM -0700, Selva Nair wrote:
> I think we need to increase that 5s timeout or make it configurable -- vaguely recall similar reports in trac.

Yes, there is a bug report in trac or GH (from ValidkSS?) that
--connect-timeout does not cover SOCKS timeouts, and for "the SOCKS
server is sort of remote" (TOR) the 5s might be too slow.

I've not investigate that ticket yet, was busy with breaking other
stuff...

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by cron2** [comment]
Hi,

On Thu, Mar 16, 2023 at 02:50:02AM -0700, tohid monjazeb wrote:
> 2023-03-16 05:45:17 OpenVPN 2.6.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
> 2023-03-16 05:45:17 library versions: OpenSSL 3.0.7 1 Nov 2022, LZO 2.10
> 2023-03-16 05:45:17 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> 2023-03-16 05:45:17 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> 2023-03-16 05:45:17 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.43.1:1080
> 2023-03-16 05:45:17 Socket Buffers: R=[212992->212992] S=[212992->212992]
> 2023-03-16 05:45:17 Attempting to establish TCP connection with [AF_INET]192.168.43.1:1080
> 2023-03-16 05:45:17 TCP connection established with [AF_INET]192.168.43.1:1080
> 2023-03-16 05:45:17 recv_socks_reply: TCP port read failed on recv(): Operation now in progress (errno=115)
> 2023-03-16 05:45:17 SIGUSR1[soft,socks-error] received, process restarting
> 2023-03-16 05:45:17 Restart pause, 1 second(s)

So this is actually not the 5s timer that we expected, but something else
with poor error handling in OpenVPN.  Maybe the SOCKS proxy is down, or
rejecting connections from your host.

If you do "telnet 192.168.43.1 1080", does that lead to an established
connection (for multiple seconds, at least), or to "connection refused"
or "connection closed by foreign host" in very short time?

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by selvanair** [comment]
The relevant code is, after select returns:
```
size = recv(sd, &c, 1, MSG_NOSIGNAL);
if (size != 1)
{
     msg(D_LINK_ERRORS | M_ERRNO, "recv_socks_reply: TCP port read failed on recv()");
}
```
The error printed (EINPROGRESS) is probably set by some previous call and likely irrelevant. Select indicates ready and recv possibly returns 0 here means peer disconnected? If so, this calls for better error handling.

**Comment by tohidmonjazeb** [comment]
> 



> Hi,
> On Thu, Mar 16, 2023 at 02:50:02AM -0700, tohid monjazeb wrote: 2023-03-16 05:45:17 OpenVPN 2.6.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO] 2023-03-16 05:45:17 library versions: OpenSSL 3.0.7 1 Nov 2022, LZO 2.10 2023-03-16 05:45:17 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication 2023-03-16 05:45:17 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication 2023-03-16 05:45:17 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.43.1:1080 2023-03-16 05:45:17 Socket Buffers: R=[212992->212992] S=[212992->212992] 2023-03-16 05:45:17 Attempting to establish TCP connection with [AF_INET]192.168.43.1:1080 2023-03-16 05:45:17 TCP connection established with [AF_INET]192.168.43.1:1080 2023-03-16 05:45:17 recv_socks_reply: TCP port read failed on recv(): Operation now in progress (errno=115) 2023-03-16 05:45:17 SIGUSR1[soft,socks-error] received, process restarting 2023-03-16 05:45:17 Restart pause, 1 second(s)
> So this is actually not the 5s timer that we expected, but something else with poor error handling in OpenVPN. Maybe the SOCKS proxy is down, or rejecting connections from your host. If you do "telnet 192.168.43.1 1080", does that lead to an established connection (for multiple seconds, at least), or to "connection refused" or "connection closed by foreign host" in very short time? gert -- "If was one thing all people took for granted, was conviction that if you feed honest figures into a computer, honest figures come out. Never doubted it myself till I met a computer with a sense of humor." Robert A. Heinlein, The Moon is a Harsh Mistress Gert Doering - Munich, Germany ***@***.***

Hi 

I did what you said.
telnet connects to proxy with no problem.

**Comment by selvanair** [comment]
Telnet success only means that connecting to the proxy works, while, I think, your error is after the client sends the proxy request and then tries to read a response. The proxy server appears to close the connection at that point. You may be trying to proxy UDP that the proxy server doesn't support, or for some other reason it doesn't like the address/port you have asked to proxy to.

The error message is very likely bogus and could be improved, but the real fault here appears to be with your proxy setup. What proxy is this?

**Comment by tohidmonjazeb** [comment]
> Telnet success only means that connecting to the proxy works, while, I think, your error is after the client sends the proxy request and then tries to read a response. The proxy server appears to close the connection at that point. You may be trying to proxy UDP that the proxy server doesn't support, or for some other reason it doesn't like the address/port you have asked to proxy to.
> 
> The error message is very likely bogus and could be improved, but the real fault here appears to be with your proxy setup. What proxy is this?

Hello selvanair

Yes you are right. I changed my proxy and now connection is successful. The previous proxy didn't support UDP as you said.
Thank you so much.

**Comment by selvanair** [comment]
The error message was improved by
commit 172640189277c940439d24fd31a59b8faffd0b3e (master)
commit c20a15844829a186b4d5256b0e8d76b8eb074845 (release/2.6)
This may be closed now (I couldn't).
