### ISSUE TITLE
Another one question about Explicit-exit-notify

### ISSUE THREAD

**Issue by Comandante1977** [OpenVPN/openvpn#297]
Hi!
First of all, I apologize that I'm asking about this case again.
Yes, I saw topics about it, but didnt find any solution in it. 

I have fresh install:
Debian 11 
 
 `5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`

OVPN 2.6.2 

`OpenVPN 2.6.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
library versions: OpenSSL 1.1.1n  15 Mar 2022, LZO 2.10
DCO version: 0.2.20230313-1-g726fdfe
Originally developed by James Yonan
Copyright (C) 2002-2023 OpenVPN Inc <sales@openvpn.net>
Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto_ofb_cfb=yes enable_dco=auto enable_dco_arg=auto enable_debug=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_iproute2=no enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_maintainer_mode=no enable_management=yes enable_option_checking=no enable_pam_dlopen=no enable_pedantic=no enable_pkcs11=yes enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_shared=yes enable_shared_with_static_runtimes=no enable_silent_rules=no enable_small=no enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=yes enable_werror=no enable_win32_dll=yes enable_wolfssl_options_h=yes enable_x509_alt_username=yes with_aix_soname=aix with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_openssl_engine=auto with_sysroot=no`

ovpn-dco-v2 kernel module from git compiled and installed

server.conf

_local aaa.bbb.ccc.ddd
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA256
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.252.0
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 67.207.67.3"
push "dhcp-option DNS 67.207.67.2"
push "explicit-exit-notify 3"
keepalive 10 120
cipher AES-128-GCM
data-ciphers AES-128-GCM:AES-128-GCM
user nobody
group nogroup
persist-key
persist-tun
client-config-dir /etc/openvpn/ccd
log-append /var/log/openvpn/openvpn.log
verb 4
crl-verify crl.pem
explicit-exit-notify 1
management 127.0.0.1 7555
learn-address /opt/openvpn/tc1.sh
script-security 3 
txqueuelen 4000
mute-replay-warnings_

client.conf

_client
dev tun
proto udp
remote aaa.bbb.ccc.ddd 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA256
cipher AES-128-GCM
data-ciphers AES-128-GCM:AES-128-GCM
ignore-unknown-option block-outside-dns
block-outside-dns
verb 3
explicit-exit-notify 3
mute-replay-warnings_

Clients that were tested - Android 9, OpenSuse 15.3.

Problem:

When client correctly disconnect session, server wait for 5 mins to delete session from list.

What I see in server log after client is disconnected:

_read UDPv4 [ECONNREFUSED]: Connection refused (fd=7,code=111)

 (60 the same messages here)

read UDPv4 [ECONNREFUSED]: Connection refused (fd=7,code=111)
hqvpnus01-u19061/176.99.82.12:27873 SIGTERM[soft,ovpn-dco: ping expired] received, client-instance exiting_

So, server close tunnel only after timeout.

On OVPN 2.5.1 this option works perfectly and disconnect immediately.

Help! )))

Thanks!

**Comment by cron2** [comment]
Hi,

On Fri, Mar 24, 2023 at 12:04:10PM -0700, Comandante1977 wrote:
> client.conf
[..]
> explicit-exit-notify 3
> 
> Clients that were tested - Android 9, OpenSuse 15.3.

Which openvpn version on the OpenSuse client?

OpenVPN Connect or OpenVPN for Android on the Android device?

> Problem:
> 
> When client correctly disconnect session, server wait for 5 mins to delete session from list.

I guess that the client is pre-2.6.0, so will send the explicit-exit-notify
as a data channel packet - which does not work with DCO.  2.6.x to 2.6.x
will send EEN via control channel, and that should work fine.

@plaisthos, do you know what the state of control-channel EEN is in
OpenVPN Connect?

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by Comandante1977** [comment]
> Which openvpn version on the OpenSuse client? OpenVPN Connect or OpenVPN for Android on the Android device?

Android - OpenVPN Connect 3.3.1 installed from Play Store
OpenSuse - 
NetworkManager v. 1.22.10-3.7.1
NetworkManager-openvpn v. 1.8.10
installed from repos. May be these versions are OpenSuse format.

> I guess that the client is pre-2.6.0, so will send the explicit-exit-notify as a data channel packet - which does not work with DCO. 2.6.x to 2.6.x will send EEN via control channel, and that should work fine. 

I guess so also! But, clients are not too old. May be for OpenSuse, but android is up to date. Strange.

**Comment by schwabe** [comment]
OpenVPN Connect is on OpenVPN 3.6 or so, which is over a year old. I don't think they have support for that.

**Comment by Comandante1977** [comment]
Hi!
Installed Openvpn for Android v. 0.7.43 from Arne Schwabe.
EEN works correctly!

As for OpenSuse, there are no updates in official repos, but it's not the most problem.
Will look for updates or recompile myself.

Thanks in advance.
Issue closed.
