### ISSUE TITLE
crash on OpenVPN 2.6.2 Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by kolya25** [OpenVPN/openvpn#301]
Please tell me, I can't install the ovpn-dco-v2 kernel module.

```
/home/paul/ovpn-dco/gen-compat-autoconf.sh /home/paul/ovpn-dco/compat-autoconf.h
make -C /lib/modules/5.15.0-67-generic/build M=/home/paul/ovpn-dco PWD=/home/paul/ovpn-dco REVISION=0.2.20230323-1-g1c2c84e CONFIG_OVPN_DCO_V2=m INSTALL_MOD_DIR=updates/	modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-67-generic'
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/main.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/bind.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/crypto.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/ovpn.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/peer.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/sock.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/stats.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/netlink.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/crypto_aead.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/pktid.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/tcp.o
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/udp.o
  LD [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/ovpn-dco-v2.o
  MODPOST /home/paul/ovpn-dco/Module.symvers
  CC [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/ovpn-dco-v2.mod.o
  LD [M]  /home/paul/ovpn-dco/drivers/net/ovpn-dco/ovpn-dco-v2.ko
  BTF [M] /home/paul/ovpn-dco/drivers/net/ovpn-dco/ovpn-dco-v2.ko
Skipping BTF generation for /home/paul/ovpn-dco/drivers/net/ovpn-dco/ovpn-dco-v2.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-67-generic'
root@vpn-cl:/home/paul/ovpn-dco# make install
/home/paul/ovpn-dco/gen-compat-autoconf.sh /home/paul/ovpn-dco/compat-autoconf.h
make -C /lib/modules/5.15.0-67-generic/build M=/home/paul/ovpn-dco PWD=/home/paul/ovpn-dco REVISION=0.2.20230323-1-g1c2c84e CONFIG_OVPN_DCO_V2=m INSTALL_MOD_DIR=updates/ modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-67-generic'
arch/x86/Makefile:142: CONFIG_X86_X32 enabled but no binutils support
  INSTALL /lib/modules/5.15.0-67-generic/updates//drivers/net/ovpn-dco/ovpn-dco-v2.ko
  SIGN    /lib/modules/5.15.0-67-generic/updates//drivers/net/ovpn-dco/ovpn-dco-v2.ko
At main.c:167:
- SSL error:FFFFFFFF80000002:system library::No such file or directory: ../crypto/bio/bss_file.c:67
- SSL error:10000080:BIO routines::no such file: ../crypto/bio/bss_file.c:75
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  /lib/modules/5.15.0-67-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-67-generic'
depmod -a
```
I tried to run the module manually modprobe ovpn-dco-v2

```
root@vpn-cl:/home/paul/ovpn-dco# modprobe ovpn-dco-v2
modprobe: ERROR: could not insert 'ovpn_dco_v2': Operation not permitted
```

My OS and kernel version: 

```
root@vpn-cl:/home/paul/ovpn-dco# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
root@vpn-cl:/etc/openvpn# uname -r
5.15.0-67-generic
```
Tell me how you can solve the problem , or the best practice of which OS to install so that there are no problems with OpenVPN 2.6.2 with DCO ?

Thanks.

**Comment by selvanair** [comment]
@kolya25 Could you please test by removing `status vpn_cl.log` from client config? That should bypass a bug fixed since 2.6.2.

**Comment by kolya25** [comment]
I deleted the `status vpn_cl.log` from client config, errors remained in the server and client logs as before

**Comment by selvanair** [comment]
> I deleted the status vpn_cl.log from client config, errors remained in the server and client logs as before

I never saw any errors in your server or client logs: the server logged TCP disconnect which is not an "error". Client logs end abruptly with no errors logged. The segfault in dmesg was the only indication of an error. I guess you are not running this from command line -- otherwise you would have got Segmentation Fault on command line. So impossible to know whatever is executing openvpn is adding ---status or any other options.
 
Either wait for 2.6.3 or build OpenVPN from the latest master branch and try. Then post client logs at verb 4 and stack trace using a non-stripped binary if you still get a segfault.

**Comment by kolya25** [comment]
After the 2.6.3 update , the error disappeared .Thanks.

**Comment by ogolovanov** [comment]
Latest ubuntu server 22.04 with latest kernel available ( 5.15.0-92.102 )

Using ovpn_dco_v2 kernel module does not work for me ( DCO ignored ).

> ogolovanov@selenium:~$ lsmod | grep dco
ovpn_dco_v2            73728  0
ip6_udp_tunnel         16384  1 ovpn_dco_v2
udp_tunnel             20480  1 ovpn_dco_v2

Syslog:

> Jan 31 03:54:40 server kernel: [  569.744536] OpenVPN data channel offload (ovpn-dco) ovpn:0-20220601git2db65af -- (C) 2020-2022 OpenVPN, Inc.
Jan 31 03:54:40 server kernel: [  569.744547] ovpn: can't register RTNL link ops
Jan 31 03:54:40 server kernel: [  569.744680] ovpn: initialization failed, error status=-17

Connection established, but DCO ignored.

> Jan 31 03:54:40 server openvpn3-service-logger[2651]: {tag:1046415159024048155} Connected: xxx:1194 (xxx) via /UDPv4 on tun/10.8.0.5/ gw=[10.8.0.1/]

But old kernel module "ovpn_dco" works as expected. ( package = "kmod-ovpn-dco" )

> lsmod | grep dco
ovpn_dco               73728  0
ip6_udp_tunnel         16384  1 ovpn_dco
udp_tunnel             20480  1 ovpn_dco

Syslog:

> Jan 31 04:14:11 server openvpn3-service-logger[2651]: {tag:8058288393314618067} Connected: : (xxx) via /UDPv4-DCO on ovpn-dco/10.8.0.5/ gw=[10.8.0.1/]

I really hope that someday it will work without "dancing".

**Comment by ordex** [comment]
Are you running openvpn-2.6.3 or later?
From what you are saying it seems you are trying to use a new DCO kernel module against an older OpenVPN userspace software.

**Comment by ogolovanov** [comment]
Hi.

> From what you are saying it seems you are trying to use a new DCO kernel module against an older OpenVPN userspace software.

When i am starting session with DCO enabled -> kernel module "ovpn_dco_v2" is autoloaded.
But it does not work ( = connection works, but DCO disabled ).
If i manually unload ovpn_dco_v2 and load ovpn_dco -> everything works.
So i am confused, why "ovpn_dco_v2" not working for me with latest software on ubuntu 22.04.

> Are you running openvpn-2.6.3 or later?

Yes, latest openvpn available.

client:

```
OpenVPN3/Linux v20 (openvpn3)
OpenVPN core v3.7.2 linux x86_64 64-bit
Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
```

server:

```
OpenVPN 2.6.8 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
DCO version: 0.2.20231117
Originally developed by James Yonan
Copyright (C) 2002-2023 OpenVPN Inc <sales@openvpn.net>
Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto_ofb_cfb=yes enable_dco=auto enable_dco_arg=auto enable_debug=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_iproute2=no enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_maintainer_mode=no enable_management=yes enable_option_checking=no enable_pam_dlopen=no enable_pedantic=no enable_pkcs11=yes enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_shared=yes enable_shared_with_static_runtimes=no enable_silent_rules=no enable_small=no enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=yes enable_werror=no enable_win32_dll=yes enable_wolfssl_options_h=yes enable_x509_alt_username=yes with_aix_soname=aix with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_openssl_engine=auto with_sysroot=no

```

**Comment by dsommers** [comment]
@ogolovanov You need OpenVPN 3 Linux v21 to have ovpn-dco-v2 support.

**Comment by ordex** [comment]
You are using the openvpn3-linux client. It started supporting ovpn-dco-v2 starting from v21, but you have v20 installed.

Are you also having problems on the server? Sorry but from your message it is not clear what error belongs to what.

**Comment by ogolovanov** [comment]
Thanks :)
