### ISSUE TITLE
OpenVPN behaves like --ping-restart despite using --ping-exit flag

### ISSUE THREAD

**Issue by jonasjancarik** [OpenVPN/openvpn#302]
**Describe the bug**
OpenVPN behaves like --ping-restart despite using --ping-exit flag. When the server is unreachable for 60 seconds, the OpenVPN process should exit, but it keeps restarting instead.

Log output:
```
2023-03-28 16:08:22 [UNDEF] Inactivity timeout (--ping-restart), restarting
2023-03-28 16:08:22 SIGUSR1[soft,ping-restart] received, process restarting
...
```

**To Reproduce**
1. Start the OpenVPN process using the following command (replace placeholders with actual values): `openvpn --config /path/to/connect.ovpn --auth-user-pass /path/to/pass --dev devname --dev-type tun --ping 10 --ping-exit 60`
2. Disconnect or make the server unreachable.
3. Observe the logs, which show the OpenVPN process restarting due to inactivity timeout, as if the --ping-restart flag was used.

**Expected behavior**
The OpenVPN process should exit after 60 seconds of inactivity due to the --ping-exit 60 flag.

**Version information (please complete the following information):**
- OS: Ubuntu 22.04
- OpenVPN version: 2.5.5 (built on Jul 14 2022)

**Additional context**
- I have checked the connect.ovpn configuration file for any conflicting settings, and there is no ping-restart option set in the file.
- The machine is an Amazon WorkSpaces instance running Ubuntu 22.04.

The config file (connect.ovpn - autogenerated with the ProtonVPN CLI from https://github.com/Rafficer/linux-cli-community) looks like this:

```
client
dev tun
proto udp

remote 169.150.196.99 1194

remote 169.150.196.99 1194

remote 169.150.196.99 1194

remote 169.150.196.99 1194

remote-random
resolv-retry infinite
nobind
cipher AES-256-CBC
auth SHA512
comp-lzo no
verb 3

tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun

reneg-sec 0

remote-cert-tls server
auth-user-pass
pull
fast-io
```

**Comment by jonasjancarik** [comment]
I think you're right, I found this in the logs:

`2023-03-28 17:08:34 us=527881 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.18.0.1,sndbuf 524288,rcvbuf 524288,redirect-gateway def1,explicit-exit-notify,comp-lzo no,route-gateway 10.18.0.1,topology subnet,ping 10,ping-restart 60,socket-flags TCP_NODELAY,ifconfig 10.18.0.9 255.255.0.0,peer-id 131079,cipher AES-256-GCM'`

I'll try setting ping-exit to a lower value than 60.

**Comment by selvanair** [comment]
You can add `pull-filter ignore ping-restart ` to filter out that pushed option.

**Comment by jonasjancarik** [comment]
Ok, thanks for your help!

I'll also try `--ping-restart 0` which might override and disable the pulled option. (Leaving this here for future reference...)

**Comment by selvanair** [comment]
> Ok, thanks for your help!
> 
> I'll also try `--ping-restart 0` which might override and disable the pulled option. (Leaving this here for future reference...)

First, ping-restart and ping-exit are mutually exclusive, if you want the latter to be effective, you do not want to set ping-restart. Second, the latest value will over-ride any previous setting, so in this case the pulled option ping-restart will override.  Use pull-filter ignore.
