### ISSUE TITLE
Question: how to connect to more VPN at the same time?

### ISSUE THREAD

**Issue by Ciao223344** [OpenVPN/openvpn#311]
HI, i want to run more chrome.exe with different ip at the same time.
So, i read on internet that is possible with OpenVPN GUI but i didn't find any guide. I want that every connection work only with the programm that i declare. There is somebody that can help me?

**Comment by shipitsin-ilia** [comment]
can you elaborate on `i read on internet that is possible with OpenVPN GUI` ? any particular link ?

**Comment by Ciao223344** [comment]
this: "If you are a system administrator and you require a complex setup where multiple connections are active at the same time, there is the option to use the open source community OpenVPN client software available from our website." from this site https://openvpn.net/client-connect-vpn-for-windows/

**Comment by Ciao223344** [comment]
I thought that the program is Open VPN GUI (that)

**Comment by Ciao223344** [comment]
Ok, thanks for the help
