### ISSUE TITLE
block-ipv6 option has no effect

### ISSUE THREAD

**Issue by pokamest** [OpenVPN/openvpn#322]
- OS: [MacOS]
 - OpenVPN version: [e.g. 2.6.3]

Does block-ipv6 option has any effect on MacOS, Windows and Linux?

**Comment by flichtenheld** [comment]
Please provide more details what exactly you tried and where it did not match your expectations. As the documentation mentions this option requires some additional configuration to be effective.

**Comment by pokamest** [comment]
I just tried to pass option "block-ipv6" to openvpn (2.6.3) and found that the ipv6 was not blocked.
At first glance this option should block ipv6 as described:
```
--block-ipv6     : (Client) Instead sending IPv6 to the server generate
                   ICMPv6 host unreachable messages on the client.
```
What is correct way to block ipv6?

**Comment by schwabe** [comment]
See the man page. That even comes with an example how to use the option.
