### ISSUE TITLE
Possible certificate problems after install of OpenVPN in Mac OS

### ISSUE THREAD

**Issue by fithisux** [OpenVPN/openvpn#327]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**

**Not 100% that openvpn or its build is to blame**

I installed openvpn and openvpn connect in Mac OS via brew.

Previously various sites were working in Chrome and Firefox

https://www.verbling.com/dashboard
https://www.italki.com/en/

Now they are not and they appear with the

```
Secure Connection Failed

An error occurred during a connection to www.italki.com.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**To Reproduce**
```sh
brew install openvpn
brew install --cask openvpn-connect
brew update && brew upgrade
sudo brew services restart openvpn
```

**Expected behavior**
Sites should be accessible as before. Even if I uninstall things do not work any more.

**Version information (please complete the following information):**
 - OS: Mac OS 13.3.1 (a) 
     (Darwin C02CH2W2MD6R.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64)
 - OpenVPN version: 2.6.3
 - Repeat for peer if relevant

**Additional context**
Previous I had perimeter 81
My Laptop has a Sophos installation
and a firewall from Check Point.

**Comment by schwabe** [comment]
A warning about a server's SSL certificate points rather at your addinitional client security software than OpenVPN. OpenVPN does not mess with server certificates.

**Comment by fithisux** [comment]
I agree. You can close it @schwabe
