### ISSUE TITLE
How to build Open VPN 2.6.3 with applied XOR patch and DCO drivers for Windows OS? 

### ISSUE THREAD

**Issue by oblomingo** [OpenVPN/openvpn#329]
I would like to set up Open VPN connection in Windows 10/11.
It seems I could take pre-build dco drivers from https://github.com/OpenVPN/ovpn-dco-win and install them very easily: `devcon install ovpn-dco.inf ovpn-dco`
Open VPN binary files (openvpn.exe) can be taken from the official open vpn installer files or it can be build using `https://github.com/OpenVPN/openvpn` or `https://github.com/OpenVPN/openvpn-build`    
It is unclear to me, how to apply XOR patch (https://tunnelblick.net/cOpenvpn_xorpatch.html) to the latest Open VPN 2.6.3 version.
Should I find 2.6.3 patches and apply them to openvpn source code and then build it?
It seems there are 2.6.3 patches in https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.6.3/patches (for MacOs), can I use these patches for openvpn and then build windows version?
How to apply these files? It is looks like a file diff, does it apply changes to a specific file? Not clear what files should be changed :(
In case of OpenVPN build for Windows 10/11, what github project should I use? `https://github.com/OpenVPN/openvpn` or `https://github.com/OpenVPN/openvpn-build` ?

P.S. https://github.com/lawtancool/openvpn-windows-xor would be problem solver, but unfortunately it has only 2.5.7 and doesn't support DCO drivers.

**Comment by flichtenheld** [comment]
The official builds for Windows use Visual Studio to build openvpn.exe. See https://github.com/OpenVPN/openvpn-build/blob/master/windows-msi/build-and-package.ps1#L99
It is also possible to build openvpn.exe for Windows with MinGW, although it is not very well documented how to set up the cross-build environment. But one could follow https://github.com/OpenVPN/openvpn/blob/master/.github/workflows/build.yaml#L59

**Comment by lstipakov** [comment]
Doesn't XOR patch mangle data channel packets? It won't make much sense with DCO, since data channel is handled in kernel.

**Comment by schwabe** [comment]
Yes. to support XOR patch you would need to patch the kernel driver as well.

**Comment by oblomingo** [comment]
@flichtenheld Great, thank you. Should I apply XOR patch before running https://github.com/OpenVPN/openvpn-build/blob/master/windows-msi/build-and-package.ps1#L99 ?
@schwabe @lstipakov Thank you for the quick response. When you say that the kernel driver should be patched. Do you mean VPN server Linux side? At the moment the client-server connection works with XOR patch, but the Windows client uses TAP driver. If I change Windows client driver from TAP to DCO, should I change something on the server side?

**Comment by cron2** [comment]
whenever DCO is involved (windows-dco, linux-dco) the xor patch for the "openvpn binary" will do nothing, as packet forwarding happens in the DCO kernel driver.

**Comment by oblomingo** [comment]
@cron2 Just to double-check, does it mean that it is impossible to obfuscate a VPN (with DCO driver) connection using XOR patch? 
In case I still would like to obfuscate a connection, should I use alternatives, like Stunnel or Obfsproxy?

**Comment by schwabe** [comment]
If you need obfuscation DCO is not for you.

**Comment by cron2** [comment]
@oblomingo it means "if you want obfuscation and DCO, you need to patch the kernel driver, not (only) the userland binary, and it will be a massive piece of work".  So the XOR patch would need to be used with `--disable-dco`, on all DCO-enabled platforms (Linux, Windows, FreeBSD).  Ideally it would auto-disable DCO if an XOR-related option is detected.

... in other words, the question "how to build 2.6.3 with the XOR patch" will not get you "XOR with DCO".

**Comment by oblomingo** [comment]
Thank you for the detailed reply!
I think we can close the issue.
