### ISSUE TITLE
P2P support

### ISSUE THREAD

**Issue by charlieye-dev** [OpenVPN/openvpn#330]
After setup openvpn, IMO, the routing relationship is as follows，
> Client-1 -> Server -> Client-2
    
I hope that clients can access each other directly without server, Can openvpn achieve the following routing after setup?
> Client-1 -> Client-2 
    
If YES, how can i configure it.

**Comment by cron2** [comment]
Just for completeness, the answer is "no" - OpenVPN today does not support direct client-to-client tunnels, all encrypted traffic has to go via the server.
