### ISSUE TITLE
No data flow

### ISSUE THREAD

**Issue by DmitryShchegolev** [OpenVPN/openvpn#334]
Ping lost from client to server in tunnel. After successful connection to server from client to server passes about seven pings and after that it is packet lost until client restart connection.

Server is fresh Ubuntu 22.04 LTS. (OpenVPN 2.5.5 x86_64-pc-linux-gnu)
Server config:
local 212.47.219.237
port 1194
proto udp4
fragment 1500
mssfix 1500
dev tun
ca /etc/openvpn/server/private/AA.pem
crl-verify /etc/openvpn/server/private/AA.crl
cert /etc/openvpn/server/private/R02Cert.pem
key /etc/openvpn/server/private/R02Key.pem
dh /etc/openvpn/server/private/dh2048.pem
topology subnet
server 192.168.142.0 255.255.255.0
ifconfig-pool-persist /var/log/openvpn/ipp.txt
push "route 192.168.0.0 255.255.0.0"
push "dhcp-option DNS 192.168.168.2"
push "dhcp-option DNS 192.168.8.2"
keepalive 1 30
tls-auth /etc/openvpn/server/private/ta.key 0
max-clients 250
user nobody
group nogroup
persist-tun
persist-key
status /var/log/openvpn/openvpn-status.log
verb 3
explicit-exit-notify 1

Client is Ubuntu 22.10 (OpenVPN 2.6_git x86_64-pc-linux-gnu)
Client config:
client
dev tun
fragment 1500
mssfix 1500
proto udp4
remote 212.47.219.237 1194
resolv-retry infinite
nobind
persist-key
persist-tun
mute-replay-warnings
ca caCert.pem
pkcs12 dmitry.p12
auth-nocache
remote-cert-tls server
tls-auth ta.key 1
verb 3

There are no unusual messages in log files.
ping and traceroute attached. Time on client and server differs by an hour due to timezones.
[openvpn-ping-from-client.txt](https://github.com/OpenVPN/openvpn/files/11486491/openvpn-ping-from-client.txt)
[openvpn-tcpdump-client.txt](https://github.com/OpenVPN/openvpn/files/11486492/openvpn-tcpdump-client.txt)
[openvpn-tcpdump-server.txt](https://github.com/OpenVPN/openvpn/files/11486493/openvpn-tcpdump-server.txt)
[openvpn-client-log.txt](https://github.com/OpenVPN/openvpn/files/11486711/openvpn-client-log.txt)
[openvpn-server-log.txt](https://github.com/OpenVPN/openvpn/files/11486712/openvpn-server-log.txt)

**Comment by schwabe** [comment]
What happes to the VPN connection. Does it stay connected or does it time out eventually? Also what network is the client using. Since you are not using `redirect-gateway` or `redirect-private` check that the routes pushed by the VPN do not create a routing loop. Also try to look not only on tcpdump of the ethernet interface but also on the tun interfaces. But overall this feels more like a configuration problems rather than a bug in OpeNVPN.

**Comment by DmitryShchegolev** [comment]
> 

After client reconnect by timeout again about seven pings. I attach logs, tcpdump, ping. Client on mobile internet. I guess with private ip and nat translation. I ping server's tun ip, routing not in play.
ip route on client
default via 172.16.11.1 dev wlp3s0 proto dhcp src 172.16.11.245 metric 1024 
10.138.65.0/24 dev lxdbr0 proto kernel scope link src 10.138.65.1 
169.254.0.0/16 dev virbr0 scope link metric 1000 linkdown 
172.16.11.0/24 dev wlp3s0 proto kernel scope link src 172.16.11.245 metric 1024 
172.16.11.1 dev wlp3s0 proto dhcp scope link src 172.16.11.245 metric 1024 
192.168.0.0/16 via 192.168.142.1 dev tun0 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
192.168.142.0/24 dev tun0 proto kernel scope link src 192.168.142.2 
There is no any loops...

**Comment by DmitryShchegolev** [comment]
If I change protocol to tcp4 on client and server, all works fine.

**Comment by schwabe** [comment]
This looks more like some network problem in your setup with UDP than anything. OpenVPN will play nicely with NAT and changing IPs (peer-id). if you can try over another network to rule out a bug in openvpn

**Comment by DmitryShchegolev** [comment]
I changed the server's udp port to a non-standard one and it worked. Providers block the work of openvpn?

**Comment by schwabe** [comment]
There are states/providers that might block OpenVPN but that is outside the control of this project and also not a bug in this project.
