### ISSUE TITLE
UUID related questions

### ISSUE THREAD

**Issue by sklun** [OpenVPN/openvpn#340]
I want to bind the client configuration file to a fixed device.

It is known that the peer info provided by openvpn2 includes the MAC address, but the MAC address can change, for example, the WIFI and Ethernet have two different MAC addresses, so the MAC address is not very "unique".

In openvpn3 client, the UUID device identifier is returned as the UV_UUID parameter, which is more suitable as a device identifier. However, the openvpn connect that supports openvpn3 can only connect to one configuration file at a time, while my use case requires connecting to multiple configuration files at the same time. 

Therefore, is it possible for openvpn2 client to return UUID or is there an openvpn3 based client for mac/Windows, or are there other solutions?

**Comment by schwabe** [comment]
All of these parameters are very weak and can be easily faked. You can easily do `setenv UV_UUID string` in the OpenVPN 2.x file yourself to get yourself an identifier like that.
