### ISSUE TITLE
Failed to update apt cache due to missing Release file from OpenVPN apt repository

### ISSUE THREAD

**Issue by fcanela** [OpenVPN/openvpn#354]
**Describe the bug**
When attempting to update the apt cache after configuring an apt source using the instructions from the official community wiki for OpenVPN, an error occurs. The error message is as follows:

```
Failed to update apt cache: 
E: The repository 'https://build.openvpn.net/debian/stable jammy Release' does not have a Release file.
W: Updating from such a repository can't be done securely and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
```

**To Reproduce**
To reproduce the behavior, please follow these steps:
1. Visit the official community wiki for OpenVPN apt repository configuration: [OpenVPN Community Wiki - Debian/Ubuntu: Using OpenVPN apt repositories](https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos#DebianUbuntu:UsingOpenVPNaptrepositories)
2. Follow the provided instructions to import the public key
3. Add a file in `/etc/apt/sources.list.d/` with the following content (adapt the key name): `deb [arch=amd64 signed-by=/usr/share/keyrings/openvpn-archive-keyring.gpg] https://build.openvpn.net/debian/stable jammy main`
4. Run the `apt update` command and observe the error message

**Expected behavior**
After successfully configuring apt using the provided documentation, the `apt update` command should be able to update the apt cache without encountering any errors.

**Version information**
- OS: Kubuntu 22.04.2 (amd64)
- Version: pointing to the "stable" version branch on apt, but no specific OpenVPN version as this occurs before being able to install.

**Additional context**

**Comment by flichtenheld** [comment]
The correct URL is https://build.openvpn.net/debian/openvpn/stable (note the missing `openvpn` in your URL).
