### ISSUE TITLE
Determine gateway-ip during up script, or after the fact

### ISSUE THREAD

**Issue by moracca** [OpenVPN/openvpn#357]
When running openvpn client on freebsd, after a successful connection, the ifconfig output used to include the gateway IP that was determined during the connection.

for example, the ip "192.168.254.1" below:
```
# ifconfig tun0
 tun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
         options=80000<LINKSTATE>
         inet 192.168.254.21 --> 192.168.254.1 netmask 0xffffff00
         groups: tun
         nd6 options=9<PERFORMNUD,IFDISABLED>
         Opened by PID 15201
```

I'm not sure if it is a recent change to FreeBSD (presently running 13.2) or a recent change to openVPN (running OpenVPN 2.6.4), but now when running ifconfig for the tun interface, it does not include the gateway IP:
```
# ifconfig tun0
tun0: flags=8043<UP,BROADCAST,RUNNING,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	inet 192.168.254.21 netmask 0xffffff00 broadcast 192.168.254.255
	groups: tun
	nd6 options=9<PERFORMNUD,IFDISABLED>
	Opened by PID 1868
```
notice that it no longer includes the gateway IP.

I also notice that the flags are different (it is now missing the POINTOPOINT flag), which perhaps is what is leading to the different output.

My question is twofold:
Is there a change that should be made in the configs or cli flags to change the POINTOPOINT flag?
If not, is there a way to get the gateway IP during the up script or after the fact?  I've printed out all the environment variables that were set before the script runs, and none of them contain the right IP.  The only way I have seen is to look in the openvpn log file and slurp the IP from there, but in some circumstances even this has been unreliable.

Is there some better way to determine this?

Thanks!

**Comment by cron2** [comment]
Hi,

On Fri, Jun 23, 2023 at 07:00:36AM -0700, Lannar Dean wrote:
> # ifconfig tun0
> tun0: flags=8043<UP,BROADCAST,RUNNING,MULTICAST> metric 0 mtu 1500
> 	options=80000<LINKSTATE>
> 	inet 192.168.254.21 netmask 0xffffff00 broadcast 192.168.254.255
> 	groups: tun
> 	nd6 options=9<PERFORMNUD,IFDISABLED>
> 	Opened by PID 1868
> ```
> notice that it no longer includes the gateway IP.
> 
> I also notice that the flags are different (it is now missing the POINTOPOINT flag), which perhaps is what is leading to the different output.

This is intentional and required for DCO operations (and arguably the
correct way to configure a "topology subnet" config, not futzing around
with a POINTOPOINT interface setup and additional routes).

See git

commit 22bc63c78439ed23b974b8f822330d75ec79c7fc
Author: Gert Doering ***@***.***>
Date:   Wed Oct 12 16:59:15 2022 +0200

    FreeBSD DCO: introduce real subnet mode


> My question is twofold:
> Is there a change that should be made in the configs or cli flags to change the POINTOPOINT flag?

With 2.6.0 and onwards, this is no longer possible from within OpenVPN.

You could do that with a combination of --ifconfig-noexec and a custom
--up script that does "what OpenVPN used to do".  But I guess there are
easier ways to achieve what you actually *want* to achieve :-)

(Technically, "--topology net30" will get you such a config, but this
is also incompatible with DCO and will become unsupported in the long run)


> If not, is there a way to get the gateway IP during the up script or after the fact?  I've printed out all the environment variables that were set before the script runs, and none of them contain the right IP.  The only way I have seen is to look in the openvpn log file and slurp the IP from there, but in some circumstances even this has been unreliable.

In "topology subnet" mode there is no designated "gateway IP" (and
never was).  What you used to see was something OpenVPN invented so
it had something to point a route to.

So, depending on what you need, this is what you can do too - take the
first IP from the subnet and declare it to be "the gateway", and if
that is used by the local interface config, take the second address.

gert
-- 
Gert Doering - Munich, Germany                             ***@***.***

**Comment by flichtenheld** [comment]
This seems like it was answered.
