### ISSUE TITLE
OpenSSL Providers on FreeBSD 14 fail, can we have better error messages?

### ISSUE THREAD

**Issue by cron2** [OpenVPN/openvpn#361]
So this on a FreeBSD 14 "current" build, about a week old sources (src commit 4ef3964b5f85f1, as of July 3).

OpenVPN complains on loading ossl 3 providers with

```
2023-07-07 13:55:34 OpenSSL: error:12800067:DSO support routines::could not load the shared library
2023-07-07 13:55:34 OpenSSL: error:12800067:DSO support routines::could not load the shared library
2023-07-07 13:55:34 OpenSSL: error:07880025:common libcrypto routines::reason(524325)
2023-07-07 13:55:34 failed to load provider 'legacy'
2023-07-07 13:55:34 Exiting due to fatal error
```

which is highly non-helpful.

OpenSSL itself prints

```
$ openssl list -provider legacy -providers
list: unable to load provider legacy
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
002061D751340000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:/usr/src/crypto/openssl/crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/ossl-modules/legacy.so): /usr/lib/ossl-modules/legacy.so: Undefined symbol "ossl_md4_functions"
002061D751340000:error:12800067:DSO support routines:DSO_load:could not load the shared library:/usr/src/crypto/openssl/crypto/dso/dso_lib.c:152:
002061D751340000:error:07880025:common libcrypto routines:provider_init:reason(524325):/usr/src/crypto/openssl/crypto/provider_core.c:912:name=legacy
```

... so it seems something in the build was messed-up wrt dependencies between various libcrypto bits and pieces - but that's what this issue is about.  It's about "can we make OpenVPN print the full OpenSSL error messages here?"...

**Comment by cron2** [comment]
It's not the usual "we do not have the full error stack" thing, more "we do have all (3) messages, but there is a --verbose flag missing"...?!

**Comment by schwabe** [comment]
There is a new `ERR_get_error_all` in OpenSSL 3.0+ instead of just `ERR_get_error` that we currently use.

**Comment by cron2** [comment]
On the FreeBSD side, it's not "my system is weird" but "other people have hit this too"... https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272281

**Comment by cron2** [comment]
commit 0f8485f2870277fb7ccdb4097380e35dc35b064e (master)
commit 101499a43d222dcefbf5c6fc6f8b71a4f5d1f533 (release/2.6)
Author: Arne Schwabe
Date:   Fri Aug 11 14:15:03 2023 +0200

     show extra info for OpenSSL errors

thanks!
