### ISSUE TITLE
Can OpenVPN be used on QNX operating system

### ISSUE THREAD

**Issue by wywanlv** [OpenVPN/openvpn#369]
I am developing applications for autonomous driving and using OpenVPN  as the transmission channel.
The software needs to run on the QNX operating system. I know that OpenVPN  requires support from the operating system, such as TUN. Can OpenVPN be used on QNX? 

I am looking forward to a reply very much. Thanks!

**Comment by cron2** [comment]
You need a `tun` device, a reasonably standard socket API, and a reasonably standard network stack with the ability to install routes pointing to the tun device.  My last experience with QNX was about 20 years ago, and I only did serial port stuff back then - but what I remember is that the C API was "reasonably standard".

So, it might work or might not, but we can't say - we haven't had any reports about QNX yet.

In any case it will need some porting effort - "how to access and configure the tun device" and "how to install routing" is something that needs per-platform code (tun.c, route.c).

I'd be willing to review patches that come out of it, but have no access to a QNX system today, and do not really have time to work on this.

**Comment by wywanlv** [comment]
> 



> You need a `tun` device, a reasonably standard socket API, and a reasonably standard network stack with the ability to install routes pointing to the tun device. My last experience with QNX was about 20 years ago, and I only did serial port stuff back then - but what I remember is that the C API was "reasonably standard".
> 
> So, it might work or might not, but we can't say - we haven't had any reports about QNX yet.
> 
> In any case it will need some porting effort - "how to access and configure the tun device" and "how to install routing" is something that needs per-platform code (tun.c, route.c).
> 
> I'd be willing to review patches that come out of it, but have no access to a QNX system today, and do not really have time to work on this.

Thank you very much for your help. I will to try more based on your suggestion. Thanks.

**Comment by cron2** [comment]
Closing this for the time being.  Reopen, or ask on the openvpn-devel@lists.sourceforge.net mailing list when you need more help.
