### ISSUE TITLE
`configure.ac`: typo in libcap-ng config: `${LIBCAPNG_CFALGS}`

### ISSUE THREAD

**Issue by whitslack** [OpenVPN/openvpn#371]
**Describe the bug**
`configure.ac` has a typo in its `libcap-ng` setup:

https://github.com/OpenVPN/openvpn/blob/3abfc0fb5ea522fb5fc45fddbf35c3cc5c8e9ef1/configure.ac#L872

`LIBCAPNG_CFALGS` should be `LIBCAPNG_CFLAGS`.

**Version information (please complete the following information):**
 - OS: n/a
 - OpenVPN version: All 2.6.x through `master`

**Comment by ordex** [comment]
Patch sent to the mailing list: https://patchwork.openvpn.net/project/openvpn2/patch/20230725065840.24568-1-a@unstable.cc/
