### ISSUE TITLE
Question: how to dump HTTP or HTTPS traffic data on OpenVPN server?

### ISSUE THREAD

**Issue by dditxu** [OpenVPN/openvpn#380]
**IMPORTANT NOTE**
NOT A BUG. IF THIS QUESTION IS OUT OF RULES,  PLEASE TELL ME.

**Describe the bug**

**To Reproduce**
I have a little bit work on dump HTTP or HTTPS traffic stream by modify openvpn source code. Is there anybody discuss about this or there maybe some other solution?

**Comment by cron2** [comment]
Reassembling TCP streams is really outside what OpenVPN should be doing.  Just run `wireshark` on the tunnel interface (tun0, etc.) and it will nicely give you the HTTP data.  It won't give you HTTPS, as that's encrypted - but neither could OpenVPN, as that's all between the browser and web server.
