### ISSUE TITLE
error connecting on windows7

### ISSUE THREAD

**Issue by mohseneshooniam** [OpenVPN/openvpn#384]
can not connect to my server on windows 7 and everytime this error appears => there was an erroe attemping to selected server. Error message: ovpnagent.request error. HELP PLZ . I am from a totally censored country.

**Comment by mohseneshooniam** [comment]
can not connect to my server on windows 7 and everytime this error appears => there was an erroe attemping to selected server. Error message: ovpnagent.request error. HELP PLZ . I am from a totally censored country.

**Comment by schwabe** [comment]
openvpnagent is part of OpenVPN Connect.

Please use support.openvpn.net for support with the OpenVPN Connect client. The OpenVPN Connect team unfortunately does not want to participate in issues raised on Github. So the only way to report/fix issues with the Connect client is through the official support.
