### ISSUE TITLE
Feature request: Outbound interface selection

### ISSUE THREAD

**Issue by pituluk** [OpenVPN/openvpn#385]
Let us choose outbound interface like simple utilities ping and wget do.
openvpn server keeps using default route for its outbound connections which is very annoying

**Comment by cron2** [comment]
OpenVPN follows the system routing table.  If you want something else, set up routing / route policy the way you need it.

My `wget` man page does not document a way to choose an outbound interface.  `ping` has a `-I iface` switch, but that will also not actually "choose an interface", it just sets the source IP - whether or not that packet will then be sent out that interface depends on system routing (again) (except for IPv6 link-locals).

Binding to a particular source IP can be done in OpenVPN with `local <address>`, and if routing is setup accordingly, can be used to select a non-default gateway.

Or just install a host route towards the VPN gateway where you connect, pointing to whatever you need to be used.

**Comment by pituluk** [comment]
I tried many times, even asked multiple people for help and still didnt figure out how to make openvpn connect to internet through different than default route.

**Comment by cron2** [comment]
This very much depends on the operating system you use, and what you specifically want to achieve.

What works everywhere is "add a route" - so, you find the IP address of the VPN server you want to connect to (`host`, `nslookup`, or by looking in the OpenVPN log) and then you add a host route for that, pointing to the "non-default router" that you want to use.  On Linux, this would look like this:

```
$ host my.openvpn.gateway
my.openvpn.gateway has address 100.64.2.3
$ sudo route add 100.64.2.3/32 via 10.1.1.1
$
````
(assuming that "10.1.1.1" is the gateway that you want OpenVPN to use, for connections to "my.openvpn.gateway").

It's not really an OpenVPN question, more a basic "how does my operating system know where to send packets to" thing.
