### ISSUE TITLE
Recommendation: add QUIC protocol

### ISSUE THREAD

**Issue by do02fw** [OpenVPN/openvpn#388]
Add QUIC protocol. quic protocol is faster and less likely to be blocked by operators.

**Comment by cron2** [comment]
QUIC is not faster than UDP (faster in which regards, anyway?), and operators that block UDP/1194 today will block QUIC tomorrow, so nothing much gained.

**Comment by do02fw** [comment]
Can you add the obfuscated traffic feature?

**Comment by cron2** [comment]
Someone volunteered to write a proper plugin framework to get that done (any static scheme we add to the code will be recognizeable and filterable).  Nothing useful was ever delivered.  So, we do not have working code, and nobody willing to maintain the code afterwards.  If that changes, we're happy to add infrastructure plus a few sample plugins.
