### ISSUE TITLE
`explicit-exit-notify` Causes Errors With DCO Adapter

### ISSUE THREAD

**Issue by Matthew1471** [OpenVPN/openvpn#396]
**Describe the bug**
Similar to #395, `explicit-exit-notify` generates errors if DCO is in use.

**To Reproduce**

Connect via DCO and have `explicit-exit-notify` in the configuration:

```
# Send server an exit notification if tunnel is restarted or OpenVPN process is exited.
# On exit/restart, this option will tell the server to immediately close its client instance object rather than waiting for a timeout.
# The n parameter (default=1) controls the maximum number of attempts that the client will try to resend the exit notification message.
explicit-exit-notify 5
```

**Expected behavior**

Either a single error explaining this option is invalid for DCO (it's fine if it's just a limitation of DCO adapters), or for the feature to behave normally (i.e. feature to be implemented on DCO adapters).

**Version information (please complete the following information):**
 - OS: Windows 11
 - OpenVPN version: 2.6.6

**Additional context**

I also note n parameter is set to 5, yet 4 log entries are observed (off by one error?)

```
2023-08-21 10:07:48 SIGTERM received, sending exit notification to peer
2023-08-21 10:07:48 Attempting to send data packet while data channel offload is in use. Dropping packet
2023-08-21 10:07:49 Attempting to send data packet while data channel offload is in use. Dropping packet
2023-08-21 10:07:50 Attempting to send data packet while data channel offload is in use. Dropping packet
2023-08-21 10:07:51 Attempting to send data packet while data channel offload is in use. Dropping packet
```

**Comment by schwabe** [comment]
This behaviour is expected. We implemented a new method of exit notify that is compatible with DCO. However, it requires 2.6 on both sides.

**Comment by Matthew1471** [comment]
Understood, thank you for your time. Is there an off-by-one error as observed by the 4 errors when 5 packets should be sent?
