### ISSUE TITLE
how to add static route in server or Client？？

### ISSUE THREAD

**Issue by friendtasy** [OpenVPN/openvpn#398]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - OpenVPN version: [e.g. 2.5.8]
 - Repeat for peer if relevant

**Additional context**

i install openvpn in synology dsm 6.2.3,the Android phone connect the vpn,can vistor Same network segment with server，but other network segmen can't vistor....

**Comment by schwabe** [comment]
Please see your synology help or support. Adding static routes in OpenVPN works with `route` but we do not know who to configure a Synology server.

**Comment by friendtasy** [comment]
> 

ok,i know how to do it.....,just modify export config file,add just like "route 10.246.0.0 255.255.0.0 "
