### ISSUE TITLE
Cannot connect to Minecraft servers, but works fine once connected previously

### ISSUE THREAD

**Issue by miningblob** [OpenVPN/openvpn#399]
I'm hosting a vpn on an Oracle Cloud free tier server. The ports I have open are TCP 1194 and UDP 1194 (along with a few others). When trying to join Minecraft servers, it fails to connect, but enabling the VPN once connected works perfectly fine. I was able to join servers yesterday, but it doesn't work today for some reason.

**To Reproduce**
Whenever I attempt to join any server with the VPN enabled, I get an error message saying "unknown host"

**Expected behavior**
It allows the connection to the server

**Version information (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - OpenVPN version: 3.4.2

**Comment by schwabe** [comment]
Version 3.4.2 indidicates an OpenVPN Connect client, which you need to contact support.openvpn.net for help. On top of that `unknown host` indicates a network or DNS problem and not an actual client problem.
