### ISSUE TITLE
Inconsistent options of "comp-lzo" between server and client cause connection flapping

### ISSUE THREAD

**Issue by HustMax** [OpenVPN/openvpn#403]
**IMPORTANT NOTE**
WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'

**Describe the bug**
The openvpn server startup the options of comp-lzo, but the client option is disable. The openvpn client shows that the connection is successful, but it is not actually connected. It will reconnect after a period of time and the appeal process is repeated.

**To Reproduce**
just let openvpn server startup the options of comp-lzo, and the client set com-lzo disable

**Expected behavior**
openvpn server will check the options of comp-lzo inconsistency and refuse the connect connection

**Version information (please complete the following information):**
 - OpenVPN server version 2.4.7 in Ubuntu 22.04
 - OpenVPN client  version 2.6.6 in Windows 10

**Additional context**
server.log
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 TLS: Initial packet from [AF_INET]192.168.110.134:56016, sid=ae33b7ca bea134d7
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 VERIFY OK: depth=1, CN=max
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 VERIFY OK: depth=0, CN=max
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 peer info: IV_VER=2.6.6
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 peer info: IV_PLAT=win
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 peer info: IV_TCPNL=1
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 peer info: IV_MTU=1600
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 peer info: IV_NCP=2
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 peer info: IV_PROTO=990
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1558', remote='link-mtu 1557'
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 WARNING: 'cipher' is present in local config but missing in remote config, local='cipher AES-256-CBC'
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
Sun Sep  3 00:13:44 2023 192.168.110.134:56016 [max] Peer Connection Initiated with [AF_INET]192.168.110.134:56016
Sun Sep  3 00:13:44 2023 MULTI: new connection by client 'max' will cause previous active sessions by this client to be dropped.  Remember to use the --duplicate-cn option if you want multiple clients using the same certificate or username to concurrently connect.
Sun Sep  3 00:13:44 2023 MULTI_sva: pool returned IPv4=10.8.0.6, IPv6=(Not enabled)
Sun Sep  3 00:13:44 2023 MULTI: Learn: 10.8.0.6 -> max/192.168.110.134:56016
Sun Sep  3 00:13:44 2023 MULTI: primary virtual IP for max/192.168.110.134:56016: 10.8.0.6
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 PUSH: Received control message: 'PUSH_REQUEST'
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 SENT CONTROL [max]: 'PUSH_REPLY,route 10.8.0.1,topology net30,ping 10,ping-restart 120,ifconfig 10.8.0.6 10.8.0.5,peer-id 1,cipher AES-256-GCM' (status=1)
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 Data Channel: using negotiated cipher 'AES-256-GCM'
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 Bad LZO decompression header byte: 96
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 Bad LZO decompression header byte: 96
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 Bad LZO decompression header byte: 96
Sun Sep  3 00:13:45 2023 max/192.168.110.134:56016 Bad LZO decompression header byte: 96
Sun Sep  3 00:13:46 2023 max/192.168.110.134:56016 Bad LZO decompression header byte: 96

**Comment by cron2** [comment]
Hi,

On Sun, Sep 03, 2023 at 08:19:21AM -0700, HustMax wrote:
> **Expected behavior**
> openvpn server will check the options of comp-lzo inconsistency and refuse the connect connection

add "compress migrate" to the server config, and things will work.

(No other "comp*" options)

gert

-- 
Gert Doering - Munich, Germany                             ***@***.***

**Comment by HustMax** [comment]
> Hi,
> On Sun, Sep 03, 2023 at 08:19:21AM -0700, HustMax wrote: **Expected behavior** openvpn server will check the options of comp-lzo inconsistency and refuse the connect connection
> add "compress migrate" to the server config, and things will work. (No other "comp*" options) gert
> […](#)
> -- Gert Doering - Munich, Germany ***@***.***

Thanks for your answer, i still want to know,  which version supports the "compress migrete"? I have upgraded the server to 2.5.9, but it not support "compress migrate", or did you mean the opions of "allow-compression asym" , but it didn't seem to work

**Comment by Pippin1st** [comment]
Hi,

--compress migrate is 2.6.

Also read here:
https://community.openvpn.net/openvpn/wiki/Compression

**Comment by cron2** [comment]
Ah, sorry, I misread which versions are on client and on server.

So, yes, if the server is 2.6.x, then it can do `compress migrate` and all compression related confusion is gone.

If the server is older, add `allow-compression asym` to the client, or remove compression both from client and server configs.  Since compression is considered insecure today, and does not help with typical https traffic anyway, "remove all traces of compression from both sides" is considered the better option.

**Comment by HustMax** [comment]
Thanks for your answers. I can't upgrade my server due to other reasons， I finally use a script to check the log file to prompt users for inconsistent config
