### ISSUE TITLE
The dhcp-option DNS is ignored on macOS

### ISSUE THREAD

**Issue by dn0sar** [OpenVPN/openvpn#407]
The dhcp-option DNS <dns-address> is ignored on macOS.

**Steps to Reproduce**

- Make sure you have a `dhcp-option DNS <custom_dns_address>` in the client config (or pushed by the server)
- Check nameservers in `scutil --dns`
- Connect to the VPN server
- Check nameservers in `scutil --dns` --> nothing changed

**Expected behavior**

- The system nameservers should be updated to the values specified in `dhcp-option DNS`.
- Note that with the same openvpn server and client configuration this gets set up successfully by the OpenVPN Connect App (v 3.4.4) (i.e., upon connecting the new DNS nameservers are present in `scutil --dns` and are used by the system).

**Version information (please complete the following information):**
 - OS: macOS 13.5.1
 - OpenVPN client version: 2.6.6 x86_64-apple-darwin22.4.0

**Comment by cron2** [comment]
It is not ignored, but there is no code inside OpenVPN to set DNS resolvers on MacOS.  So the option is passed on as an environment variable to `--up` scripts that are expected to deal with these things.

We have no plans to implement this in the short term future, as our recommendation is to use Tunnelblick for OpenVPN usage on MacOS, which wraps the "core" openvpn binary into all the desirable MacOS fanciness - GUI, status line icons, and also DNS setup.

**Comment by dn0sar** [comment]
Thanks a lot for the quick reply!
