### ISSUE TITLE
How to add flag `--data-ciphers` for openvpn?

### ISSUE THREAD

**Issue by cupen** [OpenVPN/openvpn#408]
**Describe the bug**
I can't add flag `--data-ciphers` to openvpn, which is follow the tips form logs.

```
2023-09-10 20:56:25 OPTIONS ERROR: failed to negotiate cipher with server.  Add the server's cipher ('BF-CBC') to --data-ciphers (currently 'AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305') if you want to connect to this server.
2023-09-10 20:56:25 ERROR: Failed to apply push options
2023-09-10 20:56:25 Failed to open tun/tap interface
```

**To Reproduce**
```bash
$ openvpn --data-ciphers 'BF-CBC:AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305' ./config-file
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: data-ciphers (2.6.6)
Use --help for more information.
```
or
```bash
$ openvpn ./config-file  --data-ciphers 'BF-CBC:AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305' 
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: data-ciphers (2.6.6)
Use --help for more information.
```

**Expected behavior**
Just let it work or tell me what is it when it's not flag `--data-ciphers`.

**Version information (please complete the following information):**
 - OS: archlinux
 - OpenVPN version: 2.6.6

**Comment by ordex** [comment]
The way you are creating the command line makes OpenVPN think that "./config-file" is another argument to data-ciphers.
When passing the config file along with options, th config file should be prepended by --config. So the correct command line is:
`openvpn --data-ciphers 'BF-CBC:AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305' --config ./config-file`

**Comment by cupen** [comment]
@ordex Yes, It works.  Thank you.

**Comment by liuxuzxx** [comment]
openvpn: 2.6.12 is Error!

the error information is:
```bash
sudo openvpn --data-ciphers 'BF-CBC:AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305' --config ./ITManage.ovpn
2024-12-16 15:54:06 Note: --cipher is not set. OpenVPN versions before 2.5 defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
2024-12-16 15:54:06 Unsupported cipher in --data-ciphers: BF-CBC
Options error: --data-ciphers list contains unsupported ciphers or is too long.
Use --help for more information.

```

**Comment by liuxuzxx** [comment]
When use --data-ciphers-fallback BF-CBC,the error information is:

```bash
sudo openvpn --data-ciphers 'BF-CBC:AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305' --data-ciphers-fallback BF-CBC --config ./ITManage.ovpn

2024-12-16 15:58:05 Unsupported cipher in --data-ciphers: BF-CBC
Options error: --data-ciphers list contains unsupported ciphers or is too long.
Use --help for more information.

```

**Comment by ordex** [comment]
That is telling you that your SSL library does not support BF-CBC.
BF-CBC is know to be vulnerable in various scenarios and it is no a recommended cipher, hence it is being dropped by libraries as well.
You better move away from it.

**Comment by liuxuzxx** [comment]
The company's server is already version 2.3.10. But my system is ubuntu 24.04.   Is there any solution? I downgraded the version of openvpn to 2.3.10?

**Comment by cron2** [comment]
What do you mean with "already 2.3.10"?  2.3 is ancient.  2.6.12 is the current version.

What you need to do is upgrade the server to something which is not ancient (at least 2.5.x), so it will support cipher negotiation and AES-GCM ciphers.  Then remove all `cipher` related settings from client and server config, and both versions will negotiate the strongest common cipher automatically.

WIth a client SSL library that has no `BF-CBC` anymore, a connection to a 2.3.x server is not possible (because 2.3 understands nothing else).

**Comment by ordex** [comment]
The problem is OpenSSL, not OpenVPN. I presume you are on OpenSSL 3.
In that case, IIRC you need to pass a specific option to openvpn to load the legacy openssl provider.

If you check the openvpn manpage it says:
```
--providers providers
	
Load the list of (OpenSSL) providers. This is mainly useful for using an external provider for key management like tpm2-openssl or to load the legacy provider with

--providers legacy default

Behaviour of changing this option between SIGHUP might not be well behaving. If you need to change/add/remove this option, fully restart OpenVPN.
```

**Comment by liuxuzxx** [comment]
> What do you mean with "already 2.3.10"? 2.3 is ancient. 2.6.12 is the current version.
> 
> What you need to do is upgrade the server to something which is not ancient (at least 2.5.x), so it will support cipher negotiation and AES-GCM ciphers. Then remove all `cipher` related settings from client and server config, and both versions will negotiate the strongest common cipher automatically.
> 
> WIth a client SSL library that has no `BF-CBC` anymore, a connection to a 2.3.x server is not possible (because 2.3 understands nothing else).

The company's openvpn server version is 2.3.10, and I can't change it

**Comment by cron2** [comment]
I wonder why "the company VPN server is old, insecure and nobody cares" is a ticket on *our* plate.  This should be a company internal support ticket instead.

**Comment by liuxuzxx** [comment]
> The problem is OpenSSL, not OpenVPN. I presume you are on OpenSSL 3. In that case, IIRC you need to pass a specific option to openvpn to load the legacy openssl provider.
> 
> If you check the openvpn manpage it says:
> 
> ```
> --providers providers
> 	
> Load the list of (OpenSSL) providers. This is mainly useful for using an external provider for key management like tpm2-openssl or to load the legacy provider with
> 
> --providers legacy default
> 
> Behaviour of changing this option between SIGHUP might not be well behaving. If you need to change/add/remove this option, fully restart OpenVPN.
> ```
> 
> so try passing `--providers legacy default` to openvpn

Yes,It is work, Thank you very much!

**Comment by liuxuzxx** [comment]
> I wonder why "the company VPN server is old, insecure and nobody cares" is a ticket on _our_ plate. This should be a company internal support ticket instead.

The IT department won't make changes, I'm a developer and can only follow the openvpn version

**Comment by ordex** [comment]
> The IT department won't make changes, I'm a developer and can only follow the openvpn version

just make sure they know they are running a potentially vulnerable software and they should upgrade in order to not compromise your company security.
