### ISSUE TITLE
Large auth-token results into unrecognized option error

### ISSUE THREAD

**Issue by jkroepke** [OpenVPN/openvpn#412]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**
I have a management client that authenticate OpenVPN Clients through OIDC (WEBAUTH).

To make the OpenVPN more comfortable on reauthenticate events, I want to use `auth-token` feature from OpenVPN.

But instead using gen-auth-token feature from OpenVPN, I though to use the OIDC AccessToken. OIDC AccessTokens have a builtin expire time and I'm able to reauthenticate the user against the SSO provider directly. 

On management client I invoke the command

```
client-auth 3 1
push "auth-token-user dXNlcg=="
push "auth-token ey[2180 charts]5Q"
END
```

which result into the following error:

```
2023-09-16 18:05:20 Options error: Unrecognized option or missing or extra parameter(s) in [CONFIG-STRING]:1: ksGBRnKpzD7_2i_x9pbi14aEYvKgDwsUa1p7p6eJoSbccbWn4hM83HvrGjZODDSmvTUbOzOLp5PG9JQN0ATaMfXOZCFG3puw8ZwkfjdvsonOjKCbttF8K8xkLVQ4LPxa1IXoZqXDN1rrXTBJwDqRi5Q" (2.6.6)
```

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

Running a OpenVPN Server with an Management Client on server that sends long client configs like

```
client-auth 3 1
push "auth-token-user dXNlcg=="
push "auth-token ey[2180 charts]5Q"
END
```

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04] Ubuntu 22.04
 - OpenVPN version: [e.g. 2.5.8] OpenVPN 2.6.6 [git:release/2.6/70ef43f2b9b93825] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] [DCO] built on Sep 16 2023

**Additional context**

Sound like I'm hitting a buffer max length after some character. I'm ask anyways if this is scenario that would be supported in future versions? I though, I could use auth-token like an http cookie, but http cookies supporting data until 4KB.

**Comment by schwabe** [comment]
passwords and auth-token which are handled like passwords are limited to 128 or 256 characters.

**Comment by jkroepke** [comment]
Thanks for the confirmation.

I think I have to depend on the browsers cookie store than. REAUTH via Browser/SSO seems fast enough.
