### ISSUE TITLE
CMake: daemonization and syslog is broken

### ISSUE THREAD

**Issue by lstipakov** [OpenVPN/openvpn#413]
When building using CMake on Linux, --daemon and syslog is broken due to some defines are not set.

https://gerrit.openvpn.net/c/openvpn/+/341

**Comment by flichtenheld** [comment]
Fixes merged as 8ae6c48d5d52dec8ec6e47cc1cfe89de9f2ffbcd and e363b393f2d1b72590666554e17d928c1603f8d5. Can we close this issue?
