### ISSUE TITLE
OpenVPN Freezes when client-connect freezes/don't return 

### ISSUE THREAD

**Issue by joubertdj** [OpenVPN/openvpn#418]
**Describe the bug**
I am using a client-connect script to do some tasks on the server side. Recently, through an update of some dependencies of my script, I started to experience OpenVPN "freezing". Strace indicated that just after the client-connect starts it "waits". This wait is indefinite if the script does not return. It turns out my script was broken by some updates.

**To Reproduce**
Write a small script that loops indefinitely and assign it to client-connect. When a client connects to the server, the connection will never be completed and/or aborted.

**Expected behavior**
A timeout failure was expected for a non-return server side script, and then an aborted connection. No freezing.

**Version information (please complete the following information):**
 - OS: Ubuntu 22.04
 - OpenVPN version: 2.6.6

**Comment by schwabe** [comment]
Yes. This is known behaviour. OpenVPN does not run those scripts asyncronously by default. Search the man page for deferred if you want to change your script and your OpenVPN config to run them in the background.
