### ISSUE TITLE
Connectivity issues Mac Sonoma 14.0 (23A344) 

### ISSUE THREAD

**Issue by aalokkamble** [OpenVPN/openvpn#425]
**Describe the bug**
While trying to connect to the VPN server using OpenVPN Connect, the client is repeatedly facing a 'Transport Error: socket_protect error (UDP)' issue leading to continuous reconnection attempts without successful connection.

**To Reproduce**
1. Launch OpenVPN Connect version 3.4.3 (4617) on a Macbook Air M1 running Mac Sonoma 14.0 (23A344).
2. Attempt to connect to the VPN server at IP on port 1194 via UDP.
3. Observe the Transport Error in the logs and the client trying to reconnect.

**Expected behavior**
The VPN client should establish a connection to the VPN server without any transport errors, and maintain the connection as per the configuration settings.

**Version information (please complete the following information):**
 - OS: Mac Sonoma 14.0 (23A344)
 - OpenVPN Connect version: 3.4.3 (4617)

**Additional context**
The error seems to be related to the socket_protect functionality, possibly a bug or an incompatibility issue with the current OS/VPN client version. The reconnection attempts are continuous, and the same error is thrown in each attempt.

---

**Comment by cron2** [comment]
> **Describe the bug** While trying to connect to the VPN server using OpenVPN Connect,

We do not deal with OpenVPN Connect issues here, and the Connect team does not want to look at bug reports on GH - please report bugs against Connect on https://support.openvpn.net/

Since I'm not part of the Connect team, I'm free to recommend just using Tunnelblick instead - it uses OpenVPN 2.x internally.
