### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by krutrit** [OpenVPN/openvpn#427]
![IMG_0563](https://github.com/OpenVPN/openvpn/assets/100369293/28897c18-ae7d-414f-ab77-911cb2746c57)

**Comment by krutrit** [comment]
I started having problems since I updated to the current version 3.4.0.

**Comment by cron2** [comment]
This issue tracker is for bugs of the Open Source version, OpenVPN 2.x

You are using Connect, which is a commercial offering by OpenVPN Inc., and they do not participate here - please open a bug in https://support.openvpn.net/
