### ISSUE TITLE
Is it possible to use specific adapter for OpenVPN connection?

### ISSUE THREAD

**Issue by oblomingo** [OpenVPN/openvpn#431]
**Question**
There are a couple of VPN client applications, each of them installs and uses DCO drivers.
After an installation, openvpn detects two available adapters.
`openvpn --show-adapters`

```
C:\Temp>openvpn --show-adapters
Available TAP-WIN32 / Wintun adapters [name, GUID, driver]:
'Local Area Connection' {DE11DDDE-EB7A-4F60-86F5-354D2ABD3917} ovpn-dco
'OpenVPN DCO' {662ED260-0C8F-453D-957F-B923D3D68087} ovpn-dco
```
I have noticed that both applications uses the first adapter and ignores the second one. I'm wandering is it possible setup openvpn to use specific adapter (for example, by adapter name or id)?

**Comment by cron2** [comment]
`openvpn --dev-node 'OpenVPN DCO' ` should do the job.

**Comment by lstipakov** [comment]
A small correction - in Windows you need to specify adapter's GUID:

```
c:\Program Files\OpenVPN\bin>openvpn.exe --show-adapters
Available adapters [name, GUID, driver]:
'OpenVPN Wintun' {B2A0FE9F-475B-45B1-9A7E-6321E721E50A} wintun
'OpenVPN TAP-Windows6' {B0D86004-A0D6-40B7-93EF-5C7AF64C538F} tap-windows6
'OpenVPN Data Channel Offload' {0E82A0F1-3CE3-4692-86C1-ED82CCFC6232} ovpn-dco
'OpenVPN Data Channel Offload #1' {BF16B715-9F4E-4717-A7C4-0230BC32A096} ovpn-dco
```

To use, say, `OpenVPN Data Channel Offload #1`, add following string to your .ovpn profile:

`dev-node {BF16B715-9F4E-4717-A7C4-0230BC32A096}`

Besides, may I ask what are "both applications"? Normally OpenVPN will use first available DCO adapter, which looks something like this (assuming the first of two adapters is already in use):

```
2023-10-20 09:12:20 us=421000 CreateFile failed on ovpn-dco device: \\?\ROOT#NET#0002#{cac88484-7515-4c03-82e6-71a87abac361}\ovpn-dco: Käyttö estetty.   (errno=5)
2023-10-20 09:12:20 us=421000 ovpn-dco device [OpenVPN Data Channel Offload #1] opened
```

**Comment by oblomingo** [comment]
@cron2 Sorry for a late reply, but it seems your proposed approach doesn't work with DCO drivers.
For example:
```
c:\>openvpn.exe --show-adapters
Available TAP-WIN32 / Wintun adapters [name, GUID, driver]:
'OpenVPN Connect DCO Adapter' {E546A7EB-97AA-4FCA-B99C-0AAB717B5421} ovpn-dco
'Another DCO Adapter' {6E1AE63F-3387-46BF-9435-4359D2886A53} ovpn-dco
c:\>openvpn.exe --config config.ovpn --dev-node "Another DCO Adapter"
...
Note: ignoring --dev-node as it has no effect when using data channel offload
...
ovpn-dco device [OpenVPN Connect DCO Adapter] opened
...
```
@lstipakov for example a user installs OpenVPN Connect official client and then he (or she) installs another VPN product that uses the same OpenVPN protocol and DCO driver. In this case, it is reasonable to have a separate DCO driver for each app, otherwise, the first app uninstall would remove the DCO driver and the second VPN product wouldn't work. Another case would be specific network adapter firewall/killswitch or split tunneling settings. If one VPN would set some such settings, then another VPN would have unexpected behavior if it used the same network adapter (or the same DCO driver). 

For the reasons described above, I believe OpenVPN should have the possibility to use specific DCO drivers/network adapters.

**Comment by lstipakov** [comment]
`--dev-node` support for `dco-win` was added in May 2023, so make sure you have the latest version installed.

**Comment by oblomingo** [comment]
@lstipakov it seems I have an older version:
```
c:\>openvpn.exe --version
OpenVPN 2.6.3 [git:v2.6.3/94aad8c51043a805] Windows-MSVC [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] [DCO] built on Apr 26 2023
library versions: OpenSSL 3.1.0 14 Mar 2023, LZO 2.10
Windows version 10.0 (Windows 10 or greater), amd64 executable
DCO version: v0
Originally developed by James Yonan
Copyright (C) 2002-2023 OpenVPN Inc <sales@openvpn.net>
Compile time defines: N/A
```
