### ISSUE TITLE
The address pool provided by the server has an unused address, but the client connection indicates that no addresses are available

### ISSUE THREAD

**Issue by HustMax** [OpenVPN/openvpn#434]
Hi, when I use the option `--server 10.18.12.0 255.255.255.248`  to set the addresses , 
The address of .0 and .7 are reserved，The server itself will take the .1 address .
It still has 5 addresses to allocate for clients , but I can only use 4 clients connected,  The fifth client is connected when the server indicates no address is available.
Is there any other functions need address ?

**Comment by cron2** [comment]
Either it's a bug, or we reserve .2 and .3 for the server OS side, need to check.

I'm not using IPv4 much these days, as it's always "subnet too small".  With IPv6, you can have a pool with a million addresses and never run out :-)

**Comment by selvanair** [comment]
Which version? We used to reserve the last address as it was used by the emulated "DHCP server" on Windows. This was changed more a year or two ago (don't recall the version number). Since then addresses from network+2 to broadcast -1 should be available for clients.

**Comment by HustMax** [comment]
> Which version? We used to reserve the last address as it was used by the emulated "DHCP server" on Windows. This was changed more a year or two ago (don't recall the version number). Since then addresses from network+2 to broadcast -1 should be available for clients.

My server's version is openvpn2.4.11, running on the Linux, a little old.  After testing, the address broadcast-1 was found that it could not be available. Is there any tips for address reservation?

**Comment by selvanair** [comment]
On 2.4.11 broadcast-1 is reserved. Upgrade to 2.6.

**Comment by selvanair** [comment]
One way to use that address on older versions would be to bypass the pool using `--ifconfig-push` in a client-specific ccd file.

**Comment by HustMax** [comment]
> On 2.4.11 broadcast-1 is reserved. Upgrade to 2.6.

Thanks, is there a wiki record the reason ? Is there any other way I can know this reserved address besides the code？

**Comment by Pippin1st** [comment]
Hi,

The size of the subnet is in the log.
Old would be, subnet size minus 4:

"IFCONFIG POOL: base=10.8.0.2 size=252, ...."


New would be, subnet size minus 3:

"IFCONFIG POOL: base=10.8.0.2 size=253, ...."

For topology subnet that is.

**Comment by HustMax** [comment]
> Hi,
> 
> The size of the subnet is in the log. Old /24 would be, subnet size minus 4:
> 
> "IFCONFIG POOL: base=10.8.0.2 size=252, ...."
> 
> New /24 would be, subnet size minus 3:
> 
> "IFCONFIG POOL: base=10.8.0.2 size=253, ...."
> 
> For topology subnet that is.

Thanks, I have checked and found that it's exactly what you said.
