### ISSUE TITLE
Add repository support for Ubuntu 23.10 Mantic Minotaur

### ISSUE THREAD

**Issue by joksik** [OpenVPN/openvpn#436]
Hello,
I had previously added OpenVPN repository for lunar (Ubuntu 23.04) and i always have latest version for OpenVPN and openvpn-dco-dkms but after updating few days ago from Ubuntu 23.04 to 23.10 the OpenVPN package has rolled back to older version. I tried to add new OpenVPN repo but it doesn't work (repository does not exist) so please add new repo for latest Ubuntu 23.10.

**Comment by joksik** [comment]
ok i see that repo for mantic have been added https://build.openvpn.net/debian/openvpn/release/2.6/pool/mantic/ so i cloe issue.

**Comment by easymoney322** [comment]
> so i cloe issue.
The issue is still in "open" state tho.
