### ISSUE TITLE
Protocol_dump incorrect for tls-crypt packets

### ISSUE THREAD

**Issue by reynir** [OpenVPN/openvpn#440]
It seems the flags set for `tls_auth_hmac_size` are not used for tls-crypt first of all (if they were it would not be correct as the hmac and replay packet id are swapped between tls-auth and tls-crypt packets). Then the ack list is read incorrectly: the most significant bit of the replay packet id is read as the ack list length. If the client doesn't support hmac cookies this value is likely 0. In that case bytes 1..5 of the replay packet id is read as the packet id (message id). Then the remainder of the header and the data is printed as data.
https://github.com/OpenVPN/openvpn/blob/c827f9d83a7246971f435d0053b0252e49770f11/src/openvpn/ssl.c#L4180-L4227

It's not clear to me how to fix this, but likely a flag needs to be added and passed for tls-crypt.

**Comment by cron2** [comment]
commit 227799b8345128dd3adf2029323457804209fe93
Author: Reynir Björnsson <reynir@reynir.dk>
Date:   Thu Oct 26 16:55:32 2023 +0200

    protocol_dump: tls-crypt support

via the openvpn-devel@ mailing list
