### ISSUE TITLE
TLS handshake failed, unable to install opnvpn for new clients while the old are authenticated after backup has been done for the server. i am using opensense server

### ISSUE THREAD

**Issue by zakhona** [OpenVPN/openvpn#443]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - OpenVPN version: [e.g. 2.5.8]
 - Repeat for peer if relevant

**Additional context**

**Comment by zakhona** [comment]
I am using opensense

**Comment by cron2** [comment]
Please do actually fill in the template above - what are you doing, what does the logfile show, etc.

From the looks of it, a better place to get answers might be opensense support / forum / whatever they have.
