### ISSUE TITLE
IOS - Issue last version  3.4.0 with ARISTA NGF

### ISSUE THREAD

**Issue by Miller1990** [OpenVPN/openvpn#444]
**Describe the bug**
After updating the version 3.3.4 to version 3.4.0, I can connect to my OpenVPN server running on ARISTA NGF but I cannot reach internal destinations. I cannot ping my private VPN IP or my gateway. 

**Expected behavior**
I should be able to reach internal destinations. 
With the same app version 3.4.0 connected to PfSense, it works without any problems or problems. 

**Version information (please complete the following information):**
- OpenVPN server is running on ARISTA NGF ( untangle)
 - OS: IOS 15.8 and 16.6.1
 - OpenVPN version: 3.4.0

**Comment by schwabe** [comment]
We do not deal with OpenVPN Connect issues here, and the Connect team does not want to look at bug reports on GH - please report bugs against Connect on https://support.openvpn.net/
