### ISSUE TITLE
RISC-V architecture port status

### ISSUE THREAD

**Issue by alitariq4589** [OpenVPN/openvpn#495]
Hello,
I have seen in [this](https://docs.google.com/spreadsheets/d/10rWj7QlzCiXwTZ778vex5_nRLP9gLrNC8PwPMVdgWoU/edit?usp=sharing) sheet that the status of OpenVPN about RISC-V port is marked as "Unknown". So I wanted to confirm if it is ported to RISC-V architecture or needs a maintained CI system for RISC-V builds.

In case OpenVPN needs a CI platform for RISC-V, [Cloud-V](https://cloud-v.co/) can be a good platform for automated CI builds. You can get access at [this](https://cloud-v.co/contactus) page or email directly at cloud-v@10xengineers.ai

**Comment by cron2** [comment]
OpenVPN does not run "on RISC-V".  It will run on some operating system that runs on that hardware.

So, "support for RISC-V" depends on what OS is there, and if this is a standard unixoid (FreeBSD, Linux) or something more special which is lacking relevant kernel features.  In the former case, I expect this to be a trivial excercise (`git clone ; autoreconf -vif; configure ; make`), in the latter case, outside our control...

On the OpenVPN developer side, I'm not sure if anyone has sufficient interest and time to go out and play with this platform - but if you do, and it does not work "out of the box", let us know, and we'll help making it work.

**Comment by schwabe** [comment]
Also OpenVPN already runs a wide array of instruction sets and RISCV is just another little endian instruction set. We don't expect any problems with that. As @cron2 said, if there is any issue with RISCV, we can look into but currently getting a RISCV platform or testing it, is it a not a high priority for us.

**Comment by flichtenheld** [comment]
Looks to me like the question was answered
