### ISSUE TITLE
Verbindungsaufbau eBlocker iPhone

### ISSUE THREAD

**Issue by Cla30** [OpenVPN/openvpn#496]
Wenn ich morgens mein iPhone einschalte und die VPN Verbindung starte bricht die Verbindung mehrmals (ca.10x) ab und stellt sie vermutlich auf Grund der kill-Switch Funktion wieder her. Nach einigen hin und her bleibt die Verbindung dann stabil. Ist euch das schon bekannt?
OpenVPN hat mich zu Community geschickt ;)

Wie gesagt verwende ich in iPhone mit iOS 17.3
eBlocker eOS 3.0.3 auf einem Raspberry 4B 8GB
OpenVPN App 3.4.1

**Comment by schwabe** [comment]
for support with OpenVPN Connect app on iOS you need to go to support.openvpn.net.

**Comment by Cla30** [comment]
Die Antwort von OpenVPN

Hello Team,

Hope you're doing well. We're the support team for OpenVPN Access Server and CloudConnexa.
 
Based on the logs seems you are using a VPN provided by eblocker, please reach out with their support instead
[Feb 08, 2024, 14:25:08] VERIFY OK: depth=1, /O=eBlocker Open Source/CN=eBlocker Mobile CA, signature: RSA-SHA256 
The issue you are describing appears to be related to the OpenVPN open-source community version. We sponsor the open-source project which is run and supported 100% by the Community.
You can connect with the OpenVPN open-source community and get support here:
Community Forums
OpenVPN Community
 
You're welcome to use the Free Version of OpenVPN Access Server and CloudConnexa for unmatched flexibility, scalability, and ease of use

You can see a side-by-side product comparison Here
 
Let me know if you have any further questions, I'll be glad to help you.

**Comment by cron2** [comment]
There is no "open source community version" for iOS.

So either your log files do not match your description of the environment and software version used, or someone over at corp is confused.  (But still, the advice to contact the VPN provider for initial support is valid.  They get money, they need to provide user help)

**Comment by Cla30** [comment]
Ich verwende keinen VPN Dienstleister 
Verwende OpenVPN für die Verbindung von unterwegs vom Handy ins eigene Netzwerk zuhause

**Comment by schwabe** [comment]
This bug tracker is in English. So please try to write English here. That being said, this is then still not a problem that is discussed here. OpenVPN Connect for iOS support is still reachable under support.openvpn.net like already said in the [earlier](https://github.com/OpenVPN/openvpn/issues/496#issuecomment-1935989190) message.

**Comment by schwabe** [comment]
Still. We don't support or work on OpenVPN Connect for iOS. That mean you still have to connect their support and not us. And also this is still an English issue tracker.
