### ISSUE TITLE
No actual DNS lookup but cached wrong remote IP address

### ISSUE THREAD

**Issue by jameskimmel** [OpenVPN/openvpn#502]
**Describe the bug**
OpenVPN connect does not resolve myhost.hopto.org to its correct A and AAAA record. Instead it has some cache that point to a wrong IP. 
`TCP/UDP: Preserving recently used remote address: 185.....`
That IP seems to be a Turkish IP I never had any connection to.
On the same client, nslookup in terminal for myhost.hopto.org does not resolve the wrong IP but gives the correct A and AAAA record.

Background info:
We switched from pfsense to OPNsense, so clients had a working VPN config before. 
I deleted the old config and inserted the new one. Configs are under program files, because users don't have admin right. 

**To Reproduce**
- Start OpenVPN connect with a new config
- Connect
- See "Preserving recently used remote address: and wrong IP" in logs

**Expected behavior**
Do an actual A or AAAA record lookup.

**Version information (please complete the following information):**
 - OS: Windows 11
 - OpenVPN version: 2.6.9

**Additional context**
By manually inserting an IP instead of a FQDN, I found a funny workaround that solves the problem. 
- Change config from myhost.hopto.org to 1.1.1.1
- Try to connect and of course fail
- change config it back to myhost.hopto.org
- Now it works

**Comment by flichtenheld** [comment]
A few questions:

- Since you applied the work-around to reset the cache, I assume you can not reproduce the problem anymore?
- You have no idea where that IP address came from?
- Could you post a log of a wrong connection attempt, not just the one line?
- Could you post a copy of your config (with the secrets removed, obviously)?
- Any reason you haven't updated to 2.6.x? Not that I claim that it would behave differently, more curious. 2.5.9 is a year old at this point.

**Comment by jameskimmel** [comment]
> Since you applied the work-around to reset the cache, I assume you can not reproduce the problem anymore?

I probably could. There are 5 other users I will have to do this and it happened twice already. Should I try to log something?

> You have no idea where that IP address came from?

No idea. The strange thing is, my ISP and my IP always starts with 85. 

> Could you post a log of a wrong connection attempt, not just the one line?

I did not see any warnings despite the chached password warning. But will do that when I try another client. 

> Could you post a copy of your config (with the secrets removed, obviously)?

Sure

`dev tun
persist-tun
persist-key
client
resolv-retry infinite
remote x.hoptop.org 11940 udp
lport 0
verify-x509-name "C=CH, ST=x, L=x, O=x, emailAddress=info@x, CN=openvpn-server-new" subject
remote-cert-tls server
auth-user-pass
<ca>
-----BEGIN CERTIFICATE-----
x
-----END CERTIFICATE-----

</ca>
<cert>
-----BEGIN CERTIFICATE-----
y
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
z
-----END PRIVATE KEY-----
</key>
`

> Any reason you haven't updated to 2.6.x? Not that I claim that it would behave differently, more curious. 2.5.9 is a year old at this point.

Sorry, that was a type. Of course it is 2.6.9.

**Comment by ordex** [comment]
Are you saying that 185.174.30.26 is the *wrong* IP?

I am asking because from here I also resolve (without using OpenVPN) *.hoptop.org to 185.174.30.26
If that's the case, then this means that the issue is likely unrelated to OpenVPN, but there is some DNS fault.

**Comment by jameskimmel** [comment]
> I see you later mentioned myhost.hopto.org which is not the same of the non-working connection.

Wait a minute. DingDingDingDing! You won! 
Holy cra* that is embarrassing! Are absolutely right!
I am so so sorry for wasting your time!

In my client export, I had a typo. When I replaced it with 1.1.1.1 and then replaced it again with myhost.hopto.org it worked. 
Thank you so much and sorry again for wasting your time!
