### ISSUE TITLE
FreeDeeVPN1

### ISSUE THREAD

**Issue by ff213da** [OpenVPN/openvpn#507]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - OpenVPN version: [e.g. 2.5.8]
 - Repeat for peer if relevant

**Additional context**

**Comment by cron2** [comment]
There is no problem described here, so I assume this is some sort of advertisement spam?

**Comment by ff213da** [comment]
_Great Security_
