### ISSUE TITLE
Add setting to reestablish last active vpn connection(s) on app initial launch

### ISSUE THREAD

**Issue by justmedev** [OpenVPN/openvpn#508]
### (Feature Request/Discussion)
Hey,

I would like to implement a setting, that, when active, **instantly reconnects to the last connected vpn when the application is started**.
My reasoning is, that whenever I start OpenVPN I always want to connect to my work vpn and it would be faster to just open the app and let it connect by itself then to wait for the loading and then press the connect switch.

Any opinions on the idea before I start implementing and opening a pull request?

**Comment by selvanair** [comment]
> let it connect by itself then to wait for the loading and then press the connect switch.

This repo is about community version of OpenVPN core which does not have a connect switch. If you are referring to a particular GUI/UI or some version bundled with a UI, please ask in a forum related to that product.

OpenVPN-GUI for Windows already has this feature -- see [openvpn-gui](https://github.com/OpenVPN/openvpn-gui)

**Comment by justmedev** [comment]
Oh, sorry for the confusion and thanks for the link. Could you point me towards where openvpn-gui has this implemented? I only see "on restart" actions which is not what I was referring to.
Thanks!
