### ISSUE TITLE
2.6.7: Server crash on client reconnect with wrong ca

### ISSUE THREAD

**Issue by wangyusheng1985** [OpenVPN/openvpn#509]
**Describe the bug**
When a client with an incorrect certificate reconnects to the server, the server will crash.

**To Reproduce**

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - OpenVPN version: 2.6.7
 - Repeat for peer if relevant

**Additional context**

**Comment by wangyusheng1985** [comment]
Additional context

<img width="1672" alt="image" src="https://github.com/OpenVPN/openvpn/assets/11242728/5a59ab5c-1a55-462d-b899-a325721ab6c2">

**Comment by ordex** [comment]
Please update to 2.6.9 - this bug should be already fixed there.

**Comment by cron2** [comment]
The log file is not really helpful, but as ordex said, we know there is a crashbug in 2.6.7 which can happens on malformed incoming control packets.  "Wrong CA" is a new version of this, but anyway - 2.6.7 was not a good release.

**Comment by wangyusheng1985** [comment]
Thanks a lot
