### ISSUE TITLE
connecting client to MySQL in LAN server by OpenVPN server.

### ISSUE THREAD

**Issue by FxamarAboali** [OpenVPN/openvpn#518]
hi
I am using VMWare to install OpenVPN server in ubuntu and I have a MySQL database for my app in LAN server,

how to connect my clients to my LAN server to get my database,

please help me I can't configure OpenVPN, and I can't connect to my database.

**Comment by cron2** [comment]
This is a bugtracker, not a generic help forum.
 
You can ask in https://forums.openvpn.net or on the openvpn-users (https://sourceforge.net/p/openvpn/mailman/) mailing list.

Besides that, there is lots of example configs available via Google how to set up an OpenVPN server and client.
