### ISSUE TITLE
OpenVPN Web Admin UI in ubuntu

### ISSUE THREAD

**Issue by FxamarAboali** [OpenVPN/openvpn#519]
hi
I am using VMWare to install OpenVPN server in ubuntu by openvpn-install.sh from https://github.com/angristan/openvpn-install,
 and I want to manage my OpenVPN by Web Admin UI 

please help me I can't configure OpenVPN to get Web Admin UI, and I can't show my clients to manage.

**Comment by cron2** [comment]
If you use software from another repo (angristan), please ask them, not us, how to make it work.

And again, this is a bug tracker, not a help forum.

(Duplicate of #518)
