### ISSUE TITLE
ifconfig_broadcast environment variable is empty since 2.5

### ISSUE THREAD

**Issue by lfarkas** [OpenVPN/openvpn#527]
in 2.4.x the $ifconfig_broadcast containers the last/broadcast address of the vpn network. since 2.5 it's empty in the auth-user-pass-verify cmd en vase of via-env

**Comment by flichtenheld** [comment]
Yes, this is correct. This was removed in 2.5.0. See commit 6c8b33f28970bbadcba5dac3e324550836c573cc. The only place it is still mentioned is the documentation. We definitely should remove it there as well.

**Comment by lfarkas** [comment]
and at least in the release notes as the breaking changes since many scripts can use it...

**Comment by cron2** [comment]
> and at least in the release notes as the breaking changes since many scripts can use it...

2.5.0 was released in October 2020, so close to 3.5 years ago... and you're the first one to notice.  So it's not really "many scripts".

Changing the release notes for 2.5.0 is slightly complicated, as our time machine is on repair :-) - but I agree we could be better in pointing out user-visible changes.  We normally try to point out such changes, but it seems this was overlooked as the commit itself does not really concern itself with environment variables, but with removing code for `ifconfig` etc that never served a real purpose.

**Comment by lfarkas** [comment]
rhel/centos/alma/rocky 6,7,8 only contains 2.4 while 9 is 2.5 so everybody upgrade there os will find it now. and only in case of server upgrade not client...
