### ISSUE TITLE
DNS for remote server not refreshed after power hibernation and restoring

### ISSUE THREAD

**Issue by robot-dot-win** [OpenVPN/openvpn#531]
OS: Windows 11 23H2
OpenVPN version: 2.6.10

A laptop pc is configured as an OpenVPN client, connecting to a "remote hostname port tcp4" server. At a successful connection state, put the pc power to hibernation, and move the pc to another network, where the hostname will not be resolved to the same IP as the previous network. After power restoring, OpenVPN will reconnect automatically, using the old server IP, then fails. Now you have to click "Connect" manually for reconnection.

At some previous versions(unfortunately I forget which ones) this problem does not exist.

**Comment by lstipakov** [comment]
Please provide client log with `verb 4`.

**Comment by robot-dot-win** [comment]
> Please provide client log with `verb 4`.
See attached please. Thanks!
![OpenVPN_Log](https://github.com/OpenVPN/openvpn/assets/44886984/6ea837a6-f296-45d7-a03f-83dbea6abb24)

**Comment by schwabe** [comment]
We need a complete log that also shows the configuration options being parsed as there are many options that influence that behaviour.
