### ISSUE TITLE
Installation package download problem

### ISSUE THREAD

**Issue by pptfz** [OpenVPN/openvpn#534]
I can't access google pay, how can I download the Android phone installer from the official website? thanks

**Comment by flichtenheld** [comment]
The OpenVPN community doesn't have an official Android app. If you want to get the OpenVPN, Inc. app you will need to contact OpenVPN, Inc. directly, e.g. via https://support.openvpn.com/ If you want another app, you need to contact the publisher of that app.

**Comment by pptfz** [comment]
I see. Thank you very much
