### ISSUE TITLE
can support route ip138.com 255.255.255.255 net_gateway Is this a configuration that distributes traffic based on domain names?

### ISSUE THREAD

**Issue by user00036** [OpenVPN/openvpn#540]
Because the IP corresponding to the domain name will always change, but it is very troublesome to modify it.

**Comment by cron2** [comment]
Please do not open issues for user questions.  There's a forum and a mailing list for this.

**Comment by user00036** [comment]
> 请不要为用户问题打开问题。 有一个论坛和一个邮件列表。

Can you tell me where the mailing list is?
