### ISSUE TITLE
Problems when reconnecting OpenVPN

### ISSUE THREAD

**Issue by mymail-gaa** [OpenVPN/openvpn#545]
Hello everyone, this is a question: when using OpenVPN, when a user changes a group, he remains with the IP and old group. I use OpenVPN AS, who can tell me how to explicitly delete information about the IP address of the user’s connection?

Case like this

The user connects and receives IP 172.27.0.1, he is assigned the Users group, then I change his group to BYOD, and the user reconnects; he should have been assigned an IP from the group 172.28.0.1, but he connects and receives an IP from the Users group

**Comment by ordex** [comment]
For questions regarding AS you should open a ticket on https://support.openvpn.net

This bug tracker is only about the open source OpenVPN project.
