### ISSUE TITLE
I'm getting a certificate error when I use OpenVPN to access a website with HSTS turned on.

### ISSUE THREAD

**Issue by do02fw** [OpenVPN/openvpn#546]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**

When I use OpenVPN to access a website with HSTS enabled, it says that the website certificate is incorrect, and I check the certificate information of the website and find that it has been hijacked to Facebook.com, because I am in China, China will hijack the blocked website to Facebook.com, and I am using Edge Canary browser, when I close the browser and open it again to access this website, it is normal, I use DNS is 1.1.1.1, OpenVPN does not support proxy HSTS traffic?

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04] Ubuntu24.04
 - OpenVPN version: [e.g. 2.5.8] 2.6.10
 - Repeat for peer if relevant

**Additional context**

**Comment by schwabe** [comment]
This is to be an issue with the setup that is not cloelsly related to openvpn itself.
