### ISSUE TITLE
VPN stop working

### ISSUE THREAD

**Issue by ElementShadow** [OpenVPN/openvpn#548]
Few weeks ago for some reason my VPN stop working, any idea why its happening? 
on UDP its TLS Error: TLS handshake failed
on TCP [DCO Connect error: The semaphore timeout period has expired errno=121]
And connection "yellow" but few weeks ago everything was fine.

server i connect:
Username: freevpn.me
Password: k2YbR6Ve2JBe
TCP 80, 443
UDP 53, 40000
https://freevpn.me/FreeVPN.me-OpenVPN-Bundle-July-2020.zip - certificates

any idea how solve this problem?
[Server1-TCP80.log](https://github.com/OpenVPN/openvpn/files/15211591/Server1-TCP80.log)
[Server1-UDP53.log](https://github.com/OpenVPN/openvpn/files/15211592/Server1-UDP53.log)

**Comment by cron2** [comment]
This is a public bug tracker, not a support forum - so everybody can now read your username and password... not such a good idea.

Problems with a managed VPN service (in this case, freevpn.me) need to be addressed to them first.  They take your money, they get to provide support.

This bug tracker is for bugs in the OpenVPN community product (only)

**Comment by ElementShadow** [comment]
Its free VPN service, and well i have bug with OpenVPN community product
Thats why i type here

**Comment by ordex** [comment]
This is most likely a configuration issue due to some change that was applied on the client or server side (i.e. due to upgrade).

Whoever manages the server can most likely see in the logs why the connection is timing out.

**Comment by ElementShadow** [comment]
ok thanks for answer, will try contact server owner
