### ISSUE TITLE
Debian / Ubuntu: OpenVPN apt repositories

### ISSUE THREAD

**Issue by joksik** [OpenVPN/openvpn#549]
I haven't found such a topic yet.
28 april a new version of Ubuntu 24.04 LTS has been released (Noble Numbat).
there is currently no repository for this LTS release https://build.openvpn.net/debian/openvpn/release/2.6/dists/
if this is not a problem please add a repository for the new release.

**Comment by flichtenheld** [comment]
Normally we add new distros on the next bugfix release. But not sure when 2.6.11 will be released. I will bring it up in the Community meeting.

**Comment by schwabe** [comment]
Also currently Ubuntu 24.04 still have a quite recent OpenVPN version (2.6.9 iirc)

**Comment by flichtenheld** [comment]
2.6.10 packages for Ubuntu 24.04 (noble) have been published to the usual place. See also https://github.com/OpenVPN/openvpn-build/pull/657
