### ISSUE TITLE
Continuously sending DNS (queries/responses)

### ISSUE THREAD

**Issue by Miefind** [OpenVPN/openvpn#559]
**Describe the bug**
Continuously sending DNS (queries/responses)
<img width="715" alt="image" src="https://github.com/OpenVPN/openvpn/assets/60570780/b146e74a-11bc-40c9-a976-5ab98e552790">

**Version information (please complete the following information):**
 - OS: [MacOs Sonoma ]
 - OpenVPN version: [3.4.9]

**Comment by ordex** [comment]
The information you provided is not enough. Is this DNS traffic going "over" the tunnel? or over the LAN interface?
In the former case, OpenVPN would not have any responsibility, as this is just traffic from some software and OpenVPN is transporting it.

**Comment by Miefind** [comment]
> The information you provided is not enough. Is this DNS traffic going "over" the tunnel? or over the LAN interface? In the former case, OpenVPN would not have any responsibility, as this is just traffic from some software and OpenVPN is transporting it.

It appears that the DNS traffic is indeed routed through the tunnel. However, I've observed that when using OpenVPN2 or Tunnelblick, the frequency of DNS requests is notably reduced compared to other scenarios.

**Comment by Miefind** [comment]
<img width="358" alt="image" src="https://github.com/OpenVPN/openvpn/assets/60570780/5403e67a-59bd-486e-aa94-00ab164df2b4">
When I connect to OpenVPN3 to access websites, the following log entries appear:  


![image](https://github.com/OpenVPN/openvpn/assets/60570780/60173700-f7b3-43be-9696-d8ae9508218e)

**Comment by schwabe** [comment]
This bug tracker is only for OpenVPN 2.x. If you need support with OpenVPN Connect, please use the support.openvpn.net address as the OpenVPN Connect team does not monitor or respond to Github tickets.
