### ISSUE TITLE
OpenVPN Connect with Windows 10: Program sometimes doesn't start

### ISSUE THREAD

**Issue by M4rt1n12** [OpenVPN/openvpn#573]
Hi, I support about 20 Lenovos T14s with Windows 10 and OpenVPN Connect. It occoured on at least 6 Notebooks that OpenVPN sometimes does not open the main window. It has to be closed in the task bar and then reopened. User report that a restart of the device sometimes doesn't help.

This is an issue for at least one month.

OpenVPN Connect 3.4.4
Windows: latest Windows 10

**Comment by schwabe** [comment]
Please not that OpenVPN Connect team does not read the Github issue trackers. Please contact them under support.openvpn.net
