### ISSUE TITLE
release 2.6.12  doesn't have openvpn.sln file 

### ISSUE THREAD

**Issue by czarek23242526** [OpenVPN/openvpn#590]
**IMPORTANT NOTE**
OpenVPN release 2.6.12

**Describe the bug**

The folder containing the source code does not contain the openvpn.sln file, I have a problem with compiling the code using Visual Studo 2022. How can I solve the problem? is there any instructions on how to create a solution file?

**Version information (please complete the following information):**
 - Windows 11

**Comment by cron2** [comment]
If I understand https://community.openvpn.net/openvpn/wiki/BuildingOnWindows right, the `.sln` file is created by running `bootstrap-vcpkg.bat` and `vcpkg integrate install`.

You do not need a git checkout for this, it should work as well from the 2.6.12 tarball.

**Comment by lstipakov** [comment]
That page is indeed outdated, we've switched to CMake (which internally creates .sln, but one should not care about it).

**Comment by flichtenheld** [comment]
See https://github.com/OpenVPN/openvpn/blob/master/README.cmake.md for some more up-to-date information. I will look at that Wiki page.

**Comment by flichtenheld** [comment]
Updated the Wiki page.

**Comment by czarek23242526** [comment]
Thank you for your answer and wiki updates, now everything is OK.
