### ISSUE TITLE
There is OPENVPN connect, but there is no Internet.

### ISSUE THREAD

**Issue by ilusha0561** [OpenVPN/openvpn#600]
The same situation is with Wireguard. I use instances on amazon aws
root@ip-172-31-46-123:/home/ubuntu# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enX0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 0a:92:26:9e:39:75 brd ff:ff:ff:ff:ff:ff
    inet 172.31.46.123/20 metric 100 brd 172.31.47.255 scope global dynamic enX0
       valid_lft 3381sec preferred_lft 3381sec
    inet6 fe80::892:26ff:fe9e:3975/64 scope link 
       valid_lft forever preferred_lft forever
4: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.2.41.1/24 scope global wg0
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:2f:45:0b:6b brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
6: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.2.68.1/24 scope global tun0
       valid_lft forever preferred_lft forever
root@ip-172-31-46-123:/home/ubuntu# iptables -t nat -L -nxv
Chain PREROUTING (policy ACCEPT 16700 packets, 828989 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
   16474   793186 DOCKER     0    --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
       0        0 DNAT       0    --  enX0   *       0.0.0.0/0            34.248.164.98        to:10.2.41.1

Chain INPUT (policy ACCEPT 16475 packets, 793230 bytes)
    pkts      bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 8391 packets, 650987 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
       0        0 DOCKER     0    --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 259 packets, 21848 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
      43     3784 MASQUERADE  0    --  *      enX0    10.2.68.0/24         0.0.0.0/0            /* openvpn-nat-rule */
       0        0 MASQUERADE  0    --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
      22    21187 MASQUERADE  0    --  *      enX0    10.2.41.0/24         0.0.0.0/0            /* wireguard-nat-rule */
    8287   638439 MASQUERADE  0    --  *      enX0    0.0.0.0/0            0.0.0.0/0           
       0        0 MASQUERADE  0    --  *      enX0    0.0.0.0/0            0.0.0.0/0           
       0        0 MASQUERADE  0    --  *      enX0    10.2.41.0/24         10.2.41.0/24        
       0        0 MASQUERADE  0    --  *      enX0    0.0.0.0/0            0.0.0.0/0           
       0        0 MASQUERADE  0    --  *      enX0    0.0.0.0/0            0.0.0.0/0           

Chain DOCKER (2 references)
    pkts      bytes target     prot opt in     out     source               destination         
       0        0 RETURN     0    --  docker0 *       0.0.0.0/0            0.0.0.0/0 
       root@ip-172-31-46-123:/home/ubuntu# ip route
default via 172.31.32.1 dev enX0 proto dhcp src 172.31.46.123 metric 100 
10.2.41.0/24 dev wg0 proto kernel scope link src 10.2.41.1 
10.2.68.0/24 dev tun0 proto kernel scope link src 10.2.68.1 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
172.31.0.2 via 172.31.32.1 dev enX0 proto dhcp src 172.31.46.123 metric 100 
172.31.32.0/20 dev enX0 proto kernel scope link src 172.31.46.123 metric 100 
172.31.32.1 dev enX0 proto dhcp scope link src 172.31.46.123 metric 100 
root@ip-172-31-46-123:/home/ubuntu# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled 
(it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
in security groups, ports are open in the aws console
help please

**Comment by ilusha0561** [comment]
![image](https://github.com/user-attachments/assets/5266807f-9c84-4f6e-868c-2bb791fc59f6)

**Comment by cron2** [comment]
Good morning.  This is not really the right forum to help debugging your network setup - it's a bug tracker for OpenVPN, and "The same situation is with Wireguard" makes this really outside OpenVPN.

If the tunnel comes up (wg or openvpn) and "what you want to achieve" does not work, you need to debug this step by step - do all involved machines have correct routing tables?  is "ip forwarding" enabled on intermediate nodes?  Is DNS correctly setup and reachable?

Start by pinging hop-by-hop and then "further destinations", and look at packets (wireshark/tcpdump) on each system to see what is being sent on which interface (LAN, VPN interface) and if NAT is working properly.

For OpenVPN issues, the OpenVPN forum or openvpn-users mailing list is a good place to get user help.
