### ISSUE TITLE
in-place-upgrade OpenVPN from v2.6.7 to v2.6.12

### ISSUE THREAD

**Issue by githubaba** [OpenVPN/openvpn#604]
On Windows 11 laptop, I am trying to in-place-upgrade from OpenVPN client v2.6.7 to v2.6.12 using OpenVPN-2.6.12-I001-amd64.msi.
(1) Will this require me to create or modify config file (*.ovpn)?
(2) can't find steps to follow
(3) hope to use the same certificate
Thanks.

**Comment by cron2** [comment]
Without knowing details about your setup, we can't answer what you can do or can not do - but in general, just click on the .msi installer and then confirm you want to upgrade, done.  If that does *not* work, feel free to open an issue - but for general user questions this is the wrong place.
