### ISSUE TITLE
16 KB page size support for Android 15+

### ISSUE THREAD

**Issue by yrezgui** [OpenVPN/openvpn#611]
Hello, Android 15 is introducing a 16 KB page size development mode and asking new apps to work in this mode, so that future devices can use 16 KB pages. You may want to ensure your SDK works in this mode, so that app developers using OpenVPN in their app won't be blocked when migrating their codebase. Thank you!

Read more at https://developer.android.com/16kb-page-size.

**Comment by schwabe** [comment]
There is nothing in general that prevent OpenVPN to work on 16 kB block sizes. In fact Apple ARM already uses 16 kB block size and there no bugs or issues reported from that.

If you wanted to report about missing report of a specific OpenVPN app for Android like OpenVPN for Android (https://github.com/schwabe/ics-openvpn), then you should probably open an issue with that app.

**Comment by yrezgui** [comment]
Good to hear! Thanks for the quick reply
