### ISSUE TITLE
Feature request: Option to display available HMAC algorithms

### ISSUE THREAD

**Issue by marek22k** [OpenVPN/openvpn#622]
Hello,

I would like an option to display the available HMAC algorithms. There is already `openvpn --show-ciphers` for the ciphers.

Actually, I thought that I could display the available HMACs via `openssl list -digest-algorithms`, but there are also algorithms like `whirlpool`, which OpenVPN does not seem to support:
```
Oct 04 22:22:35 openvpn1 ovpn-tunnel[1728]: OpenSSL: error:0308010C:digital envelope routines::unsupported
Oct 04 22:22:35 openvpn1 ovpn-tunnel[1728]: Message hash algorithm 'whirlpool' not found
```

**Comment by cron2** [comment]
```
$ openvpn --show-digests   
The following message digests are available for use with
OpenVPN.  A message digest is used in conjunction with
the HMAC function, to authenticate received packets.
You can specify a message digest as parameter to
the --auth option.
See also openssl list -digest-algorithms

MD5 128 bit digest size
MD5 128 bit digest size
SHA1 160 bit digest size
SHA1 160 bit digest size
...
```

the error message about whirlpool quoted above is actually an OpenSSL error, so the version of OpenSSL linked into OpenVPN does not know `whirlpool`, while the `openssl` binary claims to do...

Not sure if there are caveats beyond "if it is listed in `--show-digests` it should work".  We generally recommend using AEAD ciphers (AES-GCM or chacha-poly) as these are more performant - and do not require a separate digest, so people tend to not care very much about digest algorithms these days.
