### ISSUE TITLE
Merge debug native libs issue keep coming while connecting with other packages in flutter

### ISSUE THREAD

**Issue by utso1707097** [OpenVPN/openvpn#626]
A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libgojni.so' from inputs:
      - /Users/user/.gradle/caches/transforms-3/686b62b632b492f3fbe33560dc9ab481/transformed/jetified-openvpn_library-5f06771b85/jni/arm64-v8a/libgojni.so
      - /Users/user/.gradle/caches/transforms-3/d8210b80163f3128e88629f40b7e6045/transformed/jetified-libv2ray/jni/arm64-v8a/libgojni.so
     If you are using jniLibs and CMake IMPORTED targets, see
     
     I am facing this error. I used the pickFirst in packagingOptions but that excluded some functionality of one of the conflicting library. I don't have any idea of how to resolve the issue.
     
     packagingOptions {
//        pickFirst 'lib/arm64-v8a/libgojni.so'
//        pickFirst 'lib/armeabi-v7a/libgojni.so'
//        pickFirst 'lib/x86/libgojni.so'
//        pickFirst 'lib/x86_64/libgojni.so'
}  // I have tried this one but that results runtime error

My gradle version is 7.5

**Comment by schwabe** [comment]
I think you are reporting on the wrong repository. OpenVPN uses cmake or autoconf to build but not gradle. This looks like an Android build but the errors don't look like any official version. Also keep in mind that OpenVPN is under GPL.

**Comment by phluidwaihanko** [comment]
@utso1707097 I also this issue, did you find any solution?

**Comment by utso1707097** [comment]
Yes. I just deleted the libgojni.so from the Gradle caches folder for the every architecture (eg. Arm x86 x64 et) I mentioned. Then build worked and everything works properly.

**Comment by phluidwaihanko** [comment]
@utso1707097 You saved my time, Thanks a lot for sharing.
