### ISSUE TITLE
All platforms except Linux does not make use of "float" option on the client side

### ISSUE THREAD

**Issue by joanandk** [OpenVPN/openvpn#640]
Setup:
2 openvpn (2.6.3) server nodes, one load balanacer (lb). Packets (UDP, 1194) arrive at the lb and is distributed to one of the two nodes (without changing the source IP address). openvpn server node sends reply to the client directly (not via lb).

Test Linux:
Linux client (openvpn 2.6.3) with the float option makes connection to the answering node.

Test Windows / Mac
Windows client (tested with openvpn 2.6.3, 2.6.12 and 3.5.0) gets the udp packets from the node, but does not connect to the node as Linux does.
MacOS Sonoma client (3.5.0) behaves like Windows.
All clients have the same configuration.

**Comment by cron2** [comment]
so I understand that each node will reply with its own IP address, not with the LB address that the client sent its initial packet to.

Not sure this is a supported concept right now - but without seeing your logs from the windows 2.x client, it's hard to say what is going on (3.x is not relevant here, as we can't influence what the commercial client does).  It might not even be an OpenVPN problem, but a NAT box or firewall inbetween that does not permit the "reply packet coming from different address".

**Comment by joanandk** [comment]
Thanks for your answer.

I have run Wireshark on the Windows machine. As you said, the node answers with its own address, not the lb's IP and this is the desired way for my use case. The packets arrive on Wireshark with the node's address. So I assume, either Windows does not forward the packet to openvpn or openvpn ignores the packet as the source address is not the one it originally tried to connect to. Attached you will find the log of windows (--verb 4). 
[bfh-test.log](https://github.com/user-attachments/files/17700915/bfh-test.log)
The windows client times out and tries the lb again.

**Comment by schwabe** [comment]
This might just as well be a firewall issue on Windows.

**Comment by cron2** [comment]
`--float` on the client might just work, and accept any packet that authenticates fine.

But I guess the windows firewall might indeed also have a word to say here - wireshark won't tell, as "it arrives on the LAN", even if dropped later.  The log smells as if "nothing is received at all", so, Firewall.

**Comment by cron2** [comment]
Indeed, I'd try without active Windows firewall and see what happens then.  Wireshark won't tell if the packet correctly arrives on the LAN interface (= wireshark sees it) and then the firewall drops it as unsolicited UDP packet.

@schwabe this is client-side/p2p `--float` - the old stuff we've had forever.  It might just work - "on reception of any packet that can be authenticated, float the peer(=server) IP".

**Comment by joanandk** [comment]
Thanks for pointing out. I tried disabling the firewall, but it didn't work. Thanks to your input, I have allowed UDP from specific source IP and that worked with openvpn 2.x
OpenVPN 3 connect doesn't work (so MacOS and iOS won't work either), so I have to search for an other possibility to do the load balancing. 

Thanks and BR
