### ISSUE TITLE
dco_get_peer_stats fails at startup

### ISSUE THREAD

**Issue by ordex** [OpenVPN/openvpn#643]
```
2024-11-18 02:32:30 OpenVPN 2.6.12 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
2024-11-18 02:32:30 library versions: OpenSSL 3.0.13 30 Jan 2024, LZO 2.10
2024-11-18 02:32:30 DCO version: 0.2.20240712
2024-11-18 02:32:30 net_route_v4_best_gw query: dst 0.0.0.0
2024-11-18 02:32:30 net_route_v4_best_gw result: via 87.90.28.1 dev eth0
2024-11-18 02:32:30 WARNING: experimental option --capath ca
2024-11-18 02:32:30 net_iface_new: add FRAvpn type ovpn-dco
2024-11-18 02:32:30 DCO device FRAvpn opened
2024-11-18 02:32:30 net_iface_mtu_set: mtu 1420 for FRAvpn
2024-11-18 02:32:30 net_iface_up: set FRAvpn up
2024-11-18 02:32:31 net_addr_ptp_v4_add: 10.11.3.1 peer 10.11.3.2 dev FRAvpn
2024-11-18 02:32:31 net_iface_mtu_set: mtu 1420 for FRAvpn
2024-11-18 02:32:31 net_iface_up: set FRAvpn up
2024-11-18 02:32:31 dco_get_peer_stats: netlink reports object not found, ovpn-dco unloaded?
2024-11-18 02:32:31 dco_get_peer_stats: failed to send netlink message: No such file or directory (-2)
2024-11-18 02:32:41 dco_get_peer_stats: netlink reports object not found, ovpn-dco unloaded?
2024-11-18 02:32:41 dco_get_peer_stats: failed to send netlink message: No such file or directory (-2)
```
linux-image-6.11.8-x64v4-xanmod1

_Originally posted by @liuxyon in https://github.com/OpenVPN/ovpn-dco/issues/50#issuecomment-2481421130_

**Comment by ordex** [comment]
> Using DCO requires ROOT permissions.

yes, normally you'd start openvpn as root, unless you're dropping privileges later.
Alternatively, you can provide the openvpn binary with the `CAP_NET_ADMIN` capability and avoid running as root.

**Comment by ordex** [comment]
> 2024-11-20 13:22:24 us=812188 dco_get_peer_stats: peer-id -1

this seems a different problem.
Can you share the config file? It seems openvpn is trying to fetch the stats of the peer *before* having configured any peer.

**Comment by ordex** [comment]
I am not fully understanding. In the config you posted you wrote `mode p2p`, how come the other side is doing push-request/reply? These are specific for client/server mode, not for p2p

**Comment by ordex** [comment]
is the other side configured as `client`?

**Comment by cron2** [comment]
This is... interesting.  So, for DCO to work, you need `DATA_V2` packet format, which is enabled in server/client mode by the server pushing a `peer-id` to the client.  In `p2p` mode, everything recent enough to support DCO(!) should create a random peer-id itself, and move over to `DATA_V2`.

Seeing the pfsense side send a PUSH_REQUEST, my guess right now is that the pfsense is using `client`  while we can see from the other side config that there is no `server` but `mode p2p`.  This will not work with DCO - if you want `p2p`, both sides need to agree on using `mode p2p`.

This all said, I think you are triggering a bug on the `mode p2p, tls-server` side - it wants to do DCO, but it fails since the `p2p peer-id negotiation` did not take place (yet).  I'm a bit surprised that it fails *before* the other side even connects, while you do have a log from the pfsense that shows a successful TLS handshake - so the logs do not really match (as can be seen by the timestamps).

Anyway, we should look into that case (that is, `mode p2p, tls-server`and error at startup / or error on connect from a `client` client)

**Comment by cron2** [comment]
> is the other side configured as `client`?

My crystal ball says it is ;-)

**Comment by schwabe** [comment]
`pull`
That is a client onfig and not a p2p mode config

`pull-filter ignore peer-id`

That will most certainly cause problems.

**Comment by ordex** [comment]
> I doubt that the config matches the log from the other side/config from the other side.

I also have this feeling. Did you post your `/etc/openvpn/server.conf` file?

**Comment by ordex** [comment]
> > I also have this feeling. Did you post your `/etc/openvpn/server.conf` file?
> 
> yes, i had post it.

it seems that the configuration you have posted and the log do not truly match.

**Comment by ordex** [comment]
> this added CAP_SETPCAP
> 
> 2024-11-20 13:22:24 us=494734 Current Parameter Settings: 2024-11-20 13:22:24 us=494818 config = '/etc/openvpn/server.conf' 2024-11-20 13:22:24 us=494826 mode = 0 2024-11-20 13:22:24 us=494836 persist_config = DISABLED 2024-11-20 13:22:24 us=494842 persist_mode = 1 2024-11-20 13:22:24 us=494848 show_ciphers = DISABLED 2024-11-20 13:22:24 us=494853 NOTE: --mute triggered... 2024-11-20 13:22:24 us=494867 288 variation(s) on previous 20 message(s) suppressed by --mute 2024-11-20 13:22:24 us=494873 OpenVPN 2.6.12 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO] 2024-11-20 13:22:24 us=494888 library versions: OpenSSL 3.0.13 30 Jan 2024, LZO 2.10 2024-11-20 13:22:24 us=494922 DCO version: 0.2.20240712 2024-11-20 13:22:24 us=495100 net_route_v4_best_gw query: dst 0.0.0.0 2024-11-20 13:22:24 us=495153 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=495168 sitnl_send: rtnl: received 792 bytes 2024-11-20 13:22:24 us=495187 net_route_v4_best_gw result: via 77.80.28.1 dev eth0 2024-11-20 13:22:24 us=496697 tls-crypt-v2 server key: Cipher 'AES-256-CTR' initialized with 256 bit key 2024-11-20 13:22:24 us=496721 tls-crypt-v2 server key: Using 256 bit message hash 'SHA256' for HMAC authentication 2024-11-20 13:22:24 us=496897 Control Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1250 tun_max_mtu:0 headroom:126 payload:1600 tailroom:126 ET:0 ] 2024-11-20 13:22:24 us=497002 open_tun_dco: FRAvpn 2024-11-20 13:22:24 us=497010 net_iface_new: add FRAvpn type ovpn-dco 2024-11-20 13:22:24 us=497631 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=497668 sitnl_send: rtnl: received 36 bytes 2024-11-20 13:22:24 us=497706 ovpn_dco_register 2024-11-20 13:22:24 us=497795 DCO device FRAvpn opened 2024-11-20 13:22:24 us=497804 do_ifconfig, ipv4=1, ipv6=1 2024-11-20 13:22:24 us=497822 net_iface_mtu_set: mtu 1430 for FRAvpn 2024-11-20 13:22:24 us=638386 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=638480 sitnl_send: rtnl: received 36 bytes 2024-11-20 13:22:24 us=638557 net_iface_up: set FRAvpn up 2024-11-20 13:22:24 us=734011 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=734110 sitnl_send: rtnl: received 36 bytes 2024-11-20 13:22:24 us=734144 net_addr_ptp_v4_add: 10.11.3.1 peer 10.11.3.2 dev FRAvpn 2024-11-20 13:22:24 us=811193 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=811294 sitnl_send: rtnl: received 36 bytes 2024-11-20 13:22:24 us=811371 net_iface_mtu_set: mtu 1430 for FRAvpn 2024-11-20 13:22:24 us=811406 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=811413 sitnl_send: rtnl: received 36 bytes 2024-11-20 13:22:24 us=811431 net_iface_up: set FRAvpn up 2024-11-20 13:22:24 us=811482 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=811489 sitnl_send: rtnl: received 36 bytes 2024-11-20 13:22:24 us=811499 net_addr_v6_add: 2a0d:2408:513:a::2/124 dev FRAvpn 2024-11-20 13:22:24 us=811703 sitnl_send: checking for received messages 2024-11-20 13:22:24 us=811715 sitnl_send: rtnl: received 36 bytes 2024-11-20 13:22:24 us=811816 Data Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1430 tun_max_mtu:1600 headroom:136 payload:1768 tailroom:562 ET:0 ] 2024-11-20 13:22:24 us=812083 Socket Buffers: R=[67108864->67108864] S=[67108864->67108864] 2024-11-20 13:22:24 us=812095 setsockopt(IPV6_V6ONLY=0) 2024-11-20 13:22:24 us=812116 UDPv6 link local (bound): [AF_INET6]2a04:e9c0:18:71a::1:51758 2024-11-20 13:22:24 us=812122 UDPv6 link remote: [AF_UNSPEC] 2024-11-20 13:22:24 us=812157 UID set to root 2024-11-20 13:22:24 us=812166 GID set to root 2024-11-20 13:22:24 us=812172 Capabilities retained: CAP_NET_ADMIN 2024-11-20 13:22:24 us=812188 dco_get_peer_stats: peer-id -1 2024-11-20 13:22:24 us=812226 dco_get_peer_stats: netlink reports object not found, ovpn-dco unloaded? 2024-11-20 13:22:24 us=812234 dco_get_peer_stats: failed to send netlink message: No such file or directory (-2)

question: does openvpn stop after this message? Or it simply continue to run?

**Comment by ordex** [comment]
btw make sure to remove the `pull` directive on BSD too. These options are not truly expected to be mixed this way.

**Comment by ordex** [comment]
> continue to run

ok, then this is not a real problem. it's just the statistics polling that fails because no peer is yet connected. You can ignore that message

**Comment by ordex** [comment]
> if i want to using ifconfig 10.11.3.1 10.11.3.2, ifconfig-ipv6 2a0d:2408:513:a::2/124 2a0d:2408:513:a::3

this looks good to me, as long as it's inverted on the other peer.

Please make sure to remove `pull` from the config as it is not expected to work with `mode p2p`

**Comment by ordex** [comment]
> 2024-11-20 18:50:40 us=188322 TLS: Initial packet from [AF_INET6]2418:827:404:ac0::58394, sid=767b5194 b90127d0

some connection is happening here on ubuntu. Please show the log from the pfsense side.

**Comment by ordex** [comment]
> Nov 20 19:16:15 openvpn 57098 WARNING: using --pull/--client and --ifconfig together is probably not what you want

here it says that you are still using `pull` and something it taking down the process immediately

**Comment by schwabe** [comment]
Your config is still extremely questionable. tls-crypt-v2 basically requires pull to actually work properly.

**Comment by schwabe** [comment]
@liuxyon it works fine in p2p mode but what you shown as configs and message you presented, suggests that you don't actually understand what p2p mode is. You want p2p mode but are saying messages like 

> when i setup add mode server, ubuntu log show

`mode server` is the opposite of mode p2p

Also your logs/config and what you are saying is all contradiction each other, so it really hard for us to make sense of what you are actually doing.

**Comment by schwabe** [comment]
> I have to use encrypted data packet headers, otherwise they will be recognized and blocked by GFW.
> Error: TLS handshake failed

The concept of encrypted data packet headers does not exist in OpenVPN.

**Comment by ordex** [comment]
> Nov 20 20:23:03 openvpn 56039 WARNING: using --pull/--client and --ifconfig together is probably not what you want

pfsense keeps showing this. it means that it is somehow enabling --pull again.
Maybe you should give up p2p and go with a normal clients/server setup.

However, please note that this is a bug tracker, not a support channel.
For support you can write to the user mailing list or in our IRC channel on libera.chat

**Comment by ordex** [comment]
https://sourceforge.net/projects/openvpn/lists/openvpn-users

**Comment by schwabe** [comment]
@liuxyon we tested p2p mode with DCO and it works. However, we lost faith in your ability to setup it correctly, so we are no longer treating this issue as a bug report/issue but rather as a user configuration and as thus, it does not belong on this issue tracker.

**Comment by ordex** [comment]
This issue is closed. Please write to the mailing list or join IRC.
