### ISSUE TITLE
Sample Config : Minor Typo "and and"

### ISSUE THREAD

**Issue by Matthew1471** [OpenVPN/openvpn#644]
Minor typo in [sample-config file](https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/server.conf#L201) line 201 - 202 where "and" is repeated twice:

```
# all IP traffic such as web browsing and
# and DNS lookups to go through the VPN
```

**Comment by networkssecurity** [comment]
185.51.200.2
178.22.122.100
[vpn download](https://www.darianet.com/whats-vpn/)

you can download vpn or set dns for use yotube free without Connection problem
