### ISSUE TITLE
The client socket is reconnected uniformly

### ISSUE THREAD

**Issue by lsx1205** [OpenVPN/openvpn#646]
<img width="406" alt="image" src="https://github.com/user-attachments/assets/ad097110-aaa1-4afa-87df-609c43438bdf">
When the client connected, the connection button turned in a circle, and the request did not go to the server. I used the oauth plug-in as the authentication method, and it would jump to our casdoor for authentication, but it kept reporting this error

**Comment by lsx1205** [comment]
The network connectivity is normal

**Comment by cron2** [comment]
OpenVPN Connect need to go to https://support.openvpn.net

This issue tracker is only for OpenVPN Community edition (2.x).
