### ISSUE TITLE
Behavior of max-clients

### ISSUE THREAD

**Issue by joanandk** [OpenVPN/openvpn#647]
Hi,
I am using openvpn 2.6.3 with max-client. The behavior of the server is, when max client is reached and a new client tries to connect, then the client with the lowest IP gets kicked out. After a while, the new client who (now) has the lowest IP gets kicked out.
I first suspected that this is due to connections from the same user, so I created different users to test. Didn't help.
I tried using ping to keep the connections busy, didn't change the behavior of the disconnect.

If I am not using max-clients, then the new client does not get any IP, but stays connected to the server. This is it not ideal as the next remote entry is not tried by the client.

Is there any way to stop new clients from kicking out the connected client? 
IMHO if a client tries to connect to a server which has no more place available, it should get a reject  response. This would not break if someone is using multiple remote entries and the client will try the next server.

I have tried the following setup: A /29 subnet (max. 6 clients), max-clients 5 and connected 6 clients. Topology is subnet.

Clients are openvpn 2.6.3 too. OS: Debian 12

Thanks and BR

**Comment by schwabe** [comment]
`max-client` is always active. The default is 1024.

With kicked-out what do you mean? I don't think we a mechanism to kick out clients for other ones. Adding logs would really help.

**Comment by joanandk** [comment]
Thanks. I some how missed the fix while reading the changelog.rst.

BR
