### ISSUE TITLE
Private DNS Queries Not Resolved by Google's Private DNS Resolver 169.254.169.254

### ISSUE THREAD

**Issue by saidfarah** [OpenVPN/openvpn#651]
**Describe the bug**
Private DNS queries routed through an OpenVPN client fail to resolve using the private IP 169.254.169.254, which is configured to handle private zones in GCP. Despite pushing the DNS settings via OpenVPN's server.conf and verifying configurations, the queries aren't resolved. I've create a private DNS zone in Cloud DNS in GCP that is using the VPC network which the VM is hosted in.

Once connected to OpenVPN via OpenVPN Connect client and I run nslookup on my local on the domain for the private zone it, only my local it returns: 
```
nslookup delete.test.internal
;; connection timed out; no servers could be reached
```

Inside the VM when I run it it returns:
```
root@server:/etc/openvpn# nslookup delete.test.internal
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	delete.test.internal
Address: 20.20.20.20
```

**Version information (please complete the following information):**
 - OS: Debian 12
 - OpenVPN version: 2.6.12

**To Reproduce**
Set up OpenVPN on a GCP VM and configure it to push DNS options:
```
push "dhcp-option DNS 169.254.169.254"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
```
Connect a client to the OpenVPN server using OpenVPN Connect that uses the [openvpn-auth-oauth2](https://github.com/jkroepke/openvpn-auth-oauth2) management client.
Attempt to resolve a private DNS record (e.g., nslookup delete.test.internal 169.254.169.254).

**Expected behavior**
When ran on my local MacOS terminal
```
nslookup delete.test.internal 169.254.169.254
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	delete.test.internal
Address: 20.20.20.20
```

**Version information (please complete the following information):**
 - OS: Debian 12
 - OpenVPN version: 2.6.12

**Additional context**
```
root@server:/etc/openvpn# resolvectl status
Global
         Protocols: +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 169.254.169.254
        DNS Servers 169.254.169.254
         DNS Domain local

Link 2 (ens4)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 169.254.169.254
       DNS Servers: 169.254.169.254
        DNS Domain: c.<project-name>.internal google.internal

Link 14 (tun0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

**Comment by schwabe** [comment]
OpenVPN 2.x needs an up script or similar to handle DNS, by default openvpn does not parse the dhcp-options that are pushed.
