### ISSUE TITLE
OpenVPN on macOS does not connect after reboot

### ISSUE THREAD

**Issue by freebrowser1** [OpenVPN/openvpn#658]
**Describe the bug**
Using OpenVPN on macOS (Sonoma or Sequoia) works, but until a reboot. After each reboor OpenVPN has to be reinstalled. It does not tocnnect to any VPN server.
**To Reproduce**
Run OpenVPN and connect to a server. Works normally. Then reboot the Mac. OpenVPN cannot connect to server anymore.

**Expected behavior**
OpenVPN should keep working after a reboot like any other app.

**Version information (please complete the following information):**
 - OS: macOS 15.1
 - OpenVPN version: 3.5.12

**Additional context**

**Comment by cron2** [comment]
Problems with the commercial "OpenVPN Connect" product need to be reported to https://support.openvpn.net/

This issue tracker deals with the open source / community version only (OpenVPN 2.x) - and I recommend on macOS to install Tunnelblick, which just works.
