### ISSUE TITLE
Cannot connect OVPN (UDP) through SOCKS5 proxy

### ISSUE THREAD

**Issue by Comandante1977** [OpenVPN/openvpn#661]
Trying to connect with udp protocol through socks5 proxy (shadowsocks or vless).
Both proxies support UDP. 
But no connect to openvpn server. It seems that no packets going through local proxy.

Proxy is on local machine (client).

Server: OVPN 2.5 and OVPN 2.6 (debian)
Client: OVPN 2.4 and OVPN 2.6 (opensuse)

Here's client config:
```
key-direction 1
auth-user-pass
client
dev tun
dhcp-option DNS 1.1.1.1
proto udp
remote <my server ip> 33896
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-GCM
ignore-unknown-option block-outside-dns
verb 3
mute-replay-warnings
socks-proxy 127.0.0.1 1080
route <my server ip> 255.255.255.255 net_gateway

<ca>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</ca>
<tls-crypt>
-----BEGIN OpenVPN Static key V1-----

-----END OpenVPN Static key V1-----
</tls-crypt>
```
Here's server config:
```

setenv deferred_auth_pam 1
plugin /usr/lib/openvpn/radiusplugin.so /etc/openvpn/radiusplugin.cnf
verify-client-cert none
key-direction 0
port 1194
proto udp
scramble obfuscate Kp77j9hawQ3PzOYqbUuWBb+MvzYbzbvm
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
server-ipv6 fddd:1194:1194:1194::/64
push "redirect-gateway def1 ipv6 bypass-dhcp"
ifconfig-pool-persist ipp.txt
push "explicit-exit-notify 3"
sndbuf 524288
rcvbuf 524288
push "sndbuf 524288"
push "rcvbuf 524288"
keepalive 10 120
cipher AES-256-GCM
user nobody
group nogroup
persist-key
persist-tun
verb 3
crl-verify crl.pem
explicit-exit-notify 3
management 127.0.0.1 7555
log-append /var/log/openvpn/openvpn.log
txqueuelen 4000
mute-replay-warnings
username-as-common-name 

```

With TCP protocol everything works just fine. 
Without proxy UDP also works.

Any help? Thanks.

**Comment by cron2** [comment]
> Trying to connect with udp protocol through socks5 proxy (shadowsocks or vless). Both proxies support UDP. But no connect to openvpn server. It seems that no packets going through local proxy.
> 
> Proxy is on local machine (client).
[..]
> socks-proxy 127.0.0.1 1080

I guess that it's not "a socks proxy on localhost, which is then sourcing packets to `my server ip`" (because that would be a bit pointless) but "a socks proxy that has a private connection to a socks server somewhere *else*, and the packets sent by the client-side piece of software go to `some other IP` (which is then recursively routed into the VPN).

In that case, figure out where this "socks" software piece is sending its packet, and add a `route` statement for *that* address to your openvpn client config.

Without more details on what the socks proxy is doing, this is all guesswork, though.  Maybe it has a log of some sorts?

(Also, while at it, it should be pointed out that `scramble obfuscate` is not something official OpenVPN supports, so you are running some sort of modified software which we can't support if that modification breaks things)

**Comment by Comandante1977** [comment]
> I guess that it's not "a socks proxy on localhost, which is then sourcing packets to `my server ip`" (because that would be a bit pointless) but "a socks proxy that has a private connection to a socks server somewhere _else_, and the packets sent by the client-side piece of software go to `some other IP` (which is then recursively routed into the VPN).

 On local machine I have OVPN client <-> Proxy 
 Proxy by itself working just fine

> 
> In that case, figure out where this "socks" software piece is sending its packet, and add a `route` statement for _that_ address to your openvpn client config.
> 
> Without more details on what the socks proxy is doing, this is all guesswork, though. Maybe it has a log of some sorts?
> 
> (Also, while at it, it should be pointed out that `scramble obfuscate` is not something official OpenVPN supports, so you are running some sort of modified software which we can't support if that modification breaks things)

**Comment by cron2** [comment]
> On local machine I have OVPN client <-> Proxy
> Proxy by itself working just fine

I understand that.  This is not the point.  This "proxy software on the local host" will receive packets from OpenVPN (localhost) and send it *somewhere*.  If that destination address is routed into the VPN again (which is what `redirect-gateway` will do) the proxy connection will break.  This is not an "OpenVPN is not working" problem but "OpenVPN is breaking your proxy" (and thus, OpenVPN is not working either, after connection establishment).

So please re-read what I wrote above - find out where that proxy software is sending its packets, and add *that* address to the openvpn client config (`route $that 255.255.255.255 net_gateway`).

Now, if OpenVPN cannot even establish a connection using the proxy, this would be something different - having an OpenVPN and proxy log would definitely be more helpful than having to guess.

**Comment by Comandante1977** [comment]
Thank you! You routed me to the right way!
First of all I've look into debug log of OVPN and saw, that on udp protocol --float option are required for my config with proxy.
After this, unchanged ovpn just work fine via udp. Changed version (scramble) still no. Logs saying
unknown udp packet. It normal. Just run without this change.

Thanks a lot!

**Comment by unknown484** [comment]
Can you please help me regarding this issue?

**Comment by cron2** [comment]
> Can you please help me regarding this issue?

"This issue" has been closed in December 2024, and I do not think that whatever is not working for you is the same thing.

If it *is* the same thing, the solution can be found by reading the issue.  If not, please open a new issue, and precisely describe your problem, including an openvpn log with `verb 4`.

**Comment by unknown484** [comment]
> > Can you please help me regarding this issue?
> 
> "This issue" has been closed in December 2024, and I do not think that whatever is not working for you is the same thing.
> 
> If it *is* the same thing, the solution can be found by reading the issue.  If not, please open a new issue, and precisely describe your problem, including an openvpn log with `verb 


I have a question regarding whether it is possible to use a SOCKS5 proxy in the Sing-box app and OpenVPN simultaneously on an Android device.

Any help or guidance you can provide on this matter would be highly appreciated.

Thanks in advance,

Sam

**Comment by cron2** [comment]
This is an issue tracker, to track bugs in the software.  It's not a user support forum.  https://forums.openvpn.net/ might be more suitable, or the openvpn-users mailing list.
